/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts/{accountID}/bracket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign an account to a bracket (or clear it) */
        put: operations["admin-assign-bracket"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anticheat/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One account's sharing and IP-overlap evidence */
        get: operations["admin-anticheat-account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anticheat/flag-sharing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flag-sharing evidence grouped by offender pair (paginated) */
        get: operations["admin-anticheat-flag-sharing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anticheat/ip-overlap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts sharing a submission IP (signal, not verdict; paginated) */
        get: operations["admin-anticheat-ip-overlap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anticheat/unissued-solves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solves on unique-flag challenges by accounts never issued an instance (paginated) */
        get: operations["admin-anticheat-unissued-solves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the audit trail (paginated, newest first, filterable) */
        get: operations["admin-list-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brackets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List brackets */
        get: operations["admin-list-brackets"];
        put?: never;
        /** Create a bracket */
        post: operations["admin-create-bracket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brackets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a bracket (members are unassigned, not deleted) */
        delete: operations["admin-delete-bracket"];
        options?: never;
        head?: never;
        /** Update a bracket (partial) */
        patch: operations["admin-update-bracket"];
        trace?: never;
    };
    "/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a challenge */
        post: operations["admin-create-challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the board position of many challenges at once */
        put: operations["admin-reorder-challenges"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a challenge (refused while it has solves) */
        delete: operations["admin-delete-challenge"];
        options?: never;
        head?: never;
        /** Update a challenge (partial) */
        patch: operations["admin-update-challenge"];
        trace?: never;
    };
    "/challenges/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a file to a challenge */
        post: operations["admin-upload-file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{id}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a flag */
        post: operations["admin-add-flag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{id}/flags/{flagID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a flag */
        delete: operations["admin-delete-flag"];
        options?: never;
        head?: never;
        /** Update a flag (partial) */
        patch: operations["admin-update-flag"];
        trace?: never;
    };
    "/challenges/{id}/hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a hint */
        post: operations["admin-add-hint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{id}/hints/{hintID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a hint */
        delete: operations["admin-delete-hint"];
        options?: never;
        head?: never;
        /** Update a hint (partial) */
        patch: operations["admin-update-hint"];
        trace?: never;
    };
    "/challenges/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Show or hide a challenge */
        put: operations["admin-set-challenge-state"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the editable config knobs */
        get: operations["admin-get-config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update config knobs (partial) */
        patch: operations["admin-update-config"];
        trace?: never;
    };
    "/files/{fileID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a challenge file */
        delete: operations["admin-delete-file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a notification */
        post: operations["admin-create-notification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every tag with its usage count */
        get: operations["admin-list-tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{value}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a tag from every challenge (force required while in use) */
        delete: operations["admin-delete-tag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{value}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename a tag, merging it into the destination */
        post: operations["admin-merge-tag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (paginated) */
        get: operations["admin-list-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ban or unban a user */
        put: operations["admin-set-user-banned"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Promote or demote a user */
        put: operations["admin-set-user-role"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcAccountReportOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AcAccountReportOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            account_id: number;
            ip_overlap: components["schemas"]["AcIPNeighborBody"][] | null;
            sharing: components["schemas"]["AcSharingEdgeBody"][] | null;
        };
        AcFlagSharingOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AcFlagSharingOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            page: number;
            pairs: components["schemas"]["AcSharingPairBody"][] | null;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            total: number;
        };
        AcIPClusterBody: {
            /** Format: int64 */
            account_count: number;
            account_ids: number[] | null;
            /** Format: date-time */
            first_seen: string;
            ip: string;
            /** Format: date-time */
            last_seen: string;
        };
        AcIPNeighborBody: {
            /** Format: date-time */
            first_seen: string;
            ip: string;
            /** Format: date-time */
            last_seen: string;
            /** Format: int64 */
            other_account_id: number;
            /** Format: int64 */
            submission_count: number;
        };
        AcIPOverlapOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AcIPOverlapOutputBody.json
             */
            readonly $schema?: string;
            clusters: components["schemas"]["AcIPClusterBody"][] | null;
            /** Format: int64 */
            min_accounts: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            total: number;
        };
        AcSharingEdgeBody: {
            challenge_ids: number[] | null;
            /** Format: int64 */
            counterparty: number;
            direction: string;
            /** Format: date-time */
            first_seen: string;
            /** Format: date-time */
            last_seen: string;
            /** Format: int64 */
            submission_count: number;
        };
        AcSharingPairBody: {
            /** Format: int64 */
            challenge_count: number;
            challenge_ids: number[] | null;
            /** Format: date-time */
            first_seen: string;
            /** Format: int64 */
            issued_to: number;
            /** Format: date-time */
            last_seen: string;
            /** Format: int64 */
            submission_count: number;
            /** Format: int64 */
            submitter: number;
        };
        AcUnissuedSolveBody: {
            /** Format: int64 */
            account_id: number;
            /** Format: int64 */
            challenge_id: number;
            challenge_name: string;
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            solve_id: number;
            /** Format: int64 */
            team_id?: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int32 */
            value: number;
        };
        AcUnissuedSolvesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AcUnissuedSolvesOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            solves: components["schemas"]["AcUnissuedSolveBody"][] | null;
            /** Format: int64 */
            total: number;
        };
        AdminAddFlagInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminAddFlagInputBody.json
             */
            readonly $schema?: string;
            case_insensitive?: boolean;
            content: string;
            /** @enum {string} */
            type: "static" | "regex";
        };
        AdminAddHintInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminAddHintInputBody.json
             */
            readonly $schema?: string;
            content: string;
            /** Format: int32 */
            cost?: number;
            /** Format: int32 */
            position?: number;
            title?: string;
        };
        AdminAssignBracketInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminAssignBracketInputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            bracket_id: number | null;
        };
        AdminAssignBracketOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminAssignBracketOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            account_id: number;
            /** Format: int64 */
            bracket_id: number | null;
            name: string;
        };
        AdminAuditEntry: {
            action: string;
            /** Format: int64 */
            actor_id?: number;
            after?: unknown;
            /** Format: date-time */
            at: string;
            before?: unknown;
            /** Format: int64 */
            id: number;
            ip?: string;
            /** Format: int64 */
            target_id?: number;
            target_table: string;
        };
        AdminBanInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminBanInputBody.json
             */
            readonly $schema?: string;
            banned: boolean;
        };
        AdminBanOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminBanOutputBody.json
             */
            readonly $schema?: string;
            banned: boolean;
            /** Format: int64 */
            id: number;
            name: string;
        };
        AdminBracketBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminBracketBody.json
             */
            readonly $schema?: string;
            applies_to: string;
            description?: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
        AdminChallengeBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminChallengeBody.json
             */
            readonly $schema?: string;
            attribution?: string;
            category: string;
            connection_info?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            decay?: number;
            description: string;
            function: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            initial?: number;
            logic: string;
            /** Format: int32 */
            max_attempts: number;
            /** Format: int32 */
            minimum?: number;
            name: string;
            /** Format: int32 */
            position: number;
            state: string;
            type: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            value: number;
        };
        AdminChallengeStateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminChallengeStateInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            state: "visible" | "hidden";
        };
        AdminConfigInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminConfigInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            account_visibility?: "public" | "private";
            /** @enum {string} */
            challenge_visibility?: "public" | "private";
            description?: string;
            /** Format: date-time */
            end?: string | null;
            /** Format: date-time */
            freeze?: string | null;
            name?: string;
            /** @enum {string} */
            registration_visibility?: "public" | "private" | "mlc";
            /** @enum {string} */
            score_visibility?: "public" | "private" | "hidden";
            /** Format: date-time */
            start?: string | null;
            theme?: string;
            theme_tokens?: string;
        };
        AdminConfigOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminConfigOutputBody.json
             */
            readonly $schema?: string;
            account_visibility: string;
            challenge_visibility: string;
            description: string;
            /** Format: date-time */
            end?: string;
            /** Format: date-time */
            freeze?: string;
            name: string;
            registration_visibility: string;
            score_visibility: string;
            /** Format: date-time */
            start?: string;
            theme: string;
            theme_tokens?: string;
        };
        AdminCreateBracketInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminCreateBracketInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            applies_to: "users" | "teams";
            description?: string;
            name: string;
        };
        AdminCreateChallengeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminCreateChallengeInputBody.json
             */
            readonly $schema?: string;
            attribution?: string;
            category: string;
            connection_info?: string;
            /** Format: int32 */
            decay?: number;
            description?: string;
            /**
             * @default static
             * @enum {string}
             */
            function: "static" | "linear" | "logarithmic";
            /** Format: int32 */
            initial?: number;
            /**
             * @default any
             * @enum {string}
             */
            logic: "any" | "all";
            /** Format: int32 */
            max_attempts?: number;
            /** Format: int32 */
            minimum?: number;
            name: string;
            /** Format: int32 */
            position?: number;
            /**
             * @default visible
             * @enum {string}
             */
            state: "visible" | "hidden";
            /** Format: int32 */
            value: number;
        };
        AdminCreateNotificationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminCreateNotificationInputBody.json
             */
            readonly $schema?: string;
            content: string;
            title: string;
        };
        AdminFileBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminFileBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            challenge_id: number | null;
            /** Format: int64 */
            id: number;
            name: string;
            sha256: string;
            /** Format: int64 */
            size_bytes: number;
        };
        AdminFlagBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminFlagBody.json
             */
            readonly $schema?: string;
            case_insensitive: boolean;
            /** Format: int64 */
            challenge_id: number;
            content: string;
            /** Format: int64 */
            id: number;
            type: string;
        };
        AdminHintBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminHintBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            challenge_id: number;
            content: string;
            /** Format: int32 */
            cost: number;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            position: number;
            title?: string;
        };
        AdminListAuditOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminListAuditOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["AdminAuditEntry"][] | null;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            total: number;
        };
        AdminListBracketsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminListBracketsOutputBody.json
             */
            readonly $schema?: string;
            brackets: components["schemas"]["AdminBracketBody"][] | null;
        };
        AdminListTagsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminListTagsOutputBody.json
             */
            readonly $schema?: string;
            tags: components["schemas"]["AdminTag"][] | null;
        };
        AdminListUsersOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminListUsersOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            total: number;
            users: components["schemas"]["AdminUserBody"][] | null;
        };
        AdminMergeTagInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminMergeTagInputBody.json
             */
            readonly $schema?: string;
            into: string;
        };
        AdminReorderInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminReorderInputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["Item"][] | null;
        };
        AdminReorderOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminReorderOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            reordered: number;
        };
        AdminRoleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminRoleInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            role: "user" | "admin";
        };
        AdminRoleOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminRoleOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            id: number;
            name: string;
            role: string;
        };
        AdminTag: {
            /** Format: int64 */
            uses: number;
            value: string;
        };
        AdminUpdateBracketInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminUpdateBracketInputBody.json
             */
            readonly $schema?: string;
            description?: string;
            name?: string;
        };
        AdminUpdateChallengeInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminUpdateChallengeInputBody.json
             */
            readonly $schema?: string;
            attribution?: string | null;
            category?: string;
            connection_info?: string | null;
            /** Format: int32 */
            decay?: number | null;
            description?: string;
            /** @enum {string} */
            function?: "static" | "linear" | "logarithmic";
            /** Format: int32 */
            initial?: number | null;
            /** @enum {string} */
            logic?: "any" | "all";
            /** Format: int32 */
            max_attempts?: number;
            /** Format: int32 */
            minimum?: number | null;
            name?: string;
            /** Format: int32 */
            position?: number;
            /** Format: int32 */
            value?: number;
        };
        AdminUpdateFlagInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminUpdateFlagInputBody.json
             */
            readonly $schema?: string;
            case_insensitive?: boolean;
            content?: string;
            /** @enum {string} */
            type?: "static" | "regex";
        };
        AdminUpdateHintInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/AdminUpdateHintInputBody.json
             */
            readonly $schema?: string;
            content?: string;
            /** Format: int32 */
            cost?: number;
            /** Format: int32 */
            position?: number;
            title?: string;
        };
        AdminUserBody: {
            banned: boolean;
            /** Format: date-time */
            created_at: string;
            email: string;
            hidden: boolean;
            /** Format: int64 */
            id: number;
            name: string;
            role: string;
            /** Format: int64 */
            team_id?: number;
            verified: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Item: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            position: number;
        };
        NotificationBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/v1/admin/schemas/NotificationBody.json
             */
            readonly $schema?: string;
            content: string;
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            id: number;
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-assign-bracket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAssignBracketInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAssignBracketOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-anticheat-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcAccountReportOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-anticheat-flag-sharing": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcFlagSharingOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-anticheat-ip-overlap": {
        parameters: {
            query?: {
                min_accounts?: number;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcIPOverlapOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-anticheat-unissued-solves": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcUnissuedSolvesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-audit": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                actor?: number;
                action?: "INSERT" | "UPDATE" | "DELETE";
                target_table?: string;
                target_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListAuditOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-brackets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListBracketsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-bracket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateBracketInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBracketBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-bracket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-bracket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateBracketInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBracketBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateChallengeInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminChallengeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-reorder-challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReorderInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReorderOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateChallengeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminChallengeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-upload-file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description filename of the file being uploaded
                     */
                    filename?: string;
                    /** @description general purpose name for multipart form value */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFileBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-add-flag": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAddFlagInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFlagBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-flag": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                flagID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-flag": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                flagID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateFlagInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFlagBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-add-hint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminAddHintInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHintBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-hint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                hintID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-hint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                hintID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateHintInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHintBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-set-challenge-state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChallengeStateInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminChallengeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-get-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminConfigOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminConfigInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminConfigOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateNotificationInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListTagsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-tag": {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                value: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-merge-tag": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                value: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMergeTagInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-users": {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListUsersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-set-user-banned": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminBanInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBanOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-set-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRoleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoleOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
