// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminAddTag = `-- name: AdminAddTag :one

INSERT INTO tags (challenge_id, value)
VALUES ($1, $2)
RETURNING id, challenge_id, value
`

type AdminAddTagParams struct {
	ChallengeID int64
	Value       string
}

// ── tags ──────────────────────────────────────────────────────────────────────────
//
// A tag is a (challenge_id, value) row; the same value on many challenges is one tag with several
// uses. These statements treat a tag by its value, which is the unit an operator manages.
// No pre-checks: UNIQUE(challenge_id, value) refuses the duplicate and the FK refuses a missing
// challenge, each mapped by the caller. A pre-read would just be the same check with a race in it.
func (q *Queries) AdminAddTag(ctx context.Context, arg AdminAddTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, adminAddTag, arg.ChallengeID, arg.Value)
	var i Tag
	err := row.Scan(&i.ID, &i.ChallengeID, &i.Value)
	return i, err
}

const adminChallengeFlagStats = `-- name: AdminChallengeFlagStats :one
SELECT count(*)::bigint AS total,
       count(*) FILTER (WHERE type = 'regex')::bigint AS regex
  FROM flags WHERE challenge_id = $1
`

type AdminChallengeFlagStatsRow struct {
	Total int64
	Regex int64
}

// Flag counts for the flag_mode switch guards: total decides whether a switch to static would leave
// every submission erroring on an empty flag set, and the regex count decides whether a switch to
// unique would strand a pattern that cannot be pool-issued.
func (q *Queries) AdminChallengeFlagStats(ctx context.Context, challengeID int64) (AdminChallengeFlagStatsRow, error) {
	row := q.db.QueryRow(ctx, adminChallengeFlagStats, challengeID)
	var i AdminChallengeFlagStatsRow
	err := row.Scan(&i.Total, &i.Regex)
	return i, err
}

const adminCountChallengeSolves = `-- name: AdminCountChallengeSolves :one
SELECT count(*)::bigint FROM solves WHERE challenge_id = $1
`

// Whether the challenge has any recorded solve. A flag_mode switch is refused while this is nonzero:
// the anti-cheat unissued-solve detector is a date-blind anti-join, so flipping static→unique
// mid-event would report every legitimate prior solver as an unissued solve.
func (q *Queries) AdminCountChallengeSolves(ctx context.Context, challengeID int64) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountChallengeSolves, challengeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountOtherAdmins = `-- name: AdminCountOtherAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND banned = false AND id <> $1
`

func (q *Queries) AdminCountOtherAdmins(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOtherAdmins, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountTagUses = `-- name: AdminCountTagUses :one
SELECT count(*) FROM tags WHERE value = $1
`

func (q *Queries) AdminCountTagUses(ctx context.Context, value string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountTagUses, value)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreateChallenge = `-- name: AdminCreateChallenge :one


INSERT INTO challenges (
    name, category, description, attribution, connection_info,
    type, state, value, function, initial, minimum, decay,
    max_attempts, logic, position, first_blood, first_blood_bonus
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17
)
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminCreateChallengeParams struct {
	Name            string
	Category        string
	Description     string
	Attribution     *string
	ConnectionInfo  *string
	Type            string
	State           string
	Value           int32
	Function        string
	Initial         *int32
	Minimum         *int32
	Decay           *int32
	MaxAttempts     int32
	Logic           string
	Position        int32
	FirstBlood      string
	FirstBloodBonus *int32
}

// Admin mutations. Every statement here runs inside a transaction that has stamped the acting
// admin into app.actor_id, so the capture triggers write the audit row in the same transaction
// as the change itself.
// ── challenges ──────────────────────────────────────────────────────────────────
func (q *Queries) AdminCreateChallenge(ctx context.Context, arg AdminCreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminCreateChallenge,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Attribution,
		arg.ConnectionInfo,
		arg.Type,
		arg.State,
		arg.Value,
		arg.Function,
		arg.Initial,
		arg.Minimum,
		arg.Decay,
		arg.MaxAttempts,
		arg.Logic,
		arg.Position,
		arg.FirstBlood,
		arg.FirstBloodBonus,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminCreateTeam = `-- name: AdminCreateTeam :one
INSERT INTO teams (name, password_hash, email, website, affiliation, country)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, name, email, website, affiliation, country, bracket_id, captain_id,
          hidden, banned, created_at
`

type AdminCreateTeamParams struct {
	Name         string
	PasswordHash *string
	Email        *string
	Website      *string
	Affiliation  *string
	Country      *string
}

type AdminCreateTeamRow struct {
	ID          int64
	Name        string
	Email       *string
	Website     *string
	Affiliation *string
	Country     *string
	BracketID   *int64
	CaptainID   *int64
	Hidden      bool
	Banned      bool
	CreatedAt   pgtype.Timestamptz
}

// Same arbiters as the self-serve create: teams_name_uniq and the num_teams caps trigger decide
// on the INSERT itself, never in a prior check. captain_id stays NULL — an admin-provisioned team
// is captainless until its first member joins and adopts it.
func (q *Queries) AdminCreateTeam(ctx context.Context, arg AdminCreateTeamParams) (AdminCreateTeamRow, error) {
	row := q.db.QueryRow(ctx, adminCreateTeam,
		arg.Name,
		arg.PasswordHash,
		arg.Email,
		arg.Website,
		arg.Affiliation,
		arg.Country,
	)
	var i AdminCreateTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.BracketID,
		&i.CaptainID,
		&i.Hidden,
		&i.Banned,
		&i.CreatedAt,
	)
	return i, err
}

const adminDeleteChallenge = `-- name: AdminDeleteChallenge :execrows
DELETE FROM challenges WHERE id = $1
`

// Flags, hints, tags and file links cascade. Ledger rows (solves, submissions, awards, hint
// unlocks, issued flags) RESTRICT: a challenge with recorded history cannot be deleted, and the
// caller maps that violation to a conflict.
func (q *Queries) AdminDeleteChallenge(ctx context.Context, challengeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteChallenge, challengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteFlag = `-- name: AdminDeleteFlag :execrows
DELETE FROM flags WHERE id = $1 AND challenge_id = $2
`

type AdminDeleteFlagParams struct {
	FlagID      int64
	ChallengeID int64
}

func (q *Queries) AdminDeleteFlag(ctx context.Context, arg AdminDeleteFlagParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteFlag, arg.FlagID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteHint = `-- name: AdminDeleteHint :execrows
DELETE FROM hints WHERE id = $1 AND challenge_id = $2
`

type AdminDeleteHintParams struct {
	HintID      int64
	ChallengeID int64
}

func (q *Queries) AdminDeleteHint(ctx context.Context, arg AdminDeleteHintParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteHint, arg.HintID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteTag = `-- name: AdminDeleteTag :execrows
DELETE FROM tags WHERE value = $1
`

func (q *Queries) AdminDeleteTag(ctx context.Context, value string) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteTag, value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminFilterChallengeFileIDs = `-- name: AdminFilterChallengeFileIDs :many
SELECT id FROM files WHERE id = ANY($1::bigint[]) AND challenge_id = $2
`

type AdminFilterChallengeFileIDsParams struct {
	Ids         []int64
	ChallengeID *int64
}

// Existence probe for artifact validation, scoped to the challenge: an artifact_id that is not a
// file of this challenge filters out here, and the caller names it as invalid.
func (q *Queries) AdminFilterChallengeFileIDs(ctx context.Context, arg AdminFilterChallengeFileIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, adminFilterChallengeFileIDs, arg.Ids, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminFilterChallengeIDs = `-- name: AdminFilterChallengeIDs :many
SELECT id FROM challenges WHERE id = ANY($1::bigint[])
`

// Existence probe for prerequisite validation: the caller diffs the echo against its input to name
// the ids that do not exist.
func (q *Queries) AdminFilterChallengeIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, adminFilterChallengeIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminFilterHintIDs = `-- name: AdminFilterHintIDs :many
SELECT id FROM hints WHERE id = ANY($1::bigint[]) AND challenge_id = $2
`

type AdminFilterHintIDsParams struct {
	Ids         []int64
	ChallengeID int64
}

// Existence probe for hint-prerequisite validation, scoped to the challenge: a cross-challenge id
// filters out here and is reported by the caller the same as one that does not exist at all.
func (q *Queries) AdminFilterHintIDs(ctx context.Context, arg AdminFilterHintIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, adminFilterHintIDs, arg.Ids, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminForcePasswordChange = `-- name: AdminForcePasswordChange :one
UPDATE users SET must_change_password = true WHERE id = $1
RETURNING id, name, must_change_password
`

type AdminForcePasswordChangeRow struct {
	ID                 int64
	Name               string
	MustChangePassword bool
}

// Set-only: the clear belongs to the password change itself, in the same statement as the new
// hash, so the order can never discharge without the password that satisfies it.
func (q *Queries) AdminForcePasswordChange(ctx context.Context, userID int64) (AdminForcePasswordChangeRow, error) {
	row := q.db.QueryRow(ctx, adminForcePasswordChange, userID)
	var i AdminForcePasswordChangeRow
	err := row.Scan(&i.ID, &i.Name, &i.MustChangePassword)
	return i, err
}

const adminGetChallenge = `-- name: AdminGetChallenge :one
SELECT id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at FROM challenges WHERE id = $1
`

func (q *Queries) AdminGetChallenge(ctx context.Context, challengeID int64) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminGetChallenge, challengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetFlag = `-- name: AdminGetFlag :one
SELECT id, challenge_id, type, content, case_insensitive FROM flags WHERE id = $1 AND challenge_id = $2
`

type AdminGetFlagParams struct {
	FlagID      int64
	ChallengeID int64
}

func (q *Queries) AdminGetFlag(ctx context.Context, arg AdminGetFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminGetFlag, arg.FlagID, arg.ChallengeID)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminGetTeam = `-- name: AdminGetTeam :one
SELECT t.id, t.name, t.email, t.website, t.affiliation, t.country,
       t.bracket_id, t.captain_id, t.hidden, t.banned, t.created_at,
       (SELECT count(*) FROM users u WHERE u.team_id = t.id)::bigint AS member_count
  FROM teams t
 WHERE t.id = $1
`

type AdminGetTeamRow struct {
	ID          int64
	Name        string
	Email       *string
	Website     *string
	Affiliation *string
	Country     *string
	BracketID   *int64
	CaptainID   *int64
	Hidden      bool
	Banned      bool
	CreatedAt   pgtype.Timestamptz
	MemberCount int64
}

func (q *Queries) AdminGetTeam(ctx context.Context, teamID int64) (AdminGetTeamRow, error) {
	row := q.db.QueryRow(ctx, adminGetTeam, teamID)
	var i AdminGetTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.BracketID,
		&i.CaptainID,
		&i.Hidden,
		&i.Banned,
		&i.CreatedAt,
		&i.MemberCount,
	)
	return i, err
}

const adminGetUser = `-- name: AdminGetUser :one
SELECT id, name, email, role, verified, banned, hidden, team_id, bracket_id,
       website, affiliation, country, must_change_password, created_at
  FROM users
 WHERE id = $1
`

type AdminGetUserRow struct {
	ID                 int64
	Name               string
	Email              string
	Role               string
	Verified           bool
	Banned             bool
	Hidden             bool
	TeamID             *int64
	BracketID          *int64
	Website            *string
	Affiliation        *string
	Country            *string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) AdminGetUser(ctx context.Context, userID int64) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, userID)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Verified,
		&i.Banned,
		&i.Hidden,
		&i.TeamID,
		&i.BracketID,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const adminInsertFlag = `-- name: AdminInsertFlag :one

INSERT INTO flags (challenge_id, type, content, case_insensitive)
VALUES ($1, $2, $3, $4)
RETURNING id, challenge_id, type, content, case_insensitive
`

type AdminInsertFlagParams struct {
	ChallengeID     int64
	Type            string
	Content         string
	CaseInsensitive bool
}

// ── flags ───────────────────────────────────────────────────────────────────────
func (q *Queries) AdminInsertFlag(ctx context.Context, arg AdminInsertFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminInsertFlag,
		arg.ChallengeID,
		arg.Type,
		arg.Content,
		arg.CaseInsensitive,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminInsertHint = `-- name: AdminInsertHint :one

INSERT INTO hints (challenge_id, title, content, cost, position, requirements)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
RETURNING id, challenge_id, title, content, cost, requirements, position
`

type AdminInsertHintParams struct {
	ChallengeID  int64
	Title        *string
	Content      string
	Cost         int32
	Position     int32
	Requirements json.RawMessage
}

// ── hints ───────────────────────────────────────────────────────────────────────
func (q *Queries) AdminInsertHint(ctx context.Context, arg AdminInsertHintParams) (Hint, error) {
	row := q.db.QueryRow(ctx, adminInsertHint,
		arg.ChallengeID,
		arg.Title,
		arg.Content,
		arg.Cost,
		arg.Position,
		arg.Requirements,
	)
	var i Hint
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Content,
		&i.Cost,
		&i.Requirements,
		&i.Position,
	)
	return i, err
}

const adminInsertInstances = `-- name: AdminInsertInstances :execrows
INSERT INTO challenge_instances (challenge_id, value_hash, artifact_id, vars, generation)
SELECT $1,
       v.value_hash,
       nullif(v.artifact_id, 0),
       v.vars,
       $2
FROM (
    SELECT unnest($3::bytea[])  AS value_hash,
           unnest($4::bigint[]) AS artifact_id,
           unnest($5::jsonb[])          AS vars
) v
`

type AdminInsertInstancesParams struct {
	ChallengeID int64
	Generation  int32
	ValueHashes [][]byte
	ArtifactIds []int64
	Vars        []json.RawMessage
}

// One statement, one transaction: the whole batch lands or none of it does. An in-batch duplicate,
// or a collision with an existing generation's hash, trips UNIQUE(challenge_id, value_hash,
// generation) and rolls the entire upload back — the friendly duplicate pre-check in Go only buys a
// nicer message; this is the guarantee. A zero artifact_id means "no artifact": file ids are
// bigserial and never 0, so it is a safe stand-in for the SQL NULL a bigint[] element cannot carry.
func (q *Queries) AdminInsertInstances(ctx context.Context, arg AdminInsertInstancesParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminInsertInstances,
		arg.ChallengeID,
		arg.Generation,
		arg.ValueHashes,
		arg.ArtifactIds,
		arg.Vars,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminListAudit = `-- name: AdminListAudit :many

SELECT id, actor_id, action, target_table, target_id, before, after, at, ip,
       COUNT(*) OVER () AS total
  FROM audit_log
 WHERE ($1::bigint IS NULL OR actor_id = $1)
   AND ($2::text IS NULL OR action = $2)
   AND ($3::text IS NULL OR target_table = $3)
   AND ($4::bigint IS NULL OR target_id = $4)
 ORDER BY at DESC, id DESC
 LIMIT $6::int OFFSET $5::int
`

type AdminListAuditParams struct {
	ActorID     *int64
	Action      *string
	TargetTable *string
	TargetID    *int64
	Off         int32
	Lim         int32
}

type AdminListAuditRow struct {
	ID          int64
	ActorID     *int64
	Action      string
	TargetTable string
	TargetID    *int64
	Before      json.RawMessage
	After       json.RawMessage
	At          pgtype.Timestamptz
	Ip          *netip.Addr
	Total       int64
}

// ── audit trail ───────────────────────────────────────────────────────────────────
// Read-only feed over the capture triggers' output, newest first. Each filter is optional and
// narrows independently; an unset one drops out of the WHERE rather than matching a sentinel. The
// (at, id) tiebreak keeps the order total when many rows share a timestamp, so pages never overlap.
// COUNT(*) OVER () rides along so the page and its total agree in one round trip.
func (q *Queries) AdminListAudit(ctx context.Context, arg AdminListAuditParams) ([]AdminListAuditRow, error) {
	rows, err := q.db.Query(ctx, adminListAudit,
		arg.ActorID,
		arg.Action,
		arg.TargetTable,
		arg.TargetID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditRow{}
	for rows.Next() {
		var i AdminListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetTable,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.At,
			&i.Ip,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChallengeRequirements = `-- name: AdminListChallengeRequirements :many
SELECT id, requirements FROM challenges
`

type AdminListChallengeRequirementsRow struct {
	ID           int64
	Requirements json.RawMessage
}

// The whole prerequisite graph, for the cycle warning on requirement writes. Boards are small; one
// read beats a traversal query nothing else needs.
func (q *Queries) AdminListChallengeRequirements(ctx context.Context) ([]AdminListChallengeRequirementsRow, error) {
	rows, err := q.db.Query(ctx, adminListChallengeRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListChallengeRequirementsRow{}
	for rows.Next() {
		var i AdminListChallengeRequirementsRow
		if err := rows.Scan(&i.ID, &i.Requirements); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListInstances = `-- name: AdminListInstances :many
SELECT ci.id, ci.value_hash, ci.artifact_id, ci.vars, ci.generation,
       fi.account_id AS issued_to, fi.assigned_at,
       COUNT(*) OVER () AS total
  FROM challenge_instances ci
  LEFT JOIN flag_issues fi ON fi.instance_id = ci.id
 WHERE ci.challenge_id = $1
 ORDER BY ci.generation DESC, ci.id
 LIMIT $3::int OFFSET $2::int
`

type AdminListInstancesParams struct {
	ChallengeID int64
	Off         int32
	Lim         int32
}

type AdminListInstancesRow struct {
	ID         int64
	ValueHash  []byte
	ArtifactID *int64
	Vars       json.RawMessage
	Generation int32
	IssuedTo   *int64
	AssignedAt pgtype.Timestamptz
	Total      int64
}

// The pool of one challenge, newest generation first, each row carrying who it was issued to (a NULL
// issued_to is a still-free instance). COUNT(*) OVER () rides along so the page and its total agree.
func (q *Queries) AdminListInstances(ctx context.Context, arg AdminListInstancesParams) ([]AdminListInstancesRow, error) {
	rows, err := q.db.Query(ctx, adminListInstances, arg.ChallengeID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListInstancesRow{}
	for rows.Next() {
		var i AdminListInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.ValueHash,
			&i.ArtifactID,
			&i.Vars,
			&i.Generation,
			&i.IssuedTo,
			&i.AssignedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTags = `-- name: AdminListTags :many
SELECT value, count(*) AS uses
  FROM tags
 GROUP BY value
 ORDER BY value
`

type AdminListTagsRow struct {
	Value string
	Uses  int64
}

func (q *Queries) AdminListTags(ctx context.Context) ([]AdminListTagsRow, error) {
	rows, err := q.db.Query(ctx, adminListTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTagsRow{}
	for rows.Next() {
		var i AdminListTagsRow
		if err := rows.Scan(&i.Value, &i.Uses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTeams = `-- name: AdminListTeams :many

SELECT t.id, t.name, t.email, t.website, t.affiliation, t.country,
       t.bracket_id, t.captain_id, t.hidden, t.banned, t.created_at,
       (SELECT count(*) FROM users u WHERE u.team_id = t.id)::bigint AS member_count,
       COUNT(*) OVER () AS total
  FROM teams t
 WHERE ($1::text IS NULL OR CASE $2::text
            WHEN 'email'       THEN t.email       ILIKE '%' || $1 || '%'
            WHEN 'website'     THEN t.website     ILIKE '%' || $1 || '%'
            WHEN 'affiliation' THEN t.affiliation ILIKE '%' || $1 || '%'
            WHEN 'country'     THEN t.country     ILIKE '%' || $1 || '%'
            ELSE t.name ILIKE '%' || $1 || '%'
        END)
 ORDER BY t.id
 LIMIT $4::int OFFSET $3::int
`

type AdminListTeamsParams struct {
	Q     *string
	Field *string
	Off   int32
	Lim   int32
}

type AdminListTeamsRow struct {
	ID          int64
	Name        string
	Email       *string
	Website     *string
	Affiliation *string
	Country     *string
	BracketID   *int64
	CaptainID   *int64
	Hidden      bool
	Banned      bool
	CreatedAt   pgtype.Timestamptz
	MemberCount int64
	Total       int64
}

// ── teams ───────────────────────────────────────────────────────────────────────
// COUNT(*) OVER () carries the total in the same round trip, like AdminListUsers. The search is
// one optional (q, field) pair; an unset q drops the filter entirely, and an unknown field falls
// back to the name so the CASE can never silently match nothing.
func (q *Queries) AdminListTeams(ctx context.Context, arg AdminListTeamsParams) ([]AdminListTeamsRow, error) {
	rows, err := q.db.Query(ctx, adminListTeams,
		arg.Q,
		arg.Field,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTeamsRow{}
	for rows.Next() {
		var i AdminListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Website,
			&i.Affiliation,
			&i.Country,
			&i.BracketID,
			&i.CaptainID,
			&i.Hidden,
			&i.Banned,
			&i.CreatedAt,
			&i.MemberCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT id, name, email, role, verified, banned, hidden, team_id,
       website, affiliation, country, must_change_password, created_at,
       COUNT(*) OVER () AS total
  FROM users
 WHERE ($1::text IS NULL OR CASE $2::text
            WHEN 'email'       THEN email       ILIKE '%' || $1 || '%'
            WHEN 'website'     THEN website     ILIKE '%' || $1 || '%'
            WHEN 'affiliation' THEN affiliation ILIKE '%' || $1 || '%'
            WHEN 'country'     THEN country     ILIKE '%' || $1 || '%'
            ELSE name ILIKE '%' || $1 || '%'
        END)
 ORDER BY id
 LIMIT $4::int OFFSET $3::int
`

type AdminListUsersParams struct {
	Q     *string
	Field *string
	Off   int32
	Lim   int32
}

type AdminListUsersRow struct {
	ID                 int64
	Name               string
	Email              string
	Role               string
	Verified           bool
	Banned             bool
	Hidden             bool
	TeamID             *int64
	Website            *string
	Affiliation        *string
	Country            *string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	Total              int64
}

// ── users ───────────────────────────────────────────────────────────────────────
// COUNT(*) OVER () carries the total in the same round trip, so the pagination header never
// disagrees with the page it describes. The (q, field) search mirrors the team list; email is
// searchable here and nowhere public.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Q,
		arg.Field,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Verified,
			&i.Banned,
			&i.Hidden,
			&i.TeamID,
			&i.Website,
			&i.Affiliation,
			&i.Country,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMergeTagCollisions = `-- name: AdminMergeTagCollisions :execrows
DELETE FROM tags t
 WHERE t.value = $1
   AND EXISTS (SELECT 1 FROM tags o WHERE o.challenge_id = t.challenge_id AND o.value = $2)
`

type AdminMergeTagCollisionsParams struct {
	FromValue string
	ToValue   string
}

// Drop the source rows on challenges that already carry the destination, so the rename that follows
// cannot trip UNIQUE(challenge_id, value). These deletions are real merges and are audited as such.
func (q *Queries) AdminMergeTagCollisions(ctx context.Context, arg AdminMergeTagCollisionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminMergeTagCollisions, arg.FromValue, arg.ToValue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminNewestPoolHashes = `-- name: AdminNewestPoolHashes :many
SELECT ci.value_hash
  FROM challenge_instances ci
 WHERE ci.challenge_id = $1
   AND ci.generation = (SELECT MAX(g.generation) FROM challenge_instances g WHERE g.challenge_id = $1)
`

// The value_hash set of the newest generation, for the idempotent-push check: an upload whose hash
// set equals this one is a no-op and returns the existing generation unchanged.
func (q *Queries) AdminNewestPoolHashes(ctx context.Context, challengeID int64) ([][]byte, error) {
	rows, err := q.db.Query(ctx, adminNewestPoolHashes, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var value_hash []byte
		if err := rows.Scan(&value_hash); err != nil {
			return nil, err
		}
		items = append(items, value_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminNextPoolGeneration = `-- name: AdminNextPoolGeneration :one

SELECT COALESCE(MAX(generation), 0) + 1 AS generation FROM challenge_instances WHERE challenge_id = $1
`

// ── challenge instances (the unique-flag pool) ────────────────────────────────────
//
// The pool write path. The client uploads value_hash = sha256(flag) — never the plaintext, which
// the platform is designed never to hold — plus an optional per-account artifact and vars. A
// re-upload lands in a new generation so new issues come from the new set while existing flag_issues
// stay attributable to the instances they were assigned from.
// The generation a fresh upload lands in: one past the highest present, or 1 for an empty pool.
func (q *Queries) AdminNextPoolGeneration(ctx context.Context, challengeID int64) (int32, error) {
	row := q.db.QueryRow(ctx, adminNextPoolGeneration, challengeID)
	var generation int32
	err := row.Scan(&generation)
	return generation, err
}

const adminRemoveTag = `-- name: AdminRemoveTag :execrows
DELETE FROM tags WHERE challenge_id = $1 AND value = $2
`

type AdminRemoveTagParams struct {
	ChallengeID int64
	Value       string
}

func (q *Queries) AdminRemoveTag(ctx context.Context, arg AdminRemoveTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminRemoveTag, arg.ChallengeID, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminRenameTag = `-- name: AdminRenameTag :execrows
UPDATE tags SET value = $1 WHERE value = $2
`

type AdminRenameTagParams struct {
	ToValue   string
	FromValue string
}

func (q *Queries) AdminRenameTag(ctx context.Context, arg AdminRenameTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminRenameTag, arg.ToValue, arg.FromValue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminReorderChallenges = `-- name: AdminReorderChallenges :execrows
UPDATE challenges c SET position = v.position, updated_at = now()
FROM (
    SELECT unnest($1::bigint[]) AS id,
           unnest($2::int[]) AS position
) v
WHERE c.id = v.id
`

type AdminReorderChallengesParams struct {
	Ids       []int64
	Positions []int32
}

// Bulk position assignment in one statement: the two arrays are zipped by ordinality, so every
// challenge moves or none does. A row count below the input length means an id did not exist.
func (q *Queries) AdminReorderChallenges(ctx context.Context, arg AdminReorderChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminReorderChallenges, arg.Ids, arg.Positions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSetChallengeFlagMode = `-- name: AdminSetChallengeFlagMode :one
UPDATE challenges SET flag_mode = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminSetChallengeFlagModeParams struct {
	FlagMode    string
	ChallengeID int64
}

// The one write path for challenges.flag_mode outside the importer. The switch guards live in the
// service, in the same transaction as this update: a mid-event switch would misfire the
// unissued-solve detector, so the service refuses it while any solve exists.
func (q *Queries) AdminSetChallengeFlagMode(ctx context.Context, arg AdminSetChallengeFlagModeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminSetChallengeFlagMode, arg.FlagMode, arg.ChallengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetChallengeRequirements = `-- name: AdminSetChallengeRequirements :one
UPDATE challenges SET requirements = $1::jsonb, updated_at = now()
WHERE id = $2
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminSetChallengeRequirementsParams struct {
	Requirements json.RawMessage
	ChallengeID  int64
}

// Whole-value replace: the column is one document, so a partial patch has no meaning here.
func (q *Queries) AdminSetChallengeRequirements(ctx context.Context, arg AdminSetChallengeRequirementsParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminSetChallengeRequirements, arg.Requirements, arg.ChallengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetChallengeState = `-- name: AdminSetChallengeState :one
UPDATE challenges SET state = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminSetChallengeStateParams struct {
	State       string
	ChallengeID int64
}

func (q *Queries) AdminSetChallengeState(ctx context.Context, arg AdminSetChallengeStateParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminSetChallengeState, arg.State, arg.ChallengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetTeamBanned = `-- name: AdminSetTeamBanned :one
UPDATE teams SET banned = $1 WHERE id = $2
RETURNING id, name, banned
`

type AdminSetTeamBannedParams struct {
	Banned bool
	TeamID int64
}

type AdminSetTeamBannedRow struct {
	ID     int64
	Name   string
	Banned bool
}

func (q *Queries) AdminSetTeamBanned(ctx context.Context, arg AdminSetTeamBannedParams) (AdminSetTeamBannedRow, error) {
	row := q.db.QueryRow(ctx, adminSetTeamBanned, arg.Banned, arg.TeamID)
	var i AdminSetTeamBannedRow
	err := row.Scan(&i.ID, &i.Name, &i.Banned)
	return i, err
}

const adminSetTeamHidden = `-- name: AdminSetTeamHidden :one
UPDATE teams SET hidden = $1 WHERE id = $2
RETURNING id, name, hidden
`

type AdminSetTeamHiddenParams struct {
	Hidden bool
	TeamID int64
}

type AdminSetTeamHiddenRow struct {
	ID     int64
	Name   string
	Hidden bool
}

func (q *Queries) AdminSetTeamHidden(ctx context.Context, arg AdminSetTeamHiddenParams) (AdminSetTeamHiddenRow, error) {
	row := q.db.QueryRow(ctx, adminSetTeamHidden, arg.Hidden, arg.TeamID)
	var i AdminSetTeamHiddenRow
	err := row.Scan(&i.ID, &i.Name, &i.Hidden)
	return i, err
}

const adminSetUserBanned = `-- name: AdminSetUserBanned :one
UPDATE users SET banned = $1 WHERE id = $2
RETURNING id, name, banned
`

type AdminSetUserBannedParams struct {
	Banned bool
	UserID int64
}

type AdminSetUserBannedRow struct {
	ID     int64
	Name   string
	Banned bool
}

func (q *Queries) AdminSetUserBanned(ctx context.Context, arg AdminSetUserBannedParams) (AdminSetUserBannedRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserBanned, arg.Banned, arg.UserID)
	var i AdminSetUserBannedRow
	err := row.Scan(&i.ID, &i.Name, &i.Banned)
	return i, err
}

const adminSetUserHidden = `-- name: AdminSetUserHidden :one
UPDATE users SET hidden = $1 WHERE id = $2
RETURNING id, name, hidden
`

type AdminSetUserHiddenParams struct {
	Hidden bool
	UserID int64
}

type AdminSetUserHiddenRow struct {
	ID     int64
	Name   string
	Hidden bool
}

func (q *Queries) AdminSetUserHidden(ctx context.Context, arg AdminSetUserHiddenParams) (AdminSetUserHiddenRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserHidden, arg.Hidden, arg.UserID)
	var i AdminSetUserHiddenRow
	err := row.Scan(&i.ID, &i.Name, &i.Hidden)
	return i, err
}

const adminSetUserRole = `-- name: AdminSetUserRole :one
UPDATE users SET role = $1 WHERE id = $2
RETURNING id, name, role
`

type AdminSetUserRoleParams struct {
	Role   string
	UserID int64
}

type AdminSetUserRoleRow struct {
	ID   int64
	Name string
	Role string
}

func (q *Queries) AdminSetUserRole(ctx context.Context, arg AdminSetUserRoleParams) (AdminSetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserRole, arg.Role, arg.UserID)
	var i AdminSetUserRoleRow
	err := row.Scan(&i.ID, &i.Name, &i.Role)
	return i, err
}

const adminUpdateChallenge = `-- name: AdminUpdateChallenge :one
UPDATE challenges SET
    name            = COALESCE($1, name),
    category        = COALESCE($2, category),
    description     = COALESCE($3, description),
    attribution     = CASE WHEN $4::bool THEN NULL
                           ELSE COALESCE($5, attribution) END,
    connection_info = CASE WHEN $6::bool THEN NULL
                           ELSE COALESCE($7, connection_info) END,
    type            = COALESCE($8, type),
    value           = COALESCE($9, value),
    function        = COALESCE($10, function),
    initial         = CASE WHEN $11::bool THEN NULL
                           ELSE COALESCE($12, initial) END,
    minimum         = CASE WHEN $13::bool THEN NULL
                           ELSE COALESCE($14, minimum) END,
    decay           = CASE WHEN $15::bool THEN NULL
                           ELSE COALESCE($16, decay) END,
    max_attempts    = COALESCE($17, max_attempts),
    logic           = COALESCE($18, logic),
    position        = COALESCE($19, position),
    first_blood     = COALESCE($20, first_blood),
    first_blood_bonus = CASE WHEN $21::bool THEN NULL
                             ELSE COALESCE($22, first_blood_bonus) END,
    next_id         = CASE WHEN $23::bool THEN NULL
                           ELSE COALESCE($24, next_id) END,
    updated_at      = now()
WHERE id = $25
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminUpdateChallengeParams struct {
	Name                 *string
	Category             *string
	Description          *string
	ClearAttribution     bool
	Attribution          *string
	ClearConnectionInfo  bool
	ConnectionInfo       *string
	Type                 *string
	Value                *int32
	Function             *string
	ClearInitial         bool
	Initial              *int32
	ClearMinimum         bool
	Minimum              *int32
	ClearDecay           bool
	Decay                *int32
	MaxAttempts          *int32
	Logic                *string
	Position             *int32
	FirstBlood           *string
	ClearFirstBloodBonus bool
	FirstBloodBonus      *int32
	ClearNextID          bool
	NextID               *int64
	ChallengeID          int64
}

// Partial update with a third state for the nullable columns: an absent field keeps its value, a
// clear flag nulls it, and a supplied value sets it. The three are exclusive per column — the
// transport turns an omitted key into neither, an explicit null into the clear, and a value into
// the narg. The dynamic-params CHECK still arbitrates the result, so clearing initial on a decayed
// challenge is refused, not silently stored.
func (q *Queries) AdminUpdateChallenge(ctx context.Context, arg AdminUpdateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminUpdateChallenge,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.ClearAttribution,
		arg.Attribution,
		arg.ClearConnectionInfo,
		arg.ConnectionInfo,
		arg.Type,
		arg.Value,
		arg.Function,
		arg.ClearInitial,
		arg.Initial,
		arg.ClearMinimum,
		arg.Minimum,
		arg.ClearDecay,
		arg.Decay,
		arg.MaxAttempts,
		arg.Logic,
		arg.Position,
		arg.FirstBlood,
		arg.ClearFirstBloodBonus,
		arg.FirstBloodBonus,
		arg.ClearNextID,
		arg.NextID,
		arg.ChallengeID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateFlag = `-- name: AdminUpdateFlag :one
UPDATE flags SET
    type             = COALESCE($1, type),
    content          = COALESCE($2, content),
    case_insensitive = COALESCE($3, case_insensitive)
WHERE id = $4 AND challenge_id = $5
RETURNING id, challenge_id, type, content, case_insensitive
`

type AdminUpdateFlagParams struct {
	Type            *string
	Content         *string
	CaseInsensitive *bool
	FlagID          int64
	ChallengeID     int64
}

// Scoped by challenge_id in the WHERE, not checked in Go: a flag id from another challenge's URL
// affects zero rows, so there is no window and no forgotten guard.
func (q *Queries) AdminUpdateFlag(ctx context.Context, arg AdminUpdateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminUpdateFlag,
		arg.Type,
		arg.Content,
		arg.CaseInsensitive,
		arg.FlagID,
		arg.ChallengeID,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminUpdateHint = `-- name: AdminUpdateHint :one
UPDATE hints SET
    title        = COALESCE($1, title),
    content      = COALESCE($2, content),
    cost         = COALESCE($3, cost),
    position     = COALESCE($4, position),
    requirements = COALESCE($5::jsonb, requirements)
WHERE id = $6 AND challenge_id = $7
RETURNING id, challenge_id, title, content, cost, requirements, position
`

type AdminUpdateHintParams struct {
	Title        *string
	Content      *string
	Cost         *int32
	Position     *int32
	Requirements json.RawMessage
	HintID       int64
	ChallengeID  int64
}

func (q *Queries) AdminUpdateHint(ctx context.Context, arg AdminUpdateHintParams) (Hint, error) {
	row := q.db.QueryRow(ctx, adminUpdateHint,
		arg.Title,
		arg.Content,
		arg.Cost,
		arg.Position,
		arg.Requirements,
		arg.HintID,
		arg.ChallengeID,
	)
	var i Hint
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Content,
		&i.Cost,
		&i.Requirements,
		&i.Position,
	)
	return i, err
}

const adminUpdateTeam = `-- name: AdminUpdateTeam :one
UPDATE teams SET
    name        = COALESCE($1, name),
    email       = CASE WHEN $2::bool THEN NULL
                       ELSE COALESCE($3, email) END,
    website     = CASE WHEN $4::bool THEN NULL
                       ELSE COALESCE($5, website) END,
    affiliation = CASE WHEN $6::bool THEN NULL
                       ELSE COALESCE($7, affiliation) END,
    country     = CASE WHEN $8::bool THEN NULL
                       ELSE COALESCE($9, country) END
WHERE id = $10
RETURNING id, name, email, website, affiliation, country, bracket_id, captain_id,
          hidden, banned, created_at
`

type AdminUpdateTeamParams struct {
	Name             *string
	ClearEmail       bool
	Email            *string
	ClearWebsite     bool
	Website          *string
	ClearAffiliation bool
	Affiliation      *string
	ClearCountry     bool
	Country          *string
	TeamID           int64
}

type AdminUpdateTeamRow struct {
	ID          int64
	Name        string
	Email       *string
	Website     *string
	Affiliation *string
	Country     *string
	BracketID   *int64
	CaptainID   *int64
	Hidden      bool
	Banned      bool
	CreatedAt   pgtype.Timestamptz
}

// Deliberately narrow SET: banned, hidden, captain_id, password_hash and membership are not
// reachable from this statement — they move through their own routes or not at all.
func (q *Queries) AdminUpdateTeam(ctx context.Context, arg AdminUpdateTeamParams) (AdminUpdateTeamRow, error) {
	row := q.db.QueryRow(ctx, adminUpdateTeam,
		arg.Name,
		arg.ClearEmail,
		arg.Email,
		arg.ClearWebsite,
		arg.Website,
		arg.ClearAffiliation,
		arg.Affiliation,
		arg.ClearCountry,
		arg.Country,
		arg.TeamID,
	)
	var i AdminUpdateTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.BracketID,
		&i.CaptainID,
		&i.Hidden,
		&i.Banned,
		&i.CreatedAt,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users SET
    name        = COALESCE($1, name),
    website     = CASE WHEN $2::bool THEN NULL
                       ELSE COALESCE($3, website) END,
    affiliation = CASE WHEN $4::bool THEN NULL
                       ELSE COALESCE($5, affiliation) END,
    country     = CASE WHEN $6::bool THEN NULL
                       ELSE COALESCE($7, country) END
WHERE id = $8
RETURNING id, name, email, role, verified, banned, hidden, team_id, bracket_id,
          website, affiliation, country, must_change_password, created_at
`

type AdminUpdateUserParams struct {
	Name             *string
	ClearWebsite     bool
	Website          *string
	ClearAffiliation bool
	Affiliation      *string
	ClearCountry     bool
	Country          *string
	UserID           int64
}

type AdminUpdateUserRow struct {
	ID                 int64
	Name               string
	Email              string
	Role               string
	Verified           bool
	Banned             bool
	Hidden             bool
	TeamID             *int64
	BracketID          *int64
	Website            *string
	Affiliation        *string
	Country            *string
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
}

// Deliberately narrow SET: email, role, banned, hidden, team_id and must_change_password are not
// reachable from this statement — each moves through its own route or not at all.
func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (AdminUpdateUserRow, error) {
	row := q.db.QueryRow(ctx, adminUpdateUser,
		arg.Name,
		arg.ClearWebsite,
		arg.Website,
		arg.ClearAffiliation,
		arg.Affiliation,
		arg.ClearCountry,
		arg.Country,
		arg.UserID,
	)
	var i AdminUpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Verified,
		&i.Banned,
		&i.Hidden,
		&i.TeamID,
		&i.BracketID,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}
