// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountOtherAdmins = `-- name: AdminCountOtherAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND banned = false AND id <> $1
`

func (q *Queries) AdminCountOtherAdmins(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOtherAdmins, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountTagUses = `-- name: AdminCountTagUses :one
SELECT count(*) FROM tags WHERE value = $1
`

func (q *Queries) AdminCountTagUses(ctx context.Context, value string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountTagUses, value)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreateChallenge = `-- name: AdminCreateChallenge :one


INSERT INTO challenges (
    name, category, description, attribution, connection_info,
    type, state, value, function, initial, minimum, decay,
    max_attempts, logic, position, first_blood, first_blood_bonus
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17
)
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminCreateChallengeParams struct {
	Name            string
	Category        string
	Description     string
	Attribution     *string
	ConnectionInfo  *string
	Type            string
	State           string
	Value           int32
	Function        string
	Initial         *int32
	Minimum         *int32
	Decay           *int32
	MaxAttempts     int32
	Logic           string
	Position        int32
	FirstBlood      string
	FirstBloodBonus *int32
}

// Admin mutations. Every statement here runs inside a transaction that has stamped the acting
// admin into app.actor_id, so the capture triggers write the audit row in the same transaction
// as the change itself.
// ── challenges ──────────────────────────────────────────────────────────────────
func (q *Queries) AdminCreateChallenge(ctx context.Context, arg AdminCreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminCreateChallenge,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Attribution,
		arg.ConnectionInfo,
		arg.Type,
		arg.State,
		arg.Value,
		arg.Function,
		arg.Initial,
		arg.Minimum,
		arg.Decay,
		arg.MaxAttempts,
		arg.Logic,
		arg.Position,
		arg.FirstBlood,
		arg.FirstBloodBonus,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeleteChallenge = `-- name: AdminDeleteChallenge :execrows
DELETE FROM challenges WHERE id = $1
`

// Flags, hints, tags and file links cascade. Ledger rows (solves, submissions, awards, hint
// unlocks, issued flags) RESTRICT: a challenge with recorded history cannot be deleted, and the
// caller maps that violation to a conflict.
func (q *Queries) AdminDeleteChallenge(ctx context.Context, challengeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteChallenge, challengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteFlag = `-- name: AdminDeleteFlag :execrows
DELETE FROM flags WHERE id = $1 AND challenge_id = $2
`

type AdminDeleteFlagParams struct {
	FlagID      int64
	ChallengeID int64
}

func (q *Queries) AdminDeleteFlag(ctx context.Context, arg AdminDeleteFlagParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteFlag, arg.FlagID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteHint = `-- name: AdminDeleteHint :execrows
DELETE FROM hints WHERE id = $1 AND challenge_id = $2
`

type AdminDeleteHintParams struct {
	HintID      int64
	ChallengeID int64
}

func (q *Queries) AdminDeleteHint(ctx context.Context, arg AdminDeleteHintParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteHint, arg.HintID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminDeleteTag = `-- name: AdminDeleteTag :execrows
DELETE FROM tags WHERE value = $1
`

func (q *Queries) AdminDeleteTag(ctx context.Context, value string) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteTag, value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminFilterChallengeIDs = `-- name: AdminFilterChallengeIDs :many
SELECT id FROM challenges WHERE id = ANY($1::bigint[])
`

// Existence probe for prerequisite validation: the caller diffs the echo against its input to name
// the ids that do not exist.
func (q *Queries) AdminFilterChallengeIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, adminFilterChallengeIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetChallenge = `-- name: AdminGetChallenge :one
SELECT id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at FROM challenges WHERE id = $1
`

func (q *Queries) AdminGetChallenge(ctx context.Context, challengeID int64) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminGetChallenge, challengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetFlag = `-- name: AdminGetFlag :one
SELECT id, challenge_id, type, content, case_insensitive FROM flags WHERE id = $1 AND challenge_id = $2
`

type AdminGetFlagParams struct {
	FlagID      int64
	ChallengeID int64
}

func (q *Queries) AdminGetFlag(ctx context.Context, arg AdminGetFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminGetFlag, arg.FlagID, arg.ChallengeID)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminInsertFlag = `-- name: AdminInsertFlag :one

INSERT INTO flags (challenge_id, type, content, case_insensitive)
VALUES ($1, $2, $3, $4)
RETURNING id, challenge_id, type, content, case_insensitive
`

type AdminInsertFlagParams struct {
	ChallengeID     int64
	Type            string
	Content         string
	CaseInsensitive bool
}

// ── flags ───────────────────────────────────────────────────────────────────────
func (q *Queries) AdminInsertFlag(ctx context.Context, arg AdminInsertFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminInsertFlag,
		arg.ChallengeID,
		arg.Type,
		arg.Content,
		arg.CaseInsensitive,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminInsertHint = `-- name: AdminInsertHint :one

INSERT INTO hints (challenge_id, title, content, cost, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, challenge_id, title, content, cost, requirements, position
`

type AdminInsertHintParams struct {
	ChallengeID int64
	Title       *string
	Content     string
	Cost        int32
	Position    int32
}

// ── hints ───────────────────────────────────────────────────────────────────────
func (q *Queries) AdminInsertHint(ctx context.Context, arg AdminInsertHintParams) (Hint, error) {
	row := q.db.QueryRow(ctx, adminInsertHint,
		arg.ChallengeID,
		arg.Title,
		arg.Content,
		arg.Cost,
		arg.Position,
	)
	var i Hint
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Content,
		&i.Cost,
		&i.Requirements,
		&i.Position,
	)
	return i, err
}

const adminListAudit = `-- name: AdminListAudit :many

SELECT id, actor_id, action, target_table, target_id, before, after, at, ip,
       COUNT(*) OVER () AS total
  FROM audit_log
 WHERE ($1::bigint IS NULL OR actor_id = $1)
   AND ($2::text IS NULL OR action = $2)
   AND ($3::text IS NULL OR target_table = $3)
   AND ($4::bigint IS NULL OR target_id = $4)
 ORDER BY at DESC, id DESC
 LIMIT $6::int OFFSET $5::int
`

type AdminListAuditParams struct {
	ActorID     *int64
	Action      *string
	TargetTable *string
	TargetID    *int64
	Off         int32
	Lim         int32
}

type AdminListAuditRow struct {
	ID          int64
	ActorID     *int64
	Action      string
	TargetTable string
	TargetID    *int64
	Before      json.RawMessage
	After       json.RawMessage
	At          pgtype.Timestamptz
	Ip          *netip.Addr
	Total       int64
}

// ── audit trail ───────────────────────────────────────────────────────────────────
// Read-only feed over the capture triggers' output, newest first. Each filter is optional and
// narrows independently; an unset one drops out of the WHERE rather than matching a sentinel. The
// (at, id) tiebreak keeps the order total when many rows share a timestamp, so pages never overlap.
// COUNT(*) OVER () rides along so the page and its total agree in one round trip.
func (q *Queries) AdminListAudit(ctx context.Context, arg AdminListAuditParams) ([]AdminListAuditRow, error) {
	rows, err := q.db.Query(ctx, adminListAudit,
		arg.ActorID,
		arg.Action,
		arg.TargetTable,
		arg.TargetID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditRow{}
	for rows.Next() {
		var i AdminListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetTable,
			&i.TargetID,
			&i.Before,
			&i.After,
			&i.At,
			&i.Ip,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChallengeRequirements = `-- name: AdminListChallengeRequirements :many
SELECT id, requirements FROM challenges
`

type AdminListChallengeRequirementsRow struct {
	ID           int64
	Requirements json.RawMessage
}

// The whole prerequisite graph, for the cycle warning on requirement writes. Boards are small; one
// read beats a traversal query nothing else needs.
func (q *Queries) AdminListChallengeRequirements(ctx context.Context) ([]AdminListChallengeRequirementsRow, error) {
	rows, err := q.db.Query(ctx, adminListChallengeRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListChallengeRequirementsRow{}
	for rows.Next() {
		var i AdminListChallengeRequirementsRow
		if err := rows.Scan(&i.ID, &i.Requirements); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTags = `-- name: AdminListTags :many

SELECT value, count(*) AS uses
  FROM tags
 GROUP BY value
 ORDER BY value
`

type AdminListTagsRow struct {
	Value string
	Uses  int64
}

// ── tags ──────────────────────────────────────────────────────────────────────────
//
// A tag is a (challenge_id, value) row; the same value on many challenges is one tag with several
// uses. These statements treat a tag by its value, which is the unit an operator manages.
func (q *Queries) AdminListTags(ctx context.Context) ([]AdminListTagsRow, error) {
	rows, err := q.db.Query(ctx, adminListTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTagsRow{}
	for rows.Next() {
		var i AdminListTagsRow
		if err := rows.Scan(&i.Value, &i.Uses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT id, name, email, role, verified, banned, hidden, team_id, created_at,
       COUNT(*) OVER () AS total
  FROM users
 ORDER BY id
 LIMIT $2::int OFFSET $1::int
`

type AdminListUsersParams struct {
	Off int32
	Lim int32
}

type AdminListUsersRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Verified  bool
	Banned    bool
	Hidden    bool
	TeamID    *int64
	CreatedAt pgtype.Timestamptz
	Total     int64
}

// ── users ───────────────────────────────────────────────────────────────────────
// COUNT(*) OVER () carries the total in the same round trip, so the pagination header never
// disagrees with the page it describes.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Verified,
			&i.Banned,
			&i.Hidden,
			&i.TeamID,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMergeTagCollisions = `-- name: AdminMergeTagCollisions :execrows
DELETE FROM tags t
 WHERE t.value = $1
   AND EXISTS (SELECT 1 FROM tags o WHERE o.challenge_id = t.challenge_id AND o.value = $2)
`

type AdminMergeTagCollisionsParams struct {
	FromValue string
	ToValue   string
}

// Drop the source rows on challenges that already carry the destination, so the rename that follows
// cannot trip UNIQUE(challenge_id, value). These deletions are real merges and are audited as such.
func (q *Queries) AdminMergeTagCollisions(ctx context.Context, arg AdminMergeTagCollisionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminMergeTagCollisions, arg.FromValue, arg.ToValue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminRenameTag = `-- name: AdminRenameTag :execrows
UPDATE tags SET value = $1 WHERE value = $2
`

type AdminRenameTagParams struct {
	ToValue   string
	FromValue string
}

func (q *Queries) AdminRenameTag(ctx context.Context, arg AdminRenameTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminRenameTag, arg.ToValue, arg.FromValue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminReorderChallenges = `-- name: AdminReorderChallenges :execrows
UPDATE challenges c SET position = v.position, updated_at = now()
FROM (
    SELECT unnest($1::bigint[]) AS id,
           unnest($2::int[]) AS position
) v
WHERE c.id = v.id
`

type AdminReorderChallengesParams struct {
	Ids       []int64
	Positions []int32
}

// Bulk position assignment in one statement: the two arrays are zipped by ordinality, so every
// challenge moves or none does. A row count below the input length means an id did not exist.
func (q *Queries) AdminReorderChallenges(ctx context.Context, arg AdminReorderChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminReorderChallenges, arg.Ids, arg.Positions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSetChallengeRequirements = `-- name: AdminSetChallengeRequirements :one
UPDATE challenges SET requirements = $1::jsonb, updated_at = now()
WHERE id = $2
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminSetChallengeRequirementsParams struct {
	Requirements json.RawMessage
	ChallengeID  int64
}

// Whole-value replace: the column is one document, so a partial patch has no meaning here.
func (q *Queries) AdminSetChallengeRequirements(ctx context.Context, arg AdminSetChallengeRequirementsParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminSetChallengeRequirements, arg.Requirements, arg.ChallengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetChallengeState = `-- name: AdminSetChallengeState :one
UPDATE challenges SET state = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminSetChallengeStateParams struct {
	State       string
	ChallengeID int64
}

func (q *Queries) AdminSetChallengeState(ctx context.Context, arg AdminSetChallengeStateParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminSetChallengeState, arg.State, arg.ChallengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminSetUserBanned = `-- name: AdminSetUserBanned :one
UPDATE users SET banned = $1 WHERE id = $2
RETURNING id, name, banned
`

type AdminSetUserBannedParams struct {
	Banned bool
	UserID int64
}

type AdminSetUserBannedRow struct {
	ID     int64
	Name   string
	Banned bool
}

func (q *Queries) AdminSetUserBanned(ctx context.Context, arg AdminSetUserBannedParams) (AdminSetUserBannedRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserBanned, arg.Banned, arg.UserID)
	var i AdminSetUserBannedRow
	err := row.Scan(&i.ID, &i.Name, &i.Banned)
	return i, err
}

const adminSetUserRole = `-- name: AdminSetUserRole :one
UPDATE users SET role = $1 WHERE id = $2
RETURNING id, name, role
`

type AdminSetUserRoleParams struct {
	Role   string
	UserID int64
}

type AdminSetUserRoleRow struct {
	ID   int64
	Name string
	Role string
}

func (q *Queries) AdminSetUserRole(ctx context.Context, arg AdminSetUserRoleParams) (AdminSetUserRoleRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserRole, arg.Role, arg.UserID)
	var i AdminSetUserRoleRow
	err := row.Scan(&i.ID, &i.Name, &i.Role)
	return i, err
}

const adminUpdateChallenge = `-- name: AdminUpdateChallenge :one
UPDATE challenges SET
    name            = COALESCE($1, name),
    category        = COALESCE($2, category),
    description     = COALESCE($3, description),
    attribution     = CASE WHEN $4::bool THEN NULL
                           ELSE COALESCE($5, attribution) END,
    connection_info = CASE WHEN $6::bool THEN NULL
                           ELSE COALESCE($7, connection_info) END,
    type            = COALESCE($8, type),
    value           = COALESCE($9, value),
    function        = COALESCE($10, function),
    initial         = CASE WHEN $11::bool THEN NULL
                           ELSE COALESCE($12, initial) END,
    minimum         = CASE WHEN $13::bool THEN NULL
                           ELSE COALESCE($14, minimum) END,
    decay           = CASE WHEN $15::bool THEN NULL
                           ELSE COALESCE($16, decay) END,
    max_attempts    = COALESCE($17, max_attempts),
    logic           = COALESCE($18, logic),
    position        = COALESCE($19, position),
    first_blood     = COALESCE($20, first_blood),
    first_blood_bonus = CASE WHEN $21::bool THEN NULL
                             ELSE COALESCE($22, first_blood_bonus) END,
    updated_at      = now()
WHERE id = $23
RETURNING id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at
`

type AdminUpdateChallengeParams struct {
	Name                 *string
	Category             *string
	Description          *string
	ClearAttribution     bool
	Attribution          *string
	ClearConnectionInfo  bool
	ConnectionInfo       *string
	Type                 *string
	Value                *int32
	Function             *string
	ClearInitial         bool
	Initial              *int32
	ClearMinimum         bool
	Minimum              *int32
	ClearDecay           bool
	Decay                *int32
	MaxAttempts          *int32
	Logic                *string
	Position             *int32
	FirstBlood           *string
	ClearFirstBloodBonus bool
	FirstBloodBonus      *int32
	ChallengeID          int64
}

// Partial update with a third state for the nullable columns: an absent field keeps its value, a
// clear flag nulls it, and a supplied value sets it. The three are exclusive per column — the
// transport turns an omitted key into neither, an explicit null into the clear, and a value into
// the narg. The dynamic-params CHECK still arbitrates the result, so clearing initial on a decayed
// challenge is refused, not silently stored.
func (q *Queries) AdminUpdateChallenge(ctx context.Context, arg AdminUpdateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, adminUpdateChallenge,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.ClearAttribution,
		arg.Attribution,
		arg.ClearConnectionInfo,
		arg.ConnectionInfo,
		arg.Type,
		arg.Value,
		arg.Function,
		arg.ClearInitial,
		arg.Initial,
		arg.ClearMinimum,
		arg.Minimum,
		arg.ClearDecay,
		arg.Decay,
		arg.MaxAttempts,
		arg.Logic,
		arg.Position,
		arg.FirstBlood,
		arg.ClearFirstBloodBonus,
		arg.FirstBloodBonus,
		arg.ChallengeID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminUpdateFlag = `-- name: AdminUpdateFlag :one
UPDATE flags SET
    type             = COALESCE($1, type),
    content          = COALESCE($2, content),
    case_insensitive = COALESCE($3, case_insensitive)
WHERE id = $4 AND challenge_id = $5
RETURNING id, challenge_id, type, content, case_insensitive
`

type AdminUpdateFlagParams struct {
	Type            *string
	Content         *string
	CaseInsensitive *bool
	FlagID          int64
	ChallengeID     int64
}

// Scoped by challenge_id in the WHERE, not checked in Go: a flag id from another challenge's URL
// affects zero rows, so there is no window and no forgotten guard.
func (q *Queries) AdminUpdateFlag(ctx context.Context, arg AdminUpdateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, adminUpdateFlag,
		arg.Type,
		arg.Content,
		arg.CaseInsensitive,
		arg.FlagID,
		arg.ChallengeID,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Type,
		&i.Content,
		&i.CaseInsensitive,
	)
	return i, err
}

const adminUpdateHint = `-- name: AdminUpdateHint :one
UPDATE hints SET
    title    = COALESCE($1, title),
    content  = COALESCE($2, content),
    cost     = COALESCE($3, cost),
    position = COALESCE($4, position)
WHERE id = $5 AND challenge_id = $6
RETURNING id, challenge_id, title, content, cost, requirements, position
`

type AdminUpdateHintParams struct {
	Title       *string
	Content     *string
	Cost        *int32
	Position    *int32
	HintID      int64
	ChallengeID int64
}

func (q *Queries) AdminUpdateHint(ctx context.Context, arg AdminUpdateHintParams) (Hint, error) {
	row := q.db.QueryRow(ctx, adminUpdateHint,
		arg.Title,
		arg.Content,
		arg.Cost,
		arg.Position,
		arg.HintID,
		arg.ChallengeID,
	)
	var i Hint
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Content,
		&i.Cost,
		&i.Requirements,
		&i.Position,
	)
	return i, err
}
