// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_verification.sql

package db

import (
	"context"
)

const adminSetUserVerified = `-- name: AdminSetUserVerified :one

UPDATE users SET verified = $1 WHERE id = $2
RETURNING id, name, verified
`

type AdminSetUserVerifiedParams struct {
	Verified bool
	UserID   int64
}

type AdminSetUserVerifiedRow struct {
	ID       int64
	Name     string
	Verified bool
}

// Admin-side verification repair: the escape hatch for an event whose mail never arrives.
// Every statement here runs inside a transaction that has stamped the acting admin into
// app.actor_id, so the capture triggers write the audit row in the same transaction as the
// change itself. Flipping who counts as a verified player is exactly the kind of act that
// has to be attributable afterwards.
func (q *Queries) AdminSetUserVerified(ctx context.Context, arg AdminSetUserVerifiedParams) (AdminSetUserVerifiedRow, error) {
	row := q.db.QueryRow(ctx, adminSetUserVerified, arg.Verified, arg.UserID)
	var i AdminSetUserVerifiedRow
	err := row.Scan(&i.ID, &i.Name, &i.Verified)
	return i, err
}

const adminVerifyAllUsers = `-- name: AdminVerifyAllUsers :execrows
UPDATE users SET verified = true WHERE verified = false
`

// The whole-event repair, for a mailer that accepted everything and delivered nothing.
// Narrowed to the rows that actually change: the audit trail then names exactly the accounts
// this unblocked, and running it twice is a no-op rather than a second sweep of noise.
func (q *Queries) AdminVerifyAllUsers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, adminVerifyAllUsers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
