// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_read.sql

package db

import (
	"context"
)

const adminListChallengeFlags = `-- name: AdminListChallengeFlags :many
SELECT id, challenge_id, type, content, case_insensitive FROM flags WHERE challenge_id = $1 ORDER BY id
`

// Every flag on a challenge, plaintext content included. This is the one read that returns a flag's
// content, and it is reachable only behind the admin gate — the player detail redacts flags entirely.
func (q *Queries) AdminListChallengeFlags(ctx context.Context, challengeID int64) ([]Flag, error) {
	rows, err := q.db.Query(ctx, adminListChallengeFlags, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flag{}
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.Type,
			&i.Content,
			&i.CaseInsensitive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChallengeHints = `-- name: AdminListChallengeHints :many
SELECT id, challenge_id, title, content, cost, requirements, position FROM hints WHERE challenge_id = $1 ORDER BY position, id
`

// Every hint on a challenge in unlock order, body included — unlike the player list, which withholds
// the content until it is bought.
func (q *Queries) AdminListChallengeHints(ctx context.Context, challengeID int64) ([]Hint, error) {
	rows, err := q.db.Query(ctx, adminListChallengeHints, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hint{}
	for rows.Next() {
		var i Hint
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.Title,
			&i.Content,
			&i.Cost,
			&i.Requirements,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListChallenges = `-- name: AdminListChallenges :many

SELECT
    c.id, c.name, c.category, c.value, c.function, c.state,
    (SELECT count(*) FROM solves s WHERE s.challenge_id = c.id)::bigint AS solve_count,
    (SELECT count(*) FROM flags  f WHERE f.challenge_id = c.id)::bigint AS flag_count,
    (SELECT count(*) FROM hints  h WHERE h.challenge_id = c.id)::bigint AS hint_count
  FROM challenges c
 ORDER BY c.category, c.position, c.id
`

type AdminListChallengesRow struct {
	ID         int64
	Name       string
	Category   string
	Value      int32
	Function   string
	State      string
	SolveCount int64
	FlagCount  int64
	HintCount  int64
}

// Admin reads for the challenge authoring console. These are plain reads — no audit transaction —
// and they deliberately ignore the visible/hidden state and the anonymize gate that the player
// catalog applies: an operator authors every challenge, hidden ones included, and reads back the
// flags a player is never shown.
// The operator's board: every challenge in board order regardless of state, each row carrying the
// counts the console shows (solves, flags, hints) so the list renders them without a per-row read.
func (q *Queries) AdminListChallenges(ctx context.Context) ([]AdminListChallengesRow, error) {
	rows, err := q.db.Query(ctx, adminListChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListChallengesRow{}
	for rows.Next() {
		var i AdminListChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Value,
			&i.Function,
			&i.State,
			&i.SolveCount,
			&i.FlagCount,
			&i.HintCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
