// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anticheat.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountName = `-- name: AccountName :one
SELECT coalesce(u.name, t.name, '')::text AS name
  FROM instance i
  LEFT JOIN users u ON i.user_mode = 'users' AND u.id = $1::bigint
  LEFT JOIN teams t ON i.user_mode = 'teams' AND t.id = $1::bigint
`

// The display name of one scoring account, resolved by mode. Empty string when the id matches no
// account: the report is analytics over the submissions log, not an account lookup, so a name here
// is a courtesy for the header and its absence is not an error. instance is a singleton, so this is
// always exactly one row.
func (q *Queries) AccountName(ctx context.Context, accountID int64) (string, error) {
	row := q.db.QueryRow(ctx, accountName, accountID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const countFlagSharingPairs = `-- name: CountFlagSharingPairs :one
SELECT count(*) FROM (
    SELECT sub.attributed_account_id,
           (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
      FROM submissions sub
      CROSS JOIN instance i
     WHERE sub.type = 'correct'
       AND sub.attributed_account_id IS NOT NULL
       AND sub.attributed_account_id IS DISTINCT FROM
           (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
     GROUP BY 1, 2
) pairs
`

// The distinct (issued-to, submitted-by) pair count behind FindFlagSharingPairs, for pagination.
func (q *Queries) CountFlagSharingPairs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFlagSharingPairs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIPOverlaps = `-- name: CountIPOverlaps :one
SELECT count(*) FROM (
    SELECT sub.ip
      FROM submissions sub
      CROSS JOIN instance i
     WHERE sub.ip IS NOT NULL
       AND (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) IS NOT NULL
     GROUP BY sub.ip
    HAVING count(DISTINCT (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END))
           >= $1::int
) clusters
`

// The count of IP clusters meeting the threshold, for pagination.
func (q *Queries) CountIPOverlaps(ctx context.Context, minAccounts int32) (int64, error) {
	row := q.db.QueryRow(ctx, countIPOverlaps, minAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnissuedSolves = `-- name: CountUnissuedSolves :one
SELECT count(*)
  FROM solves s
  JOIN challenges c ON c.id = s.challenge_id
  CROSS JOIN instance i
 WHERE c.flag_mode = 'unique'
   AND NOT EXISTS (
       SELECT 1
         FROM flag_issues fi
        WHERE fi.challenge_id = s.challenge_id
          AND fi.account_id = (CASE WHEN i.user_mode = 'teams' THEN s.team_id ELSE s.user_id END)
   )
`

// The unissued-solve count behind FindUnissuedSolves, for pagination.
func (q *Queries) CountUnissuedSolves(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnissuedSolves)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findFlagSharing = `-- name: FindFlagSharing :many

SELECT sub.id, sub.date, sub.challenge_id, sub.user_id, sub.team_id, sub.ip,
       sub.attributed_account_id
  FROM submissions sub
  CROSS JOIN instance i
 WHERE sub.type = 'correct'
   AND sub.attributed_account_id IS NOT NULL
   AND sub.attributed_account_id IS DISTINCT FROM
       (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
 ORDER BY sub.date DESC
 LIMIT $1::int
`

type FindFlagSharingRow struct {
	ID                  int64
	Date                pgtype.Timestamptz
	ChallengeID         int64
	UserID              int64
	TeamID              *int64
	Ip                  *netip.Addr
	AttributedAccountID *int64
}

// The anti-cheat detectors. Reads only. These never mutate, never penalise, and never tell the
// player anything: auto-penalisation was considered and rejected (no appeal path, and a false
// positive becomes an instant ban during a live event). They feed an admin review queue; a human
// decides, out of band.
// A predicate on `submissions` alone — no join to flag_issues, no join to
// challenge_instances. That is the entire payoff of stamping `attributed_account_id` inside the
// submit transaction: the evidence survives the instance being rotated, regenerated or
// deleted, and it survives swapping FlagIssuer to the HMAC implementation later. A join-based audit
// trail is only as durable as the rows it joins to; a stamped one is a fact.
//
// Served by submissions_sharing_idx, which is partial — only correct, attributed submissions are
// ever scanned, a tiny fraction of the table.
//
// The account model comes from `instance`. In teams mode the unit is the team, so
// intra-team sharing is invisible by design: teammates legitimately share artifacts and flags — that
// is what a team is. The detector fires only across accounts, which is the thing worth catching.
func (q *Queries) FindFlagSharing(ctx context.Context, lim int32) ([]FindFlagSharingRow, error) {
	rows, err := q.db.Query(ctx, findFlagSharing, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFlagSharingRow{}
	for rows.Next() {
		var i FindFlagSharingRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.ChallengeID,
			&i.UserID,
			&i.TeamID,
			&i.Ip,
			&i.AttributedAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFlagSharingForAccount = `-- name: FindFlagSharingForAccount :many
SELECT direction, counterparty,
       count(*)                                   AS submission_count,
       array_agg(DISTINCT challenge_id)::bigint[] AS challenge_ids,
       min(date)::timestamptz                     AS first_seen,
       max(date)::timestamptz                     AS last_seen,
       max(coalesce(cu.name, ct.name, ''))::text     AS counterparty_name
  FROM (
    SELECT
        (CASE WHEN sub.attributed_account_id = $1::bigint
              THEN 'issued_to' ELSE 'submitted' END) AS direction,
        (CASE WHEN sub.attributed_account_id = $1::bigint
              THEN (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
              ELSE sub.attributed_account_id END)::bigint AS counterparty,
        sub.challenge_id, sub.date
      FROM submissions sub
      CROSS JOIN instance i
     WHERE sub.type = 'correct'
       AND sub.attributed_account_id IS NOT NULL
       AND sub.attributed_account_id IS DISTINCT FROM
           (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
       AND (sub.attributed_account_id = $1::bigint
            OR (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) = $1::bigint)
  ) e
  CROSS JOIN instance i
  LEFT JOIN users cu ON i.user_mode = 'users' AND cu.id = e.counterparty
  LEFT JOIN teams ct ON i.user_mode = 'teams' AND ct.id = e.counterparty
 GROUP BY direction, counterparty
 ORDER BY submission_count DESC
`

type FindFlagSharingForAccountRow struct {
	Direction        string
	Counterparty     int64
	SubmissionCount  int64
	ChallengeIds     []int64
	FirstSeen        pgtype.Timestamptz
	LastSeen         pgtype.Timestamptz
	CounterpartyName string
}

// One account's sharing evidence, both directions: flags issued to it that another account submitted
// (direction='issued_to') and flags it submitted that were issued to another (direction='submitted'),
// grouped by counterparty. Bounded to one account, so it is not paginated.
func (q *Queries) FindFlagSharingForAccount(ctx context.Context, accountID int64) ([]FindFlagSharingForAccountRow, error) {
	rows, err := q.db.Query(ctx, findFlagSharingForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFlagSharingForAccountRow{}
	for rows.Next() {
		var i FindFlagSharingForAccountRow
		if err := rows.Scan(
			&i.Direction,
			&i.Counterparty,
			&i.SubmissionCount,
			&i.ChallengeIds,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CounterpartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFlagSharingPairs = `-- name: FindFlagSharingPairs :many
SELECT sub.attributed_account_id::bigint AS issued_to,
       (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)::bigint AS submitter,
       count(*)                                          AS submission_count,
       count(DISTINCT sub.challenge_id)                  AS challenge_count,
       array_agg(DISTINCT sub.challenge_id)::bigint[]    AS challenge_ids,
       min(sub.date)::timestamptz                        AS first_seen,
       max(sub.date)::timestamptz                        AS last_seen,
       max(coalesce(iu.name, it.name, ''))::text                AS issued_to_name,
       max(coalesce(su.name, st.name, ''))::text                AS submitter_name
  FROM submissions sub
  CROSS JOIN instance i
  LEFT JOIN users iu ON i.user_mode = 'users' AND iu.id = sub.attributed_account_id
  LEFT JOIN teams it ON i.user_mode = 'teams' AND it.id = sub.attributed_account_id
  LEFT JOIN users su ON i.user_mode = 'users' AND su.id = sub.user_id
  LEFT JOIN teams st ON i.user_mode = 'teams' AND st.id = sub.team_id
 WHERE sub.type = 'correct'
   AND sub.attributed_account_id IS NOT NULL
   AND sub.attributed_account_id IS DISTINCT FROM
       (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
 GROUP BY sub.attributed_account_id,
          (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
 ORDER BY submission_count DESC, last_seen DESC
 LIMIT $2::int OFFSET $1::int
`

type FindFlagSharingPairsParams struct {
	Off int32
	Lim int32
}

type FindFlagSharingPairsRow struct {
	IssuedTo        int64
	Submitter       int64
	SubmissionCount int64
	ChallengeCount  int64
	ChallengeIds    []int64
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
	IssuedToName    string
	SubmitterName   string
}

// Flag sharing, folded to one row per offender pair: account `submitter` submitted correct flags that
// were issued to account `issued_to`. Same predicate as FindFlagSharing — submissions alone, so it
// survives instance rotation — but grouped, counted, and with the challenge span, so a pair that
// shared twenty flags is one row of evidence, not twenty. Served by submissions_sharing_idx.
//
// Both account names come along resolved by mode — a name for the offender pair is the whole point
// of the review screen. The name joins are 1:1 on the account primary key, so they do not touch the
// counts. max() over the group is just "the one name this account has"; it never varies within a pair.
func (q *Queries) FindFlagSharingPairs(ctx context.Context, arg FindFlagSharingPairsParams) ([]FindFlagSharingPairsRow, error) {
	rows, err := q.db.Query(ctx, findFlagSharingPairs, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFlagSharingPairsRow{}
	for rows.Next() {
		var i FindFlagSharingPairsRow
		if err := rows.Scan(
			&i.IssuedTo,
			&i.Submitter,
			&i.SubmissionCount,
			&i.ChallengeCount,
			&i.ChallengeIds,
			&i.FirstSeen,
			&i.LastSeen,
			&i.IssuedToName,
			&i.SubmitterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIPOverlapForAccount = `-- name: FindIPOverlapForAccount :many
WITH mine AS (
    SELECT DISTINCT sub.ip
      FROM submissions sub
      CROSS JOIN instance i
     WHERE sub.ip IS NOT NULL
       AND (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) = $1::bigint
)
SELECT sub.ip,
       (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)::bigint AS other_account_id,
       count(*)                   AS submission_count,
       min(sub.date)::timestamptz AS first_seen,
       max(sub.date)::timestamptz AS last_seen,
       max(coalesce(ou.name, ot.name, ''))::text AS other_account_name
  FROM submissions sub
  CROSS JOIN instance i
  JOIN mine ON mine.ip = sub.ip
  LEFT JOIN users ou ON i.user_mode = 'users' AND ou.id = sub.user_id
  LEFT JOIN teams ot ON i.user_mode = 'teams' AND ot.id = sub.team_id
 WHERE (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END)
           IS DISTINCT FROM $1::bigint
   AND (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) IS NOT NULL
 GROUP BY sub.ip, other_account_id
 ORDER BY sub.ip, submission_count DESC
 LIMIT $2::int
`

type FindIPOverlapForAccountParams struct {
	AccountID int64
	Lim       int32
}

type FindIPOverlapForAccountRow struct {
	Ip               *netip.Addr
	OtherAccountID   int64
	SubmissionCount  int64
	FirstSeen        pgtype.Timestamptz
	LastSeen         pgtype.Timestamptz
	OtherAccountName string
}

// The other accounts that shared an address with @account_id, one row per (address, other account).
// Same signal caveat as FindIPOverlaps: shared egress is common and this only points a human at a
// coincidence worth checking.
func (q *Queries) FindIPOverlapForAccount(ctx context.Context, arg FindIPOverlapForAccountParams) ([]FindIPOverlapForAccountRow, error) {
	rows, err := q.db.Query(ctx, findIPOverlapForAccount, arg.AccountID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindIPOverlapForAccountRow{}
	for rows.Next() {
		var i FindIPOverlapForAccountRow
		if err := rows.Scan(
			&i.Ip,
			&i.OtherAccountID,
			&i.SubmissionCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OtherAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIPOverlaps = `-- name: FindIPOverlaps :many
WITH seen AS (
    SELECT sub.ip,
           (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) AS account,
           coalesce(u.name, t.name, '')                                            AS name,
           sub.date
      FROM submissions sub
      CROSS JOIN instance i
      LEFT JOIN users u ON i.user_mode = 'users' AND u.id = sub.user_id
      LEFT JOIN teams t ON i.user_mode = 'teams' AND t.id = sub.team_id
     WHERE sub.ip IS NOT NULL
       AND (CASE WHEN i.user_mode = 'teams' THEN sub.team_id ELSE sub.user_id END) IS NOT NULL
),
per_account AS (
    SELECT ip, account, min(name) AS name, min(date) AS first_seen, max(date) AS last_seen
      FROM seen
     GROUP BY ip, account
)
SELECT ip,
       count(*)                                      AS account_count,
       array_agg(account ORDER BY account)::bigint[] AS account_ids,
       array_agg(name ORDER BY account)::text[]      AS account_names,
       min(first_seen)::timestamptz                  AS first_seen,
       max(last_seen)::timestamptz                   AS last_seen
  FROM per_account
 GROUP BY ip
HAVING count(*) >= $1::int
 ORDER BY account_count DESC, ip
 LIMIT $3::int OFFSET $2::int
`

type FindIPOverlapsParams struct {
	MinAccounts int32
	Off         int32
	Lim         int32
}

type FindIPOverlapsRow struct {
	Ip           *netip.Addr
	AccountCount int64
	AccountIds   []int64
	AccountNames []string
	FirstSeen    pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
}

// Addresses used by several distinct accounts. This is a SIGNAL, not a verdict: shared NAT, a campus,
// a corporate egress or a carrier-grade NAT pool all put unrelated players behind one address, so a
// cluster is evidence for a human to weigh, never grounds to act on alone. @min_accounts tunes how
// many distinct accounts on one address is worth surfacing. In teams mode the account is the team, so
// teammates behind one router do not trip it. Served by submissions_ip_idx.
//
// account_ids and account_names are two arrays built under the SAME `ORDER BY account`, so element i
// of one lines up with element i of the other — names are deliberately not unique, so a second name
// array distinct-aggregated on its own would not align. The per-account fold happens first, in a CTE,
// so the outer count is a plain COUNT of accounts rather than a COUNT(DISTINCT) repeated three times.
func (q *Queries) FindIPOverlaps(ctx context.Context, arg FindIPOverlapsParams) ([]FindIPOverlapsRow, error) {
	rows, err := q.db.Query(ctx, findIPOverlaps, arg.MinAccounts, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindIPOverlapsRow{}
	for rows.Next() {
		var i FindIPOverlapsRow
		if err := rows.Scan(
			&i.Ip,
			&i.AccountCount,
			&i.AccountIds,
			&i.AccountNames,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnissuedSolves = `-- name: FindUnissuedSolves :many
SELECT s.id AS solve_id, s.challenge_id, c.name AS challenge_name,
       (CASE WHEN i.user_mode = 'teams' THEN s.team_id ELSE s.user_id END)::bigint AS account_id,
       s.user_id, s.team_id, s.date, s.value,
       su.name AS user_name,
       st.name AS team_name
  FROM solves s
  JOIN challenges c ON c.id = s.challenge_id
  CROSS JOIN instance i
  LEFT JOIN users su ON su.id = s.user_id
  LEFT JOIN teams st ON st.id = s.team_id
 WHERE c.flag_mode = 'unique'
   AND NOT EXISTS (
       SELECT 1
         FROM flag_issues fi
        WHERE fi.challenge_id = s.challenge_id
          AND fi.account_id = (CASE WHEN i.user_mode = 'teams' THEN s.team_id ELSE s.user_id END)
   )
 ORDER BY s.date DESC, s.id DESC
 LIMIT $2::int OFFSET $1::int
`

type FindUnissuedSolvesParams struct {
	Off int32
	Lim int32
}

type FindUnissuedSolvesRow struct {
	SolveID       int64
	ChallengeID   int64
	ChallengeName string
	AccountID     int64
	UserID        int64
	TeamID        *int64
	Date          pgtype.Timestamptz
	Value         int32
	UserName      *string
	TeamName      *string
}

// The provable detector, not a statistical signal.
//
// A solve on a flag_mode='unique' challenge by an account that was never issued an instance. There is
// no honest way to hold a valid flag for a challenge whose artifact you never fetched: assignment is
// lazy, so a flag_issues row exists for every account that so much as opened the challenge. No such
// row means the flag came from somewhere else. Full stop.
//
// The user and team names ride along so the review screen names who to talk to: in teams mode the
// account is the team, but a solve is still one human's act, so both the submitter and their team
// are worth showing.
//
// Anti-join over solves_challenge_firstblood_idx × the flag_issues PK. No new index.
func (q *Queries) FindUnissuedSolves(ctx context.Context, arg FindUnissuedSolvesParams) ([]FindUnissuedSolvesRow, error) {
	rows, err := q.db.Query(ctx, findUnissuedSolves, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindUnissuedSolvesRow{}
	for rows.Next() {
		var i FindUnissuedSolvesRow
		if err := rows.Scan(
			&i.SolveID,
			&i.ChallengeID,
			&i.ChallengeName,
			&i.AccountID,
			&i.UserID,
			&i.TeamID,
			&i.Date,
			&i.Value,
			&i.UserName,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
