// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpRateLimit = `-- name: BumpRateLimit :one

INSERT INTO rate_limits (bucket, window_start, n)
VALUES ($1, $2, 1)
ON CONFLICT (bucket, window_start) DO UPDATE
   SET n = rate_limits.n + 1
RETURNING n
`

type BumpRateLimitParams struct {
	Bucket      string
	WindowStart pgtype.Timestamptz
}

// ── rate limits ─────────────────────────────────────────────────────────────────
// Atomic on Postgres alone. The row is the counter, so there is no increment to lose: two
// concurrent bumps serialize on the primary key and both see a correct value.
func (q *Queries) BumpRateLimit(ctx context.Context, arg BumpRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpRateLimit, arg.Bucket, arg.WindowStart)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, token_hash, description, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, description, created_at, expires_at
`

type CreateAPITokenParams struct {
	UserID      int64
	TokenHash   []byte
	Description *string
	ExpiresAt   pgtype.Timestamptz
}

type CreateAPITokenRow struct {
	ID          int64
	UserID      int64
	Description *string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// ── api tokens ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.TokenHash,
		arg.Description,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (name, email, password_hash, role, verified)
VALUES ($1, $2, $3, 'admin', true)
RETURNING id
`

type CreateAdminParams struct {
	Name         string
	Email        string
	PasswordHash *string
}

// The first-admin bootstrap. role='admin' cannot be granted through the admin API without an admin
// already existing, so the very first one is made here instead. verified is stamped true because the
// account has no inbox flow behind a console command. The caller runs this with the caps trigger
// disabled for the transaction, so a full instance cannot lock its own first admin out.
func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Name, arg.Email, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id_hash, user_id, pw_fingerprint, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_hash, user_id, csrf_token, expires_at
`

type CreateSessionParams struct {
	IDHash        []byte
	UserID        int64
	PwFingerprint []byte
	CsrfToken     string
	ExpiresAt     pgtype.Timestamptz
}

type CreateSessionRow struct {
	IDHash    []byte
	UserID    int64
	CsrfToken string
	ExpiresAt pgtype.Timestamptz
}

// ── sessions ────────────────────────────────────────────────────────────────────
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.IDHash,
		arg.UserID,
		arg.PwFingerprint,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, verified)
VALUES ($1, $2, $3, $4)
RETURNING id, verified
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash *string
	Verified     bool
}

type CreateUserRow struct {
	ID       int64
	Verified bool
}

// Registration. The unique email and the num_users/team_size caps are enforced by the index and the
// caps trigger, so a duplicate raises 23505 and an over-cap insert raises a check_violation — both
// surface as errors here rather than as a lost check-then-insert race.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Verified,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Verified)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     int64
	UserID int64
}

// Scoped by user_id as well as id: ownership is enforced in the WHERE clause rather than by a
// SELECT-then-check in Go, so there is no window and no forgotten guard. Zero rows affected means
// "not yours, or not there", and the caller cannot tell the difference — which is correct.
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAPITokens = `-- name: DeleteExpiredAPITokens :exec
DELETE FROM api_tokens WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredAPITokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAPITokens)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteOldRateLimits = `-- name: DeleteOldRateLimits :exec
DELETE FROM rate_limits WHERE window_start < $1
`

func (q *Queries) DeleteOldRateLimits(ctx context.Context, before pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldRateLimits, before)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const deleteTeamSessions = `-- name: DeleteTeamSessions :exec
DELETE FROM sessions
 WHERE user_id IN (SELECT id FROM users WHERE team_id = $1)
`

// A team ban's session sweep. The ban wall stops every member on their next request even
// without this — the wall reads team_banned per request — but a live cookie on a banned
// team is still a door left unlocked.
func (q *Queries) DeleteTeamSessions(ctx context.Context, teamID *int64) error {
	_, err := q.db.Exec(ctx, deleteTeamSessions, teamID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

// "Log out everywhere". Also what a ban should call — a banned user's live cookie is still a live
// cookie, and the ban wall stops them on the next request, but there is no reason to leave the door
// shut and unlocked.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, description, created_at, expires_at
  FROM api_tokens
 WHERE token_hash = $1
   AND expires_at > now()
`

type GetAPITokenRow struct {
	ID          int64
	UserID      int64
	Description *string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// Looked up by sha256(token); the plaintext is shown once, at creation, and never stored —
// a table of plaintext secrets turns every dump or export into a bearer-credential leak.
// Expiry is enforced here, in the WHERE clause, for the same reason as sessions.
func (q *Queries) GetAPIToken(ctx context.Context, tokenHash []byte) (GetAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getAPIToken, tokenHash)
	var i GetAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id_hash, s.user_id, s.pw_fingerprint, s.csrf_token, s.expires_at,
       u.password_hash
  FROM sessions s
  JOIN users u ON u.id = s.user_id
 WHERE s.id_hash = $1
   AND s.expires_at > now()
`

type GetSessionRow struct {
	IDHash        []byte
	UserID        int64
	PwFingerprint []byte
	CsrfToken     string
	ExpiresAt     pgtype.Timestamptz
	PasswordHash  *string
}

// Expiry is a WHERE clause, not a Go comparison: an expired session must be indistinguishable from
// a missing one, and it must be so at the only place that can be tricked into disagreeing — the
// database. `now()` is the transaction's clock, not the app server's, so a skewed pod cannot extend
// a session.
//
// pw_fingerprint comes back so the caller can compare it against the user's current password hash.
// A mismatch means the password changed after this session was minted, and the session is dead.
func (q *Queries) GetSession(ctx context.Context, idHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, idHash)
	var i GetSessionRow
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.PwFingerprint,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, name, email, password_hash, role, verified, banned, must_change_password, team_id
  FROM users WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID                 int64
	Name               string
	Email              string
	PasswordHash       *string
	Role               string
	Verified           bool
	Banned             bool
	MustChangePassword bool
	TeamID             *int64
}

// ── credentials ─────────────────────────────────────────────────────────────────
// Case-insensitive, matching users_email_uniq: lookup and the uniqueness constraint must
// agree on the fold, or an address can be registered twice and reset neither time.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.Banned,
		&i.MustChangePassword,
		&i.TeamID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, verified, banned, must_change_password, team_id,
       website, affiliation, country
  FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID                 int64
	Name               string
	Email              string
	PasswordHash       *string
	Role               string
	Verified           bool
	Banned             bool
	MustChangePassword bool
	TeamID             *int64
	Website            *string
	Affiliation        *string
	Country            *string
}

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Verified,
		&i.Banned,
		&i.MustChangePassword,
		&i.TeamID,
		&i.Website,
		&i.Affiliation,
		&i.Country,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, description, created_at, expires_at
  FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

type ListAPITokensRow struct {
	ID          int64
	UserID      int64
	Description *string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadPrincipal = `-- name: LoadPrincipal :one

WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT
    u.id                AS user_id,
    u.team_id,
    u.role = 'admin'    AS is_admin,
    u.verified,
    u.banned,
    u.must_change_password,
    COALESCE(t.banned, false) AS team_banned,
    COALESCE((SELECT m.user_mode = 'teams' FROM mode m) AND u.team_id IS NULL, false)::boolean AS teamless,
    NOT EXISTS (
        SELECT 1 FROM fields f
         WHERE f.applies_to = 'user' AND f.required
           AND NOT EXISTS (
               SELECT 1 FROM field_entries fe
                WHERE fe.field_id = f.id AND fe.user_id = u.id
                  AND fe.value IS NOT NULL
                  AND fe.value <> 'null'::jsonb AND fe.value <> '""'::jsonb
           )
    ) AS profile_complete,
    NOT EXISTS (
        SELECT 1 FROM fields f
         WHERE f.applies_to = 'team' AND f.required AND u.team_id IS NOT NULL
           AND NOT EXISTS (
               SELECT 1 FROM field_entries fe
                WHERE fe.field_id = f.id AND fe.team_id = u.team_id
                  AND fe.value IS NOT NULL
                  AND fe.value <> 'null'::jsonb AND fe.value <> '""'::jsonb
           )
    ) AS team_profile_complete
  FROM users u
  LEFT JOIN teams t ON t.id = u.team_id
 WHERE u.id = $1
`

type LoadPrincipalRow struct {
	UserID              int64
	TeamID              *int64
	IsAdmin             bool
	Verified            bool
	Banned              bool
	MustChangePassword  bool
	TeamBanned          bool
	Teamless            bool
	ProfileComplete     bool
	TeamProfileComplete bool
}

// Authentication: sessions, API tokens, and the one query that resolves a caller to a Principal.
// THE authentication query. Sessions and API tokens both converge here before any
// authorization runs, so a token cannot route around a wall a cookie hits.
//
// Deliberately absent: `hidden`. A hidden account authenticates and plays normally —
// hiddenness is a scoreboard predicate, never an auth decision.
//
// `profile_complete` is the required-fields gate. NOT EXISTS over the missing entries,
// so the answer is a boolean and not a count the caller has to interpret.
func (q *Queries) LoadPrincipal(ctx context.Context, userID int64) (LoadPrincipalRow, error) {
	row := q.db.QueryRow(ctx, loadPrincipal, userID)
	var i LoadPrincipalRow
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.IsAdmin,
		&i.Verified,
		&i.Banned,
		&i.MustChangePassword,
		&i.TeamBanned,
		&i.Teamless,
		&i.ProfileComplete,
		&i.TeamProfileComplete,
	)
	return i, err
}

const promoteToAdmin = `-- name: PromoteToAdmin :execrows
UPDATE users SET role = 'admin', verified = true
WHERE lower(email) = lower($1)
`

// Elevate an existing user to a verified admin, by email (case-insensitive, matching
// users_email_uniq). role is not one of the columns the caps trigger watches, so this needs no
// exemption. execrows so the caller can distinguish "no such user" from a real promotion.
func (q *Queries) PromoteToAdmin(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteToAdmin, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen = now() WHERE id_hash = $1
`

func (q *Queries) TouchSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, touchSession, idHash)
	return err
}

const updateOwnProfile = `-- name: UpdateOwnProfile :one
UPDATE users SET
    website     = CASE WHEN $1::bool THEN NULL
                       ELSE COALESCE($2, website) END,
    affiliation = CASE WHEN $3::bool THEN NULL
                       ELSE COALESCE($4, affiliation) END,
    country     = CASE WHEN $5::bool THEN NULL
                       ELSE COALESCE($6, country) END
WHERE id = $7
RETURNING id, name, email, role, verified, banned, team_id, website, affiliation, country
`

type UpdateOwnProfileParams struct {
	ClearWebsite     bool
	Website          *string
	ClearAffiliation bool
	Affiliation      *string
	ClearCountry     bool
	Country          *string
	UserID           int64
}

type UpdateOwnProfileRow struct {
	ID          int64
	Name        string
	Email       string
	Role        string
	Verified    bool
	Banned      bool
	TeamID      *int64
	Website     *string
	Affiliation *string
	Country     *string
}

// The self-serve profile write: the player-owned fields and nothing else. Identity and
// moderation state are not in the SET list, so this statement cannot be talked into touching them.
func (q *Queries) UpdateOwnProfile(ctx context.Context, arg UpdateOwnProfileParams) (UpdateOwnProfileRow, error) {
	row := q.db.QueryRow(ctx, updateOwnProfile,
		arg.ClearWebsite,
		arg.Website,
		arg.ClearAffiliation,
		arg.Affiliation,
		arg.ClearCountry,
		arg.Country,
		arg.UserID,
	)
	var i UpdateOwnProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Verified,
		&i.Banned,
		&i.TeamID,
		&i.Website,
		&i.Affiliation,
		&i.Country,
	)
	return i, err
}

const updatePasswordAndClearForcedChange = `-- name: UpdatePasswordAndClearForcedChange :exec
UPDATE users SET password_hash = $1, must_change_password = false
 WHERE id = $2
`

type UpdatePasswordAndClearForcedChangeParams struct {
	PasswordHash *string
	UserID       int64
}

// A real password change: the user chose a new password, so a pending forced change is satisfied.
// One statement, so the flag can never clear without the hash that justifies it.
func (q *Queries) UpdatePasswordAndClearForcedChange(ctx context.Context, arg UpdatePasswordAndClearForcedChangeParams) error {
	_, err := q.db.Exec(ctx, updatePasswordAndClearForcedChange, arg.PasswordHash, arg.UserID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordHashParams struct {
	PasswordHash *string
	UserID       int64
}

// The rehash-on-login path only: a bcrypt hash from an import, silently upgraded to Argon2id while
// we hold the plaintext. The password itself has not changed, so must_change_password stays put —
// a forced user logging in must not discharge the order by the act of logging in.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.UserID)
	return err
}
