// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: awards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantTeamAward = `-- name: GrantTeamAward :one
INSERT INTO awards (user_id, team_id, type, name, description, value)
SELECT t.captain_id, t.id, 'standard', 'manual adjustment', $1, $2
  FROM teams t
 WHERE t.id = $3 AND t.captain_id IS NOT NULL
RETURNING id, user_id, team_id, value, description, date
`

type GrantTeamAwardParams struct {
	Reason *string
	Value  int32
	TeamID int64
}

type GrantTeamAwardRow struct {
	ID          int64
	UserID      int64
	TeamID      *int64
	Value       int32
	Description *string
	Date        pgtype.Timestamptz
}

// Teams mode: the scoring account is the team. awards.user_id is NOT NULL, so the adjustment is
// recorded against the team's captain — its representative member, kept current by the enrolment
// trigger. A team with no members (captain_id IS NULL) has no way to score and is refused as zero
// rows rather than silently violating the NOT NULL.
func (q *Queries) GrantTeamAward(ctx context.Context, arg GrantTeamAwardParams) (GrantTeamAwardRow, error) {
	row := q.db.QueryRow(ctx, grantTeamAward, arg.Reason, arg.Value, arg.TeamID)
	var i GrantTeamAwardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Value,
		&i.Description,
		&i.Date,
	)
	return i, err
}

const grantUserAward = `-- name: GrantUserAward :one

INSERT INTO awards (user_id, team_id, type, name, description, value)
SELECT u.id, u.team_id, 'standard', 'manual adjustment', $1, $2
  FROM users u
 WHERE u.id = $3
RETURNING id, user_id, team_id, value, description, date
`

type GrantUserAwardParams struct {
	Reason *string
	Value  int32
	UserID int64
}

type GrantUserAwardRow struct {
	ID          int64
	UserID      int64
	TeamID      *int64
	Value       int32
	Description *string
	Date        pgtype.Timestamptz
}

// Manual awards: the admin write surface for out-of-band point adjustments — a cheating penalty,
// a live-dispute correction, a make-good. A manual award is always type='standard'; the ledger's
// other award types (hint_unlock, first_blood) are gameplay facts stamped under the challenge lock,
// never an admin decision. The scoreboard already sums awards.value alongside solves.value, so a
// single INSERT here moves standings and nothing on the read side changes.
// Users mode: the scoring account is the user. team_id rides along from the user's own row (NULL in
// users mode), exactly as the submit path writes both. Zero rows ⇒ no such user.
func (q *Queries) GrantUserAward(ctx context.Context, arg GrantUserAwardParams) (GrantUserAwardRow, error) {
	row := q.db.QueryRow(ctx, grantUserAward, arg.Reason, arg.Value, arg.UserID)
	var i GrantUserAwardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Value,
		&i.Description,
		&i.Date,
	)
	return i, err
}

const listTeamManualAwards = `-- name: ListTeamManualAwards :many
SELECT id, value, description, date
  FROM awards
 WHERE team_id = $1 AND type = 'standard'
 ORDER BY date DESC, id DESC
`

type ListTeamManualAwardsRow struct {
	ID          int64
	Value       int32
	Description *string
	Date        pgtype.Timestamptz
}

func (q *Queries) ListTeamManualAwards(ctx context.Context, teamID *int64) ([]ListTeamManualAwardsRow, error) {
	rows, err := q.db.Query(ctx, listTeamManualAwards, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamManualAwardsRow{}
	for rows.Next() {
		var i ListTeamManualAwardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Description,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserManualAwards = `-- name: ListUserManualAwards :many
SELECT id, value, description, date
  FROM awards
 WHERE user_id = $1 AND type = 'standard'
 ORDER BY date DESC, id DESC
`

type ListUserManualAwardsRow struct {
	ID          int64
	Value       int32
	Description *string
	Date        pgtype.Timestamptz
}

// Only type='standard' rows: hint spends and first-blood bonuses are gameplay facts, not admin
// adjustments, and must never appear in a revoke list.
func (q *Queries) ListUserManualAwards(ctx context.Context, userID int64) ([]ListUserManualAwardsRow, error) {
	rows, err := q.db.Query(ctx, listUserManualAwards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserManualAwardsRow{}
	for rows.Next() {
		var i ListUserManualAwardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Description,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeManualAward = `-- name: RevokeManualAward :one
WITH target AS (
    SELECT a.id AS award_id, a.type AS award_type FROM awards a WHERE a.id = $1
),
del AS (
    DELETE FROM awards
     WHERE awards.id = (SELECT t.award_id FROM target t WHERE t.award_type = 'standard')
    RETURNING awards.id AS deleted_id
)
SELECT COALESCE((SELECT t.award_type FROM target t), '')::text   AS found_type,
       COALESCE((SELECT d.deleted_id FROM del d), 0)::bigint      AS deleted_id
`

type RevokeManualAwardRow struct {
	FoundType string
	DeletedID int64
}

// A revoke is a real DELETE, never a mutation of a ledger row: scoreboard time-travel replays the
// ledger, so a revoked adjustment must read as never-having-happened, not as a rewritten fact. The
// WHERE type='standard' inside the delete is the guard — a hint_unlock or first_blood award is a
// gameplay fact and cannot be deleted through this path whatever id is passed. The surrounding CTE
// reads the row's type once so the caller can tell "no such award" from "refused: not manual",
// without a check-then-delete window: the delete's own predicate, not the read, is what protects the
// gameplay awards.
// COALESCE to non-null sentinels so the single result row scans cleanly whatever happened: an empty
// found_type means "no such award" (type is never empty), a zero deleted_id means "not deleted"
// (ids start at 1). The caller reads the two together to pick the outcome.
func (q *Queries) RevokeManualAward(ctx context.Context, id int64) (RevokeManualAwardRow, error) {
	row := q.db.QueryRow(ctx, revokeManualAward, id)
	var i RevokeManualAwardRow
	err := row.Scan(&i.FoundType, &i.DeletedID)
	return i, err
}
