// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package db

import (
	"context"
)

const ensureInstance = `-- name: EnsureInstance :one

INSERT INTO instance (id, user_mode, version)
VALUES (true, $1, $2)
ON CONFLICT (id) DO UPDATE
   SET user_mode = instance.user_mode
RETURNING user_mode
`

type EnsureInstanceParams struct {
	UserMode string
	Version  string
}

// The console bootstrap: the one path from an empty database to a playable instance.
//
// Two rows make an instance live — the instance singleton (which the scoring SQL keys on) and
// config.setup (which the route policy gates every request on, including /login). They are written
// in the same transaction as the first admin, so a live instance always has an admin and an
// instance with an admin is always live.
// The singleton, created once and never rewritten: user_mode is fixed at setup, and the immutability
// trigger says so. ON CONFLICT makes a re-run idempotent and hands back the mode actually in force —
// the no-op SET exists only so RETURNING fires on the conflict path, and it re-asserts the same
// user_mode so the trigger stays satisfied.
func (q *Queries) EnsureInstance(ctx context.Context, arg EnsureInstanceParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureInstance, arg.UserMode, arg.Version)
	var user_mode string
	err := row.Scan(&user_mode)
	return user_mode, err
}

const markSetupComplete = `-- name: MarkSetupComplete :exec
INSERT INTO config (key, value)
VALUES ('setup', 'true')
ON CONFLICT (key) DO UPDATE
   SET value = 'true', updated_at = now()
`

// Flips the instance live. Until this row says "true" the policy gate denies every route with
// setup-incomplete, so a fresh install has no front door. Idempotent: re-running the bootstrap on a
// live instance rewrites the same value.
func (q *Queries) MarkSetupComplete(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSetupComplete)
	return err
}
