// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brackets.sql

package db

import (
	"context"
)

const adminAssignTeamBracket = `-- name: AdminAssignTeamBracket :one
UPDATE teams SET bracket_id = $1 WHERE id = $2
RETURNING id, name, bracket_id
`

type AdminAssignTeamBracketParams struct {
	BracketID *int64
	TeamID    int64
}

type AdminAssignTeamBracketRow struct {
	ID        int64
	Name      string
	BracketID *int64
}

func (q *Queries) AdminAssignTeamBracket(ctx context.Context, arg AdminAssignTeamBracketParams) (AdminAssignTeamBracketRow, error) {
	row := q.db.QueryRow(ctx, adminAssignTeamBracket, arg.BracketID, arg.TeamID)
	var i AdminAssignTeamBracketRow
	err := row.Scan(&i.ID, &i.Name, &i.BracketID)
	return i, err
}

const adminAssignUserBracket = `-- name: AdminAssignUserBracket :one
UPDATE users SET bracket_id = $1 WHERE id = $2
RETURNING id, name, bracket_id
`

type AdminAssignUserBracketParams struct {
	BracketID *int64
	UserID    int64
}

type AdminAssignUserBracketRow struct {
	ID        int64
	Name      string
	BracketID *int64
}

// bracket_id NULL clears the assignment. Touching bracket_id does not trip the registration-cap
// trigger, which fires only on team_id.
func (q *Queries) AdminAssignUserBracket(ctx context.Context, arg AdminAssignUserBracketParams) (AdminAssignUserBracketRow, error) {
	row := q.db.QueryRow(ctx, adminAssignUserBracket, arg.BracketID, arg.UserID)
	var i AdminAssignUserBracketRow
	err := row.Scan(&i.ID, &i.Name, &i.BracketID)
	return i, err
}

const adminCreateBracket = `-- name: AdminCreateBracket :one
INSERT INTO brackets (name, description, applies_to)
VALUES ($1, $2, $3)
RETURNING id, name, description, applies_to
`

type AdminCreateBracketParams struct {
	Name        string
	Description *string
	AppliesTo   string
}

func (q *Queries) AdminCreateBracket(ctx context.Context, arg AdminCreateBracketParams) (Bracket, error) {
	row := q.db.QueryRow(ctx, adminCreateBracket, arg.Name, arg.Description, arg.AppliesTo)
	var i Bracket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AppliesTo,
	)
	return i, err
}

const adminDeleteBracket = `-- name: AdminDeleteBracket :execrows
DELETE FROM brackets WHERE id = $1
`

// Members are not blocked: bracket_id is ON DELETE SET NULL, so a delete simply unassigns them.
func (q *Queries) AdminDeleteBracket(ctx context.Context, bracketID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteBracket, bracketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateBracket = `-- name: AdminUpdateBracket :one
UPDATE brackets SET
    name        = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, name, description, applies_to
`

type AdminUpdateBracketParams struct {
	Name        *string
	Description *string
	BracketID   int64
}

// Partial update: an absent field keeps its value. applies_to is immutable — flipping it would
// silently strand every current member, whose account kind no longer matches.
func (q *Queries) AdminUpdateBracket(ctx context.Context, arg AdminUpdateBracketParams) (Bracket, error) {
	row := q.db.QueryRow(ctx, adminUpdateBracket, arg.Name, arg.Description, arg.BracketID)
	var i Bracket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AppliesTo,
	)
	return i, err
}

const getBracket = `-- name: GetBracket :one
SELECT id, name, description, applies_to FROM brackets WHERE id = $1
`

func (q *Queries) GetBracket(ctx context.Context, bracketID int64) (Bracket, error) {
	row := q.db.QueryRow(ctx, getBracket, bracketID)
	var i Bracket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AppliesTo,
	)
	return i, err
}

const listBrackets = `-- name: ListBrackets :many

SELECT id, name, description, applies_to FROM brackets
 WHERE ($1::text IS NULL OR applies_to = $1::text)
 ORDER BY id
`

// Brackets: named divisions that partition the scoreboard. A bracket is a filter over the one
// global ranking, never a separate scoring pool, so the standings query joins it as a WHERE
// predicate (scoreboard.sql). Membership is a single nullable FK on the account, so an account
// belongs to at most one bracket by construction, and deleting a bracket only nulls its members.
// All brackets, optionally scoped to one account kind. The public list passes the instance mode so
// a client only offers filters that can match; the admin list passes nothing and sees every row.
func (q *Queries) ListBrackets(ctx context.Context, appliesTo *string) ([]Bracket, error) {
	rows, err := q.db.Query(ctx, listBrackets, appliesTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bracket{}
	for rows.Next() {
		var i Bracket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AppliesTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
