// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChallengeForView = `-- name: GetChallengeForView :one
WITH mode AS (
    SELECT user_mode FROM instance
),
counts AS (
    SELECT s.challenge_id, count(*)::bigint AS n
      FROM solves s
      CROSS JOIN mode m
      LEFT JOIN users su ON su.id = s.user_id
      LEFT JOIN teams st ON st.id = s.team_id
     WHERE s.challenge_id = $4::bigint
       AND ($1::timestamptz IS NULL OR s.date < $1::timestamptz)
       AND CASE WHEN m.user_mode = 'teams'
                THEN st.hidden = false AND st.banned = false
                ELSE su.hidden = false AND su.banned = false
           END
     GROUP BY s.challenge_id
)
SELECT
    c.id, c.name, c.category, c.description, c.attribution, c.connection_info,
    c.type, c.function, c.max_attempts, c.state, c.requirements, c.flag_mode, c.next_id,
    (CASE
        WHEN $1::timestamptz IS NULL OR c.function = 'static' THEN c.value
        ELSE GREATEST(
            c.minimum::bigint,
            CASE c.function
                WHEN 'linear' THEN
                    c.initial::bigint - (c.decay::bigint * GREATEST(COALESCE(cnt.n, 0) - 1, 0)::bigint)
                ELSE
                    c.initial::bigint - (
                        ((c.initial - c.minimum)::bigint
                         * LEAST(GREATEST(COALESCE(cnt.n, 0) - 1, 0), c.decay)::bigint
                         * LEAST(GREATEST(COALESCE(cnt.n, 0) - 1, 0), c.decay)::bigint)
                        / (NULLIF(c.decay, 0)::bigint * NULLIF(c.decay, 0)::bigint)
                    )
            END
        )
     END)::int AS value,
    COALESCE(cnt.n, 0)::bigint AS solve_count,
    EXISTS (
        SELECT 1 FROM solves s
        CROSS JOIN mode m
        WHERE s.challenge_id = c.id
          AND CASE WHEN m.user_mode = 'teams'
                   THEN s.team_id = $2::bigint
                   ELSE s.user_id = $3::bigint
              END
    ) AS solved,
    -- Same prerequisite projection as the board: unmet means the caller withholds solvable
    -- content (or 404s the whole row when the anonymize flag hides it).
    NOT EXISTS (
        SELECT 1
          FROM jsonb_array_elements_text(c.requirements -> 'prerequisites') AS req(pid)
         WHERE NOT EXISTS (
            SELECT 1 FROM solves ps
            CROSS JOIN mode pm
            WHERE ps.challenge_id = req.pid::bigint
              AND CASE WHEN pm.user_mode = 'teams'
                       THEN ps.team_id = $2::bigint
                       ELSE ps.user_id = $3::bigint
                  END
         )
    ) AS prereqs_met
  FROM challenges c
  LEFT JOIN counts cnt ON cnt.challenge_id = c.id
 WHERE c.id = $4::bigint AND c.state = 'visible'
`

type GetChallengeForViewParams struct {
	Cutoff      pgtype.Timestamptz
	TeamID      *int64
	UserID      int64
	ChallengeID int64
}

type GetChallengeForViewRow struct {
	ID             int64
	Name           string
	Category       string
	Description    string
	Attribution    *string
	ConnectionInfo *string
	Type           string
	Function       string
	MaxAttempts    int32
	State          string
	Requirements   json.RawMessage
	FlagMode       string
	NextID         *int64
	Value          int32
	SolveCount     int64
	Solved         bool
	PrereqsMet     bool
}

// A single visible challenge with the same solve_count / solved projection as the board, clamped to
// the same freeze horizon — including `value`, which is invertible to the solve count on a dynamic
// challenge and so is quoted at the frozen count for a frozen viewer. See ListChallenges.
func (q *Queries) GetChallengeForView(ctx context.Context, arg GetChallengeForViewParams) (GetChallengeForViewRow, error) {
	row := q.db.QueryRow(ctx, getChallengeForView,
		arg.Cutoff,
		arg.TeamID,
		arg.UserID,
		arg.ChallengeID,
	)
	var i GetChallengeForViewRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.Function,
		&i.MaxAttempts,
		&i.State,
		&i.Requirements,
		&i.FlagMode,
		&i.NextID,
		&i.Value,
		&i.SolveCount,
		&i.Solved,
		&i.PrereqsMet,
	)
	return i, err
}

const listChallengeFiles = `-- name: ListChallengeFiles :many
SELECT id, name, size_bytes FROM files WHERE challenge_id = $1 ORDER BY id
`

type ListChallengeFilesRow struct {
	ID        int64
	Name      string
	SizeBytes int64
}

// The board shows the name and size; the download link is built from the id. location is the storage
// key and never leaves the server.
func (q *Queries) ListChallengeFiles(ctx context.Context, challengeID *int64) ([]ListChallengeFilesRow, error) {
	rows, err := q.db.Query(ctx, listChallengeFiles, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeFilesRow{}
	for rows.Next() {
		var i ListChallengeFilesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengeHints = `-- name: ListChallengeHints :many
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT
    h.id, h.title, h.cost, h.position,
    EXISTS (
        SELECT 1 FROM hint_unlocks hu
        CROSS JOIN mode m
        WHERE hu.hint_id = h.id
          AND CASE WHEN m.user_mode = 'teams'
                   THEN hu.team_id = $1::bigint
                   ELSE hu.user_id = $2::bigint
              END
    ) AS unlocked,
    -- Locked: a prerequisite hint has not been unlocked by this account, so UnlockHint will reject
    -- the purchase. A hint with no prerequisites has zero elements to check and is never locked.
    EXISTS (
        SELECT 1
          FROM jsonb_array_elements_text(h.requirements -> 'prerequisites') AS req(pid)
         WHERE NOT EXISTS (
            SELECT 1 FROM hint_unlocks phu
            CROSS JOIN mode pm
            WHERE phu.hint_id = req.pid::bigint
              AND CASE WHEN pm.user_mode = 'teams'
                       THEN phu.team_id = $1::bigint
                       ELSE phu.user_id = $2::bigint
                  END
         )
    ) AS locked
  FROM hints h
 WHERE h.challenge_id = $3
 ORDER BY h.position, h.id
`

type ListChallengeHintsParams struct {
	TeamID      *int64
	UserID      int64
	ChallengeID int64
}

type ListChallengeHintsRow struct {
	ID       int64
	Title    *string
	Cost     int32
	Position int32
	Unlocked bool
	Locked   bool
}

// Hint content is a purchase, never listed: the row carries the price and whether this account already
// paid it, and the content itself is delivered only by UnlockHint.
func (q *Queries) ListChallengeHints(ctx context.Context, arg ListChallengeHintsParams) ([]ListChallengeHintsRow, error) {
	rows, err := q.db.Query(ctx, listChallengeHints, arg.TeamID, arg.UserID, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeHintsRow{}
	for rows.Next() {
		var i ListChallengeHintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Cost,
			&i.Position,
			&i.Unlocked,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengeSolves = `-- name: ListChallengeSolves :many
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT
    COALESCE(u.name, t.name, '')     AS name,
    COALESCE(s.value, 0)::int        AS value,
    s.date,
    (COALESCE(u.id, t.id) IS NOT NULL)::boolean AS shown
  FROM challenges c
  CROSS JOIN mode m
  LEFT JOIN solves s
         ON s.challenge_id = c.id
        AND ($1::timestamptz IS NULL OR s.date < $1::timestamptz)
  LEFT JOIN users u
         ON m.user_mode = 'users' AND u.id = s.user_id AND u.hidden = false AND u.banned = false
  LEFT JOIN teams t
         ON m.user_mode = 'teams' AND t.id = s.team_id AND t.hidden = false AND t.banned = false
 WHERE c.id = $2 AND c.state = 'visible'
 ORDER BY s.date ASC, s.id ASC
`

type ListChallengeSolvesParams struct {
	Cutoff      pgtype.Timestamptz
	ChallengeID int64
}

type ListChallengeSolvesRow struct {
	Name  string
	Value int32
	Date  pgtype.Timestamptz
	Shown bool
}

// Who solved a challenge, oldest first, with cutoff (strict <, NULL = live) as the freeze horizon.
// The challenge is the driving table and EVERY solve/account predicate lives in an ON clause, so the
// two empty cases stay distinguishable in one round trip: zero rows means no visible challenge (the
// caller 404s), while `shown = false` marks a row the challenge kept but the projection must hide —
// no visible solve at all, or a hidden/banned solver filtered out. The caller drops the unshown rows.
func (q *Queries) ListChallengeSolves(ctx context.Context, arg ListChallengeSolvesParams) ([]ListChallengeSolvesRow, error) {
	rows, err := q.db.Query(ctx, listChallengeSolves, arg.Cutoff, arg.ChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengeSolvesRow{}
	for rows.Next() {
		var i ListChallengeSolvesRow
		if err := rows.Scan(
			&i.Name,
			&i.Value,
			&i.Date,
			&i.Shown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengeTags = `-- name: ListChallengeTags :many
SELECT value FROM tags WHERE challenge_id = $1 ORDER BY value
`

func (q *Queries) ListChallengeTags(ctx context.Context, challengeID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listChallengeTags, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallenges = `-- name: ListChallenges :many

WITH mode AS (
    SELECT user_mode FROM instance
),
counts AS (
    SELECT s.challenge_id, count(*)::bigint AS n
      FROM solves s
      CROSS JOIN mode m
      LEFT JOIN users su ON su.id = s.user_id
      LEFT JOIN teams st ON st.id = s.team_id
     WHERE ($1::timestamptz IS NULL OR s.date < $1::timestamptz)
       AND CASE WHEN m.user_mode = 'teams'
                THEN st.hidden = false AND st.banned = false
                ELSE su.hidden = false AND su.banned = false
           END
     GROUP BY s.challenge_id
)
SELECT
    c.id, c.name, c.category, c.function, c.state, c.requirements,
    (CASE
        WHEN $1::timestamptz IS NULL OR c.function = 'static' THEN c.value
        ELSE GREATEST(
            c.minimum::bigint,
            CASE c.function
                WHEN 'linear' THEN
                    c.initial::bigint - (c.decay::bigint * GREATEST(COALESCE(cnt.n, 0) - 1, 0)::bigint)
                ELSE
                    c.initial::bigint - (
                        ((c.initial - c.minimum)::bigint
                         * LEAST(GREATEST(COALESCE(cnt.n, 0) - 1, 0), c.decay)::bigint
                         * LEAST(GREATEST(COALESCE(cnt.n, 0) - 1, 0), c.decay)::bigint)
                        / (NULLIF(c.decay, 0)::bigint * NULLIF(c.decay, 0)::bigint)
                    )
            END
        )
     END)::int AS value,
    COALESCE(cnt.n, 0)::bigint AS solve_count,
    EXISTS (
        SELECT 1 FROM solves s
        CROSS JOIN mode m
        WHERE s.challenge_id = c.id
          AND CASE WHEN m.user_mode = 'teams'
                   THEN s.team_id = $2::bigint
                   ELSE s.user_id = $3::bigint
              END
    ) AS solved,
    -- Every prerequisite challenge in requirements.prerequisites has a solve by this account. A
    -- challenge with no prerequisites yields zero elements to check, so it is met by default. The
    -- caller decides whether an unmet challenge is hidden or shown locked, from the anonymize flag.
    NOT EXISTS (
        SELECT 1
          FROM jsonb_array_elements_text(c.requirements -> 'prerequisites') AS req(pid)
         WHERE NOT EXISTS (
            SELECT 1 FROM solves ps
            CROSS JOIN mode pm
            WHERE ps.challenge_id = req.pid::bigint
              AND CASE WHEN pm.user_mode = 'teams'
                       THEN ps.team_id = $2::bigint
                       ELSE ps.user_id = $3::bigint
                  END
         )
    ) AS prereqs_met
  FROM challenges c
  LEFT JOIN counts cnt ON cnt.challenge_id = c.id
 WHERE c.state = 'visible'
 ORDER BY c.category, c.position, c.id
`

type ListChallengesParams struct {
	Cutoff pgtype.Timestamptz
	TeamID *int64
	UserID int64
}

type ListChallengesRow struct {
	ID           int64
	Name         string
	Category     string
	Function     string
	State        string
	Requirements json.RawMessage
	Value        int32
	SolveCount   int64
	Solved       bool
	PrereqsMet   bool
}

// Read models for the challenge board and challenge detail. All account-scoped predicates resolve the
// mode from the instance singleton, the same way the hot path and scoreboard do, so "solved by me" and
// the solve count can never be computed against the wrong column.
// The visible board. solve_count and solved are scoped to visible accounts, matching the decay and
// first-blood exclusion, so a hidden admin test-solve does not inflate a challenge's count.
// cutoff is the freeze horizon (strict <, NULL = live): a frozen viewer's solve_count must not
// tick up on a post-freeze solve, or the count leaks what the frozen board hides.
//
// `value` is clamped to the same horizon, and that is not cosmetic. challenges.value is the current
// asking price: RecalcChallengeValue rewrites it on every solve with no time predicate, and it has
// to — the price a player is quoted must be the price they will pay. But the decay curve is public,
// deterministic and integer-exact, so the solve count is directly invertible from the value: a
// frozen viewer who snapshots the price and watches it drop has counted the solves the freeze exists
// to hide. Clamping the count and serving the live value hides the reading and publishes its
// derivative.
//
// So a frozen viewer is quoted the price at the FROZEN count. The curve is evaluated here, in SQL,
// from the same integer arithmetic RecalcChallengeValue writes — a second evaluation in Go is
// exactly how the two silently drift apart by a point. This costs the player nothing real: what a
// solve is actually worth is stamped on solves.value when it lands, not read off this column.
// One count per challenge, over visible accounts, clamped to the freeze horizon. solve_count and a
// frozen viewer's value are the same fact, so they are read from the same place and cannot disagree.
func (q *Queries) ListChallenges(ctx context.Context, arg ListChallengesParams) ([]ListChallengesRow, error) {
	rows, err := q.db.Query(ctx, listChallenges, arg.Cutoff, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChallengesRow{}
	for rows.Next() {
		var i ListChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Function,
			&i.State,
			&i.Requirements,
			&i.Value,
			&i.SolveCount,
			&i.Solved,
			&i.PrereqsMet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
