// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForImportAwards implements pgx.CopyFromSource.
type iteratorForImportAwards struct {
	rows                 []ImportAwardsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportAwards) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportAwards) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].TeamID,
		r.rows[0].Type,
		r.rows[0].ChallengeID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Value,
		r.rows[0].Category,
		r.rows[0].Icon,
		r.rows[0].Date,
	}, nil
}

func (r iteratorForImportAwards) Err() error {
	return nil
}

func (q *Queries) ImportAwards(ctx context.Context, arg []ImportAwardsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"awards"}, []string{"id", "user_id", "team_id", "type", "challenge_id", "name", "description", "value", "category", "icon", "date"}, &iteratorForImportAwards{rows: arg})
}

// iteratorForImportBrackets implements pgx.CopyFromSource.
type iteratorForImportBrackets struct {
	rows                 []ImportBracketsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportBrackets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportBrackets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].AppliesTo,
	}, nil
}

func (r iteratorForImportBrackets) Err() error {
	return nil
}

// Bulk restore path for the archive importer (internal/platform/importer).
//
// Every insert here is a :copyfrom: the loader streams whole translated tables through the binary
// COPY protocol inside one transaction, with explicit ids so the archive's identity is preserved.
// The transaction runs under `session_replication_role = replica`, so foreign keys and audit
// triggers are suppressed during the COPY and the tables can be loaded in any order; unique and
// check constraints stay live, which is what turns a conflicting archive into an atomic failure
// rather than a silently partial import. Dangling references are caught explicitly afterwards by
// the Count*WithoutParent probes below.
func (q *Queries) ImportBrackets(ctx context.Context, arg []ImportBracketsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"brackets"}, []string{"id", "name", "description", "applies_to"}, &iteratorForImportBrackets{rows: arg})
}

// iteratorForImportChallenges implements pgx.CopyFromSource.
type iteratorForImportChallenges struct {
	rows                 []ImportChallengesParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportChallenges) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportChallenges) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Category,
		r.rows[0].Description,
		r.rows[0].Attribution,
		r.rows[0].ConnectionInfo,
		r.rows[0].Type,
		r.rows[0].State,
		r.rows[0].Value,
		r.rows[0].Function,
		r.rows[0].Initial,
		r.rows[0].Minimum,
		r.rows[0].Decay,
		r.rows[0].MaxAttempts,
		r.rows[0].Logic,
		r.rows[0].Position,
		r.rows[0].NextID,
		r.rows[0].Requirements,
		r.rows[0].FlagMode,
		r.rows[0].FirstBlood,
		r.rows[0].FirstBloodBonus,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForImportChallenges) Err() error {
	return nil
}

func (q *Queries) ImportChallenges(ctx context.Context, arg []ImportChallengesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"challenges"}, []string{"id", "name", "category", "description", "attribution", "connection_info", "type", "state", "value", "function", "initial", "minimum", "decay", "max_attempts", "logic", "position", "next_id", "requirements", "flag_mode", "first_blood", "first_blood_bonus", "created_at", "updated_at"}, &iteratorForImportChallenges{rows: arg})
}

// iteratorForImportConfig implements pgx.CopyFromSource.
type iteratorForImportConfig struct {
	rows                 []ImportConfigParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportConfig) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportConfig) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Key,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForImportConfig) Err() error {
	return nil
}

func (q *Queries) ImportConfig(ctx context.Context, arg []ImportConfigParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"config"}, []string{"key", "value"}, &iteratorForImportConfig{rows: arg})
}

// iteratorForImportFiles implements pgx.CopyFromSource.
type iteratorForImportFiles struct {
	rows                 []ImportFilesParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportFiles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportFiles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Location,
		r.rows[0].Sha256sum,
		r.rows[0].SizeBytes,
		r.rows[0].ChallengeID,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForImportFiles) Err() error {
	return nil
}

func (q *Queries) ImportFiles(ctx context.Context, arg []ImportFilesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"files"}, []string{"id", "location", "sha256sum", "size_bytes", "challenge_id", "created_at"}, &iteratorForImportFiles{rows: arg})
}

// iteratorForImportFlags implements pgx.CopyFromSource.
type iteratorForImportFlags struct {
	rows                 []ImportFlagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportFlags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportFlags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChallengeID,
		r.rows[0].Type,
		r.rows[0].Content,
		r.rows[0].CaseInsensitive,
	}, nil
}

func (r iteratorForImportFlags) Err() error {
	return nil
}

func (q *Queries) ImportFlags(ctx context.Context, arg []ImportFlagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"flags"}, []string{"id", "challenge_id", "type", "content", "case_insensitive"}, &iteratorForImportFlags{rows: arg})
}

// iteratorForImportHints implements pgx.CopyFromSource.
type iteratorForImportHints struct {
	rows                 []ImportHintsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportHints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportHints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChallengeID,
		r.rows[0].Title,
		r.rows[0].Content,
		r.rows[0].Cost,
		r.rows[0].Requirements,
		r.rows[0].Position,
	}, nil
}

func (r iteratorForImportHints) Err() error {
	return nil
}

func (q *Queries) ImportHints(ctx context.Context, arg []ImportHintsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"hints"}, []string{"id", "challenge_id", "title", "content", "cost", "requirements", "position"}, &iteratorForImportHints{rows: arg})
}

// iteratorForImportSolves implements pgx.CopyFromSource.
type iteratorForImportSolves struct {
	rows                 []ImportSolvesParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportSolves) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportSolves) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].SubmissionID,
		r.rows[0].ChallengeID,
		r.rows[0].UserID,
		r.rows[0].TeamID,
		r.rows[0].Value,
		r.rows[0].Date,
	}, nil
}

func (r iteratorForImportSolves) Err() error {
	return nil
}

func (q *Queries) ImportSolves(ctx context.Context, arg []ImportSolvesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"solves"}, []string{"id", "submission_id", "challenge_id", "user_id", "team_id", "value", "date"}, &iteratorForImportSolves{rows: arg})
}

// iteratorForImportSubmissions implements pgx.CopyFromSource.
type iteratorForImportSubmissions struct {
	rows                 []ImportSubmissionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportSubmissions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportSubmissions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChallengeID,
		r.rows[0].UserID,
		r.rows[0].TeamID,
		r.rows[0].Type,
		r.rows[0].Provided,
		r.rows[0].Ip,
		r.rows[0].Date,
		r.rows[0].AttributedAccountID,
	}, nil
}

func (r iteratorForImportSubmissions) Err() error {
	return nil
}

func (q *Queries) ImportSubmissions(ctx context.Context, arg []ImportSubmissionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"submissions"}, []string{"id", "challenge_id", "user_id", "team_id", "type", "provided", "ip", "date", "attributed_account_id"}, &iteratorForImportSubmissions{rows: arg})
}

// iteratorForImportTags implements pgx.CopyFromSource.
type iteratorForImportTags struct {
	rows                 []ImportTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ChallengeID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForImportTags) Err() error {
	return nil
}

func (q *Queries) ImportTags(ctx context.Context, arg []ImportTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tags"}, []string{"id", "challenge_id", "value"}, &iteratorForImportTags{rows: arg})
}

// iteratorForImportTeams implements pgx.CopyFromSource.
type iteratorForImportTeams struct {
	rows                 []ImportTeamsParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportTeams) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportTeams) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Email,
		r.rows[0].PasswordHash,
		r.rows[0].Secret,
		r.rows[0].Website,
		r.rows[0].Affiliation,
		r.rows[0].Country,
		r.rows[0].BracketID,
		r.rows[0].CaptainID,
		r.rows[0].Hidden,
		r.rows[0].Banned,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForImportTeams) Err() error {
	return nil
}

func (q *Queries) ImportTeams(ctx context.Context, arg []ImportTeamsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teams"}, []string{"id", "name", "email", "password_hash", "secret", "website", "affiliation", "country", "bracket_id", "captain_id", "hidden", "banned", "created_at"}, &iteratorForImportTeams{rows: arg})
}

// iteratorForImportUsers implements pgx.CopyFromSource.
type iteratorForImportUsers struct {
	rows                 []ImportUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForImportUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForImportUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Email,
		r.rows[0].PasswordHash,
		r.rows[0].Role,
		r.rows[0].Secret,
		r.rows[0].Website,
		r.rows[0].Affiliation,
		r.rows[0].Country,
		r.rows[0].Language,
		r.rows[0].BracketID,
		r.rows[0].TeamID,
		r.rows[0].Hidden,
		r.rows[0].Banned,
		r.rows[0].Verified,
		r.rows[0].MustChangePassword,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForImportUsers) Err() error {
	return nil
}

func (q *Queries) ImportUsers(ctx context.Context, arg []ImportUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "name", "email", "password_hash", "role", "secret", "website", "affiliation", "country", "language", "bracket_id", "team_id", "hidden", "banned", "verified", "must_change_password", "created_at"}, &iteratorForImportUsers{rows: arg})
}
