// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens
   SET consumed_at = now()
 WHERE token_hash = $1
   AND purpose = $2
   AND consumed_at IS NULL
   AND expires_at > now()
RETURNING user_id
`

type ConsumeEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
}

// Single-use is enforced by this one statement: two concurrent consumers race on the row
// lock, and the loser sees consumed_at already set and gets zero rows. A SELECT-then-UPDATE
// would let both pass the check. Expiry lives in the WHERE clause so an expired token is
// indistinguishable from a bad one, on the database's clock, not the app server's.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, arg.TokenHash, arg.Purpose)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailToken = `-- name: CreateEmailToken :one

INSERT INTO email_tokens (token_hash, purpose, user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateEmailTokenParams struct {
	TokenHash []byte
	Purpose   string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

// Email verification and password reset tokens.
func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.TokenHash,
		arg.Purpose,
		arg.UserID,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :exec
DELETE FROM email_tokens WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailTokens)
	return err
}

const markUserVerified = `-- name: MarkUserVerified :exec
UPDATE users SET verified = true WHERE id = $1
`

func (q *Queries) MarkUserVerified(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markUserVerified, userID)
	return err
}
