// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fields.sql

package db

import (
	"context"
	"encoding/json"
)

const adminCreateField = `-- name: AdminCreateField :one


INSERT INTO fields (name, applies_to, field_type, description, required, public, editable, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, applies_to, field_type, description, required, public, editable, position
`

type AdminCreateFieldParams struct {
	Name        string
	AppliesTo   string
	FieldType   string
	Description *string
	Required    bool
	Public      bool
	Editable    bool
	Position    int32
}

// Custom registration fields: admin-defined profile questions (affiliation, eligibility, a consent
// checkbox) collected at sign-up. `fields` holds the definitions; `field_entries` holds one answer
// per (field, account), enforced by the one-owner CHECK and the per-field UNIQUE. A `required` field
// with no entry is what the login `profile_complete` gate reads as an incomplete profile, so the
// answer writes below are what keep that gate satisfiable.
// ── admin CRUD over the definitions ──────────────────────────────────────────────
func (q *Queries) AdminCreateField(ctx context.Context, arg AdminCreateFieldParams) (Field, error) {
	row := q.db.QueryRow(ctx, adminCreateField,
		arg.Name,
		arg.AppliesTo,
		arg.FieldType,
		arg.Description,
		arg.Required,
		arg.Public,
		arg.Editable,
		arg.Position,
	)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppliesTo,
		&i.FieldType,
		&i.Description,
		&i.Required,
		&i.Public,
		&i.Editable,
		&i.Position,
	)
	return i, err
}

const adminDeleteField = `-- name: AdminDeleteField :execrows
DELETE FROM fields WHERE id = $1
`

// Answers are cascaded, not blocked: field_entries.field_id is ON DELETE CASCADE. An answer is user
// data, not a gameplay ledger row — removing a retired question takes its answers with it, and the
// audit trigger on field_entries records each removed answer. execrows so the caller can tell "no
// such field" from a real delete.
func (q *Queries) AdminDeleteField(ctx context.Context, fieldID int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeleteField, fieldID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetField = `-- name: AdminGetField :one
SELECT id, name, applies_to, field_type, description, required, public, editable, position FROM fields WHERE id = $1
`

func (q *Queries) AdminGetField(ctx context.Context, fieldID int64) (Field, error) {
	row := q.db.QueryRow(ctx, adminGetField, fieldID)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppliesTo,
		&i.FieldType,
		&i.Description,
		&i.Required,
		&i.Public,
		&i.Editable,
		&i.Position,
	)
	return i, err
}

const adminListFields = `-- name: AdminListFields :many
SELECT id, name, applies_to, field_type, description, required, public, editable, position FROM fields ORDER BY applies_to, position, id
`

// Every field, in the order a form would render them: user fields then team fields, each by their
// authored position, id as the stable tie-break.
func (q *Queries) AdminListFields(ctx context.Context) ([]Field, error) {
	rows, err := q.db.Query(ctx, adminListFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Field{}
	for rows.Next() {
		var i Field
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AppliesTo,
			&i.FieldType,
			&i.Description,
			&i.Required,
			&i.Public,
			&i.Editable,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateField = `-- name: AdminUpdateField :one
UPDATE fields SET
    name        = COALESCE($1, name),
    description = CASE WHEN $2::bool THEN NULL
                      ELSE COALESCE($3, description) END,
    required    = COALESCE($4, required),
    public      = COALESCE($5, public),
    editable    = COALESCE($6, editable),
    position    = COALESCE($7, position)
WHERE id = $8
RETURNING id, name, applies_to, field_type, description, required, public, editable, position
`

type AdminUpdateFieldParams struct {
	Name             *string
	ClearDescription bool
	Description      *string
	Required         *bool
	Public           *bool
	Editable         *bool
	Position         *int32
	FieldID          int64
}

// Partial update: an absent argument keeps its value. field_type and applies_to are immutable —
// flipping either would reinterpret every stored answer (a text answer read as a bool, a user
// answer counted against a team gate), so they are create-only, exactly as a bracket's applies_to is.
func (q *Queries) AdminUpdateField(ctx context.Context, arg AdminUpdateFieldParams) (Field, error) {
	row := q.db.QueryRow(ctx, adminUpdateField,
		arg.Name,
		arg.ClearDescription,
		arg.Description,
		arg.Required,
		arg.Public,
		arg.Editable,
		arg.Position,
		arg.FieldID,
	)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AppliesTo,
		&i.FieldType,
		&i.Description,
		&i.Required,
		&i.Public,
		&i.Editable,
		&i.Position,
	)
	return i, err
}

const countFieldEntries = `-- name: CountFieldEntries :one
SELECT count(*) FROM field_entries WHERE field_id = $1
`

// How many answers a field carries, for the admin delete confirmation ("this removes N answers").
func (q *Queries) CountFieldEntries(ctx context.Context, fieldID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFieldEntries, fieldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserFieldEntry = `-- name: DeleteUserFieldEntry :exec
DELETE FROM field_entries WHERE field_id = $1 AND user_id = $2
`

type DeleteUserFieldEntryParams struct {
	FieldID int64
	UserID  *int64
}

// Clearing an optional, editable answer. A DELETE, not a value=null write: "no answer" has one
// representation (no row), which the gate and the reads all agree on.
func (q *Queries) DeleteUserFieldEntry(ctx context.Context, arg DeleteUserFieldEntryParams) error {
	_, err := q.db.Exec(ctx, deleteUserFieldEntry, arg.FieldID, arg.UserID)
	return err
}

const listPublicUserFieldAnswers = `-- name: ListPublicUserFieldAnswers :many
SELECT f.id, f.name, f.field_type, fe.value
  FROM fields f
  JOIN field_entries fe ON fe.field_id = f.id AND fe.user_id = $1::bigint
 WHERE f.applies_to = 'user' AND f.public
   AND fe.value IS NOT NULL AND fe.value <> 'null'::jsonb AND fe.value <> '""'::jsonb
 ORDER BY f.position, f.id
`

type ListPublicUserFieldAnswersRow struct {
	ID        int64
	Name      string
	FieldType string
	Value     json.RawMessage
}

// The public projection of a user's answers: only fields flagged public, only those actually
// answered. This is what a public profile view is allowed to show — a non-public answer never
// leaves this query.
func (q *Queries) ListPublicUserFieldAnswers(ctx context.Context, userID int64) ([]ListPublicUserFieldAnswersRow, error) {
	rows, err := q.db.Query(ctx, listPublicUserFieldAnswers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicUserFieldAnswersRow{}
	for rows.Next() {
		var i ListPublicUserFieldAnswersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FieldType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFieldDefs = `-- name: ListUserFieldDefs :many

SELECT id, name, field_type, description, required, public, editable, position
  FROM fields WHERE applies_to = 'user' ORDER BY position, id
`

type ListUserFieldDefsRow struct {
	ID          int64
	Name        string
	FieldType   string
	Description *string
	Required    bool
	Public      bool
	Editable    bool
	Position    int32
}

// ── user answers: registration + /me ─────────────────────────────────────────────
// The user-applicable field definitions, for the register-time validation and the /me editor. Read
// inside the registration transaction so required-field enforcement sees the fields as of the write.
func (q *Queries) ListUserFieldDefs(ctx context.Context) ([]ListUserFieldDefsRow, error) {
	rows, err := q.db.Query(ctx, listUserFieldDefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserFieldDefsRow{}
	for rows.Next() {
		var i ListUserFieldDefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FieldType,
			&i.Description,
			&i.Required,
			&i.Public,
			&i.Editable,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFieldsWithAnswers = `-- name: ListUserFieldsWithAnswers :many
SELECT f.id, f.name, f.field_type, f.description, f.required, f.public, f.editable, f.position,
       fe.value
  FROM fields f
  LEFT JOIN field_entries fe ON fe.field_id = f.id AND fe.user_id = $1::bigint
 WHERE f.applies_to = 'user'
 ORDER BY f.position, f.id
`

type ListUserFieldsWithAnswersRow struct {
	ID          int64
	Name        string
	FieldType   string
	Description *string
	Required    bool
	Public      bool
	Editable    bool
	Position    int32
	Value       json.RawMessage
}

// The /me view: every user field with this caller's current answer (NULL where unanswered), so the
// settings form can render both the fields still owed and the ones already filled in.
func (q *Queries) ListUserFieldsWithAnswers(ctx context.Context, userID int64) ([]ListUserFieldsWithAnswersRow, error) {
	rows, err := q.db.Query(ctx, listUserFieldsWithAnswers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserFieldsWithAnswersRow{}
	for rows.Next() {
		var i ListUserFieldsWithAnswersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FieldType,
			&i.Description,
			&i.Required,
			&i.Public,
			&i.Editable,
			&i.Position,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserFieldEntry = `-- name: UpsertUserFieldEntry :exec
INSERT INTO field_entries (field_id, user_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (field_id, user_id) DO UPDATE SET value = EXCLUDED.value
`

type UpsertUserFieldEntryParams struct {
	FieldID int64
	UserID  *int64
	Value   json.RawMessage
}

// One answer per (field, user), so a re-answer is an UPSERT on the UNIQUE(field_id, user_id), never
// a second row the profile-complete gate would have to pick a winner from.
func (q *Queries) UpsertUserFieldEntry(ctx context.Context, arg UpsertUserFieldEntryParams) error {
	_, err := q.db.Exec(ctx, upsertUserFieldEntry, arg.FieldID, arg.UserID, arg.Value)
	return err
}
