// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
)

const adminDeleteFile = `-- name: AdminDeleteFile :one
DELETE FROM files WHERE id = $1 RETURNING sha256sum
`

func (q *Queries) AdminDeleteFile(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, adminDeleteFile, id)
	var sha256sum []byte
	err := row.Scan(&sha256sum)
	return sha256sum, err
}

const adminInsertFile = `-- name: AdminInsertFile :one

INSERT INTO files (location, sha256sum, size_bytes, challenge_id, name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (location) DO NOTHING
RETURNING id, location, sha256sum, size_bytes, challenge_id, created_at, name
`

type AdminInsertFileParams struct {
	Location    string
	Sha256sum   []byte
	SizeBytes   int64
	ChallengeID *int64
	Name        string
}

// Challenge file attachments. The blob lives in object storage, content-addressed by sha256; these
// rows are the link from a challenge to a stored object plus its human-facing name.
// location is derived from the content address and is UNIQUE, so a concurrent upload of the same
// content under the same name collapses to one row instead of double-inserting. DO NOTHING (not a
// no-op UPDATE) so a deduped upload emits no spurious audit row; the caller reads the existing row.
func (q *Queries) AdminInsertFile(ctx context.Context, arg AdminInsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, adminInsertFile,
		arg.Location,
		arg.Sha256sum,
		arg.SizeBytes,
		arg.ChallengeID,
		arg.Name,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Sha256sum,
		&i.SizeBytes,
		&i.ChallengeID,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const countFilesBySha = `-- name: CountFilesBySha :one
SELECT count(*) FROM files WHERE sha256sum = $1
`

// Whether any other row still points at the same stored object, so a delete knows if the object is
// now unreferenced and safe to remove.
func (q *Queries) CountFilesBySha(ctx context.Context, sha256sum []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesBySha, sha256sum)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChallengeFileForDownload = `-- name: GetChallengeFileForDownload :one
SELECT f.id, f.name, f.sha256sum, f.size_bytes, c.state, c.id AS challenge_id
FROM files f
JOIN challenges c ON c.id = f.challenge_id
WHERE f.id = $1
`

type GetChallengeFileForDownloadRow struct {
	ID          int64
	Name        string
	Sha256sum   []byte
	SizeBytes   int64
	State       string
	ChallengeID int64
}

// The metadata a download needs, joined to its challenge so the handler can enforce that a hidden
// challenge's file is invisible to non-admins. A file with no owning challenge returns no row.
func (q *Queries) GetChallengeFileForDownload(ctx context.Context, id int64) (GetChallengeFileForDownloadRow, error) {
	row := q.db.QueryRow(ctx, getChallengeFileForDownload, id)
	var i GetChallengeFileForDownloadRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sha256sum,
		&i.SizeBytes,
		&i.State,
		&i.ChallengeID,
	)
	return i, err
}

const getFileByLocation = `-- name: GetFileByLocation :one
SELECT id, location, sha256sum, size_bytes, challenge_id, created_at, name FROM files WHERE location = $1
`

func (q *Queries) GetFileByLocation(ctx context.Context, location string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByLocation, location)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Sha256sum,
		&i.SizeBytes,
		&i.ChallengeID,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}
