// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignInstance = `-- name: AssignInstance :one
WITH picked AS (
    SELECT ci.id
      FROM challenge_instances ci
     WHERE ci.challenge_id = $1
       AND NOT EXISTS (SELECT 1 FROM flag_issues fi WHERE fi.instance_id = ci.id)
     ORDER BY ci.generation DESC, ci.id
     LIMIT 1
)
INSERT INTO flag_issues (challenge_id, account_id, instance_id)
SELECT $1, $2, picked.id FROM picked
ON CONFLICT (challenge_id, account_id) DO NOTHING
RETURNING instance_id
`

type AssignInstanceParams struct {
	ChallengeID int64
	AccountID   int64
}

// Hands the account an unissued instance from the pool.
//
// Two constraints back this up: PRIMARY KEY (challenge_id, account_id) makes it idempotent under
// concurrent first-views, and UNIQUE (instance_id) makes double-issue impossible — which is the
// constraint the entire anti-cheat property rests on.
//
// Callers must hold LockChallengePool. `FOR UPDATE ... SKIP LOCKED` alone does not make this
// safe, which is not obvious and was found the hard way: it locks the challenge_instances row, but
// the "is it issued?" test reads flag_issues — a different table. A transaction whose snapshot
// predates a concurrent commit still sees the instance as free, and by the time it takes the row
// lock the other transaction has already released it, so nothing is skipped. The loser then trips
// UNIQUE(instance_id), which ON CONFLICT does not catch (its target is the PK), and the player gets
// a 500 — at CTF start, when everyone opens the challenge at once.
//
// Newest generation first: re-uploading a pool bumps `generation`, and new issues should come from
// the new pool while old flag_issues rows keep pointing at their original instance, so submissions
// attributed under a previous generation stay attributable.
//
// Zero rows is ambiguous, and the caller must disambiguate by re-reading GetIssuedInstance:
//
//	(a) a row comes back  ⇒ a concurrent first-view won the race; use it (idempotent, correct).
//	(b) no row comes back ⇒ the pool is exhausted. Hard-fail the challenge — never fall back to a
//	    shared flag, which would silently destroy uniqueness for exactly the late registrants you
//	    are most suspicious of.
func (q *Queries) AssignInstance(ctx context.Context, arg AssignInstanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, assignInstance, arg.ChallengeID, arg.AccountID)
	var instance_id int64
	err := row.Scan(&instance_id)
	return instance_id, err
}

const getIssuedInstance = `-- name: GetIssuedInstance :one

SELECT ci.id, ci.challenge_id, ci.artifact_id, ci.vars, ci.generation, fi.assigned_at
  FROM flag_issues fi
  JOIN challenge_instances ci ON ci.id = fi.instance_id
 WHERE fi.challenge_id = $1
   AND fi.account_id = $2
`

type GetIssuedInstanceParams struct {
	ChallengeID int64
	AccountID   int64
}

type GetIssuedInstanceRow struct {
	ID          int64
	ChallengeID int64
	ArtifactID  *int64
	Vars        json.RawMessage
	Generation  int32
	AssignedAt  pgtype.Timestamptz
}

// Unique flags / challenge instances.
//
// An instance is a bundle: a flag (stored only as sha256), an optional artifact, and per-account
// template vars. Assignment is lazy — at the account's first access to the challenge. This is the
// only place in the product where reading a challenge mutates state.
// The account's own instance. This is the entire template context source: `vars` and the
// artifact, and nothing else. Note what is absent — there is no path from here to the plaintext flag,
// because the plaintext is never stored. Cross-account leakage is not prevented, it is
// unrepresentable.
// Challenge detail for flag_mode='unique' therefore varies by account: any cache must be keyed by
// (challenge_id, account_id). Design this in; do not discover it.
func (q *Queries) GetIssuedInstance(ctx context.Context, arg GetIssuedInstanceParams) (GetIssuedInstanceRow, error) {
	row := q.db.QueryRow(ctx, getIssuedInstance, arg.ChallengeID, arg.AccountID)
	var i GetIssuedInstanceRow
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.ArtifactID,
		&i.Vars,
		&i.Generation,
		&i.AssignedAt,
	)
	return i, err
}

const lockChallengePool = `-- name: LockChallengePool :exec
SELECT pg_advisory_xact_lock(hashtext('flag_issue:' || $1::bigint::text))
`

// Serializes issuance for one challenge. Must be called in the same transaction as AssignInstance,
// and as a separate statement — that is the whole point of it.
//
// Under READ COMMITTED a statement's snapshot is taken when the statement starts. If the lock were
// acquired inside AssignInstance itself, the NOT EXISTS there would still be reading the snapshot
// from before the wait, so it would not see the flag_issues row the previous holder just committed,
// and it would hand out an instance that is already taken. Taking the lock here, first, means
// AssignInstance's snapshot is created after the wait and sees everything.
//
// The lock is released on commit or rollback. Issuance is a first-view operation, not the submit
// path, so serializing it per challenge costs nothing that matters.
// hashtext over a namespaced string, so a bigserial challenge id is never truncated to int4.
func (q *Queries) LockChallengePool(ctx context.Context, challengeID int64) error {
	_, err := q.db.Exec(ctx, lockChallengePool, challengeID)
	return err
}

const lookupInstanceByHash = `-- name: LookupInstanceByHash :one
SELECT ci.id AS instance_id, ci.generation, fi.account_id AS attributed_account_id
  FROM challenge_instances ci
  LEFT JOIN flag_issues fi ON fi.instance_id = ci.id
 WHERE ci.challenge_id = $1
   AND ci.value_hash = $2
 ORDER BY (fi.account_id IS NULL), ci.generation DESC
 LIMIT 1
`

type LookupInstanceByHashParams struct {
	ChallengeID int64
	ValueHash   []byte
}

type LookupInstanceByHashRow struct {
	InstanceID          int64
	Generation          int32
	AttributedAccountID *int64
}

// The flag_mode='unique' compare path: sha256(provided) -> one indexed probe on
// challenge_instances(challenge_id, value_hash). O(1), not O(N_accounts) — and it never does a
// byte-wise comparison at all, so there is no per-byte timing channel to leak. Stronger than a
// constant-time compare, not a compromise.
//
// The LEFT JOIN is deliberate. A hit with `attributed_account_id IS NULL` is a valid pool flag that
// was never issued to anyone — the submission is still correct, and the NULL is itself an anti-cheat
// signal ("solved without ever fetching the artifact"). Correctness does not depend on who the flag
// was issued to; attribution does.
//
// If the returned account differs from the submitter's: accept the solve, silently. The player
// sees an ordinary `Correct!`. A detector that announces itself is not a detector — reject the flag
// and the cheater learns the platform tracks provenance, and adapts. The row surfaces in the admin
// review queue instead, and a human decides.
//
// Prefer an issued row over an unissued one when a hash exists across generations, so attribution
// survives a pool re-upload.
func (q *Queries) LookupInstanceByHash(ctx context.Context, arg LookupInstanceByHashParams) (LookupInstanceByHashRow, error) {
	row := q.db.QueryRow(ctx, lookupInstanceByHash, arg.ChallengeID, arg.ValueHash)
	var i LookupInstanceByHashRow
	err := row.Scan(&i.InstanceID, &i.Generation, &i.AttributedAccountID)
	return i, err
}

const poolStats = `-- name: PoolStats :many
SELECT c.id AS challenge_id,
       c.name,
       count(ci.id)::bigint            AS total,
       count(fi.instance_id)::bigint   AS issued
  FROM challenges c
  JOIN challenge_instances ci ON ci.challenge_id = c.id
  LEFT JOIN flag_issues fi    ON fi.instance_id = ci.id
 WHERE c.flag_mode = 'unique'
 GROUP BY c.id, c.name
 ORDER BY c.id
`

type PoolStatsRow struct {
	ChallengeID int64
	Name        string
	Total       int64
	Issued      int64
}

// The one number that must be right before the event starts. Pool exhaustion mid-CTF is a hard
// failure by design, and this gauge is what makes it preventable rather than merely loud.
func (q *Queries) PoolStats(ctx context.Context) ([]PoolStatsRow, error) {
	rows, err := q.db.Query(ctx, poolStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolStatsRow{}
	for rows.Next() {
		var i PoolStatsRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.Name,
			&i.Total,
			&i.Issued,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
