// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gameplay.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncorrectSubmissions = `-- name: CountIncorrectSubmissions :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT count(*)::bigint
  FROM submissions s
  CROSS JOIN mode m
 WHERE s.challenge_id = $1
   AND s.type = 'incorrect'
   AND CASE WHEN m.user_mode = 'teams'
            THEN s.team_id = $2::bigint
            ELSE s.user_id = $3::bigint
       END
`

type CountIncorrectSubmissionsParams struct {
	ChallengeID int64
	TeamID      *int64
	UserID      int64
}

// The max_attempts gate: wrong answers only, all-time, scoped to the account. A COUNT(*) over the
// append-only log rather than a counter row — there is no increment to lose.
func (q *Queries) CountIncorrectSubmissions(ctx context.Context, arg CountIncorrectSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncorrectSubmissions, arg.ChallengeID, arg.TeamID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSolvedPrerequisites = `-- name: CountSolvedPrerequisites :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT count(DISTINCT s.challenge_id)::bigint
  FROM solves s
  CROSS JOIN mode m
 WHERE s.challenge_id = ANY($1::bigint[])
   AND CASE WHEN m.user_mode = 'teams'
            THEN s.team_id = $2::bigint
            ELSE s.user_id = $3::bigint
       END
`

type CountSolvedPrerequisitesParams struct {
	Prerequisites []int64
	TeamID        *int64
	UserID        int64
}

// The prerequisite gate for the submit path. Counts how many of the given challenge ids this
// account has solved; the caller compares that against the number required. It is a plain indexed
// read with no lock, so a prerequisite-locked challenge is rejected before the challenge lock is
// ever taken — the wrong-answer fast path is untouched. The account model comes from `instance`.
func (q *Queries) CountSolvedPrerequisites(ctx context.Context, arg CountSolvedPrerequisitesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSolvedPrerequisites, arg.Prerequisites, arg.TeamID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSolvesExcluding = `-- name: CountSolvesExcluding :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT
    (SELECT count(*)
       FROM solves s
       CROSS JOIN mode m
       LEFT JOIN users u ON u.id = s.user_id
       LEFT JOIN teams t ON t.id = s.team_id
      WHERE s.challenge_id = $1
        AND s.id <> $2
        AND CASE WHEN m.user_mode = 'teams'
                 THEN t.hidden = false AND t.banned = false
                 ELSE u.hidden = false AND u.banned = false
            END
    )::bigint AS prior_solves,
    COALESCE(
        (SELECT CASE WHEN m.user_mode = 'teams'
                     THEN (SELECT t.hidden = false AND t.banned = false
                             FROM teams t WHERE t.id = $3::bigint)
                     ELSE (SELECT u.hidden = false AND u.banned = false
                             FROM users u WHERE u.id = $4::bigint)
                END
           FROM mode m),
        false
    )::boolean AS actor_eligible
`

type CountSolvesExcludingParams struct {
	ChallengeID    int64
	ExcludeSolveID int64
	TeamID         *int64
	UserID         int64
}

type CountSolvesExcludingRow struct {
	PriorSolves   int64
	ActorEligible bool
}

// First-blood detection, run under the challenge lock so it is exact, not a guess.
//
// Two columns, and first blood requires both: `prior_solves = 0 AND actor_eligible`.
// "Hidden and banned accounts cannot take first blood" is two rules, not one:
//
//	prior_solves   — hidden/banned solvers are excluded from the count, so a hidden admin
//	                 test-solving a challenge does not burn its first blood for the real solvers.
//	actor_eligible — the submitter is itself visible. The count alone silently gets this wrong:
//	                 for a hidden solver the count is 0 *by construction* (it excluded itself),
//	                 so `prior == 0` would hand the bonus to the hidden account.
//
// The account model comes from `instance`, not from a caller-supplied flag: user_mode is
// immutable and singleton, so reading it here costs one cached-page lookup and makes it impossible
// for a caller to count the wrong column.
func (q *Queries) CountSolvesExcluding(ctx context.Context, arg CountSolvesExcludingParams) (CountSolvesExcludingRow, error) {
	row := q.db.QueryRow(ctx, countSolvesExcluding,
		arg.ChallengeID,
		arg.ExcludeSolveID,
		arg.TeamID,
		arg.UserID,
	)
	var i CountSolvesExcludingRow
	err := row.Scan(&i.PriorSolves, &i.ActorEligible)
	return i, err
}

const getChallenge = `-- name: GetChallenge :one

SELECT id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at FROM challenges WHERE id = $1 AND state = 'visible'
`

// The submit hot path.
//
// The ordering that matters: the challenge lock is taken lazily, on the correct-flag path only.
// ~99% of submissions are wrong answers; a lock at the top of the transaction would serialize every
// wrong guess on the hottest challenge through one row — a queue where you meant to build a guard.
// Step 1 of submit: read the challenge with no lock. The flag compare happens against this.
// A hidden challenge is not playable; the guard lives in this read so no caller can forget it.
func (q *Queries) GetChallenge(ctx context.Context, challengeID int64) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, challengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChallengeFlags = `-- name: GetChallengeFlags :many

SELECT id, challenge_id, type, content, case_insensitive
  FROM flags
 WHERE challenge_id = $1
 ORDER BY id
`

// calling this on a static challenge is a no-op, not a corruption
// The flag_mode='static' compare path. Loaded on every submit of a static challenge — the
// hottest read in the product — and served entirely by flags_challenge_idx.
//
// Every flag is returned and the caller (domain/flags.MatchAny) evaluates ALL of them without
// short-circuiting: stopping at the first match would leak, through response latency, which flag
// matched. The whole point of crypto/subtle is lost if the loop above it branches on the result.
func (q *Queries) GetChallengeFlags(ctx context.Context, challengeID int64) ([]Flag, error) {
	rows, err := q.db.Query(ctx, getChallengeFlags, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flag{}
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.Type,
			&i.Content,
			&i.CaseInsensitive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMode = `-- name: GetUserMode :one
SELECT user_mode FROM instance
`

// The account model. Singleton and immutable (enforced by instance_user_mode_immutable), so this
// is one cached-page lookup. `instance` is created at setup; NO ROWS means the instance was never
// set up, which is a hard error and not a defaultable condition. Loud beats silent.
func (q *Queries) GetUserMode(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getUserMode)
	var user_mode string
	err := row.Scan(&user_mode)
	return user_mode, err
}

const insertAward = `-- name: InsertAward :one
INSERT INTO awards (user_id, team_id, type, challenge_id, name, description, value, category, icon)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, value, date
`

type InsertAwardParams struct {
	UserID      int64
	TeamID      *int64
	Type        string
	ChallengeID *int64
	Name        string
	Description *string
	Value       int32
	Category    *string
	Icon        *string
}

type InsertAwardRow struct {
	ID    int64
	Value int32
	Date  pgtype.Timestamptz
}

// The first-blood bonus and the hint-unlock charge are both awards (`value` may be negative).
// `awards_one_first_blood_per_challenge` (partial unique) prevents a double bonus even if the
// challenge lock is ever bypassed — by an admin grant, an import, or a psql session.
func (q *Queries) InsertAward(ctx context.Context, arg InsertAwardParams) (InsertAwardRow, error) {
	row := q.db.QueryRow(ctx, insertAward,
		arg.UserID,
		arg.TeamID,
		arg.Type,
		arg.ChallengeID,
		arg.Name,
		arg.Description,
		arg.Value,
		arg.Category,
		arg.Icon,
	)
	var i InsertAwardRow
	err := row.Scan(&i.ID, &i.Value, &i.Date)
	return i, err
}

const insertSolve = `-- name: InsertSolve :one
INSERT INTO solves (submission_id, challenge_id, user_id, team_id, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, value, date
`

type InsertSolveParams struct {
	SubmissionID *int64
	ChallengeID  int64
	UserID       int64
	TeamID       *int64
	Value        int32
}

type InsertSolveRow struct {
	ID    int64
	Value int32
	Date  pgtype.Timestamptz
}

// The duplicate check is the constraint, never a SELECT. Zero rows returned (pgx.ErrNoRows) is
// the `already_solved` signal; UNIQUE(challenge_id, user_id) / UNIQUE(challenge_id, team_id) is the
// arbiter.
//
// Not a data-modifying CTE. A CTE would insert the `submissions` row even when this insert
// conflicts, orphaning a type='correct' submission with no solve. Two statements, one transaction.
//
// @value is the per-solve snapshot: the asking price at the moment of the solve, read under the
// challenge lock and never recomputed. It is what makes the scoreboard append-only.
func (q *Queries) InsertSolve(ctx context.Context, arg InsertSolveParams) (InsertSolveRow, error) {
	row := q.db.QueryRow(ctx, insertSolve,
		arg.SubmissionID,
		arg.ChallengeID,
		arg.UserID,
		arg.TeamID,
		arg.Value,
	)
	var i InsertSolveRow
	err := row.Scan(&i.ID, &i.Value, &i.Date)
	return i, err
}

const insertSubmission = `-- name: InsertSubmission :one
INSERT INTO submissions (challenge_id, user_id, team_id, type, provided, ip, attributed_account_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, date
`

type InsertSubmissionParams struct {
	ChallengeID         int64
	UserID              int64
	TeamID              *int64
	Type                string
	Provided            string
	Ip                  *netip.Addr
	AttributedAccountID *int64
}

type InsertSubmissionRow struct {
	ID   int64
	Date pgtype.Timestamptz
}

// The append-only attempt log. `attributed_account_id` is the account the matched flag was
// issued to — NULL unless flag_mode='unique'. It is stamped here, never joined at query time, so
// sharing detection survives the instance being rotated, regenerated or deleted.
func (q *Queries) InsertSubmission(ctx context.Context, arg InsertSubmissionParams) (InsertSubmissionRow, error) {
	row := q.db.QueryRow(ctx, insertSubmission,
		arg.ChallengeID,
		arg.UserID,
		arg.TeamID,
		arg.Type,
		arg.Provided,
		arg.Ip,
		arg.AttributedAccountID,
	)
	var i InsertSubmissionRow
	err := row.Scan(&i.ID, &i.Date)
	return i, err
}

const lockAttemptCounter = `-- name: LockAttemptCounter :exec
SELECT pg_advisory_xact_lock(hashtextextended(concat_ws(':', $1::bigint, $2::bigint), 0))
`

type LockAttemptCounterParams struct {
	ChallengeID int64
	AccountID   int64
}

// The max_attempts gate is a check-then-act: count wrong answers, then insert one. Without a lock
// an account's own concurrent submissions all read the same stale count and every one slips past
// the cap, so a scripted client brute-forces past max_attempts. This advisory lock serializes THIS
// account's submissions to THIS challenge, making the count that follows exact. It is keyed per
// (challenge, account): different players never contend, so the challenge is not globally serialized
// and the wrong-answer hot path across players is untouched — this is not the challenge-row lock.
// Taken only when the challenge has a cap. A hash collision would merely make two unrelated pairs
// occasionally serialize, which is harmless. The xact lock auto-releases at commit or rollback.
func (q *Queries) LockAttemptCounter(ctx context.Context, arg LockAttemptCounterParams) error {
	_, err := q.db.Exec(ctx, lockAttemptCounter, arg.ChallengeID, arg.AccountID)
	return err
}

const lockChallengeForSubmit = `-- name: LockChallengeForSubmit :one
SELECT id, name, category, description, attribution, connection_info, type, state, value, function, initial, minimum, decay, max_attempts, logic, position, next_id, requirements, flag_mode, first_blood, first_blood_bonus, created_at, updated_at FROM challenges WHERE id = $1 AND state = 'visible' FOR NO KEY UPDATE
`

// Taken only after the flag compared correct. Under this lock the prior-solve count is exact, so
// first blood is decided inside the submitting transaction, and the decay recalc is exact for free.
// Re-read `value` from this row, not from GetChallenge: another solver may have decayed the
// challenge in between. Snapshot what the lock says, not what the optimistic read said.
//
// FOR NO KEY UPDATE: every INSERT into `submissions` and `solves` takes FOR KEY SHARE on this row
// through the FK, and plain FOR UPDATE conflicts with that — it would serialize every wrong guess
// behind the lock, one layer down. FOR NO KEY UPDATE lets the wrong-answer inserts sail through yet
// still conflicts with itself, so two correct paths serialize. We never UPDATE challenges.id, so
// the weaker lock costs nothing. Verified empirically.
func (q *Queries) LockChallengeForSubmit(ctx context.Context, challengeID int64) (Challenge, error) {
	row := q.db.QueryRow(ctx, lockChallengeForSubmit, challengeID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Attribution,
		&i.ConnectionInfo,
		&i.Type,
		&i.State,
		&i.Value,
		&i.Function,
		&i.Initial,
		&i.Minimum,
		&i.Decay,
		&i.MaxAttempts,
		&i.Logic,
		&i.Position,
		&i.NextID,
		&i.Requirements,
		&i.FlagMode,
		&i.FirstBlood,
		&i.FirstBloodBonus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recalcChallengeValue = `-- name: RecalcChallengeValue :exec
UPDATE challenges c
   SET value = GREATEST(
           c.minimum::bigint,
           CASE c.function
               WHEN 'linear' THEN
                   c.initial::bigint - (c.decay::bigint * GREATEST(cnt.n - 1, 0)::bigint)
               ELSE
                   c.initial::bigint - (
                       ((c.initial - c.minimum)::bigint
                        * LEAST(GREATEST(cnt.n - 1, 0), c.decay)::bigint
                        * LEAST(GREATEST(cnt.n - 1, 0), c.decay)::bigint)
                       / (NULLIF(c.decay, 0)::bigint * NULLIF(c.decay, 0)::bigint)
                   )
           END
       )::int,
       updated_at = now()
  FROM (
      SELECT count(*) AS n
        FROM solves s
        CROSS JOIN instance i
        LEFT JOIN users u ON u.id = s.user_id
        LEFT JOIN teams t ON t.id = s.team_id
       WHERE s.challenge_id = $1
         AND CASE WHEN i.user_mode = 'teams'
                  THEN t.hidden = false AND t.banned = false
                  ELSE u.hidden = false AND u.banned = false
             END
  ) AS cnt
 WHERE c.id = $1
   AND c.function <> 'static'
`

// One statement, never a read-modify-write — a read-modify-write is a last-writer-wins race, and
// this is only safe because the caller already holds the challenge lock.
//
// GREATEST(n - 1, 0): the first solver pays the max value. NULLIF(c.decay, 0): decay = 0 is already
// rejected by challenges_dynamic_params, but if it ever leaked in, the value collapses to `minimum`
// rather than dividing by zero. This updates only the current asking price shown on the board; it
// does not touch a single past solve — that is the whole point.
//
// Integer arithmetic, deliberately — do not "restore" the float8/CEIL version. The same curve runs
// in Go (scoring.Curve.ValueAt), and float8 does not round identically: for (initial=3901,
// minimum=205, decay=142) the true value at n = decay is 205, but float64 lands a hair high and
// CEIL lifts it to 206, so displayed and stored price would diverge for the rest of the event.
// Over the integers both engines do the same floor: init - floor(D*n^2/decay^2), D = initial - minimum.
//
// The two branches clamp n differently, and the difference is not cosmetic:
//
//	linear      — n is not clamped; its floor is the outer GREATEST. Clamping at decay would stop
//	              the decrement early and strand the challenge above `minimum`. The product is
//	              bigint because decay * n overflows int4 at real-world sizes.
//	logarithmic — n is clamped at decay: past the knee the curve is flat, so the clamp changes no
//	              result, and it is what bounds the squared product.
func (q *Queries) RecalcChallengeValue(ctx context.Context, challengeID int64) error {
	_, err := q.db.Exec(ctx, recalcChallengeValue, challengeID)
	return err
}
