// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAwardsWithoutParent = `-- name: CountAwardsWithoutParent :one
SELECT count(*) FROM awards a
    WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.id = a.user_id)
       OR (a.challenge_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM challenges c WHERE c.id = a.challenge_id))
`

func (q *Queries) CountAwardsWithoutParent(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAwardsWithoutParent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesWithoutChallenge = `-- name: CountFilesWithoutChallenge :one
SELECT count(*) FROM files f
    WHERE f.challenge_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM challenges c WHERE c.id = f.challenge_id)
`

func (q *Queries) CountFilesWithoutChallenge(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesWithoutChallenge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFlagsWithoutChallenge = `-- name: CountFlagsWithoutChallenge :one

SELECT count(*) FROM flags f
    LEFT JOIN challenges c ON c.id = f.challenge_id
    WHERE c.id IS NULL
`

// Referential-integrity probes. session_replication_role=replica ignores foreign keys during the
// COPY rather than deferring them, so re-enabling it validates nothing — a dangling reference has to
// be counted explicitly, still inside the transaction, so the whole restore rolls back on the first
// one found.
func (q *Queries) CountFlagsWithoutChallenge(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFlagsWithoutChallenge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHintsWithoutChallenge = `-- name: CountHintsWithoutChallenge :one
SELECT count(*) FROM hints h
    LEFT JOIN challenges c ON c.id = h.challenge_id
    WHERE c.id IS NULL
`

func (q *Queries) CountHintsWithoutChallenge(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHintsWithoutChallenge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSolvesWithoutParent = `-- name: CountSolvesWithoutParent :one
SELECT count(*) FROM solves s
    WHERE NOT EXISTS (SELECT 1 FROM challenges c WHERE c.id = s.challenge_id)
       OR NOT EXISTS (SELECT 1 FROM users u WHERE u.id = s.user_id)
       OR (s.submission_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM submissions sub WHERE sub.id = s.submission_id))
`

func (q *Queries) CountSolvesWithoutParent(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSolvesWithoutParent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmissionsWithoutParent = `-- name: CountSubmissionsWithoutParent :one
SELECT count(*) FROM submissions s
    WHERE NOT EXISTS (SELECT 1 FROM challenges c WHERE c.id = s.challenge_id)
       OR NOT EXISTS (SELECT 1 FROM users u WHERE u.id = s.user_id)
`

func (q *Queries) CountSubmissionsWithoutParent(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsWithoutParent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagsWithoutChallenge = `-- name: CountTagsWithoutChallenge :one
SELECT count(*) FROM tags t
    LEFT JOIN challenges c ON c.id = t.challenge_id
    WHERE c.id IS NULL
`

func (q *Queries) CountTagsWithoutChallenge(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsWithoutChallenge)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamsWithoutCaptain = `-- name: CountTeamsWithoutCaptain :one
SELECT count(*) FROM teams t
    WHERE t.captain_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM users u WHERE u.id = t.captain_id)
`

func (q *Queries) CountTeamsWithoutCaptain(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamsWithoutCaptain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersWithoutTeam = `-- name: CountUsersWithoutTeam :one
SELECT count(*) FROM users u
    WHERE u.team_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM teams t WHERE t.id = u.team_id)
`

func (q *Queries) CountUsersWithoutTeam(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithoutTeam)
	var count int64
	err := row.Scan(&count)
	return count, err
}

type ImportAwardsParams struct {
	ID          int64
	UserID      int64
	TeamID      *int64
	Type        string
	ChallengeID *int64
	Name        string
	Description *string
	Value       int32
	Category    *string
	Icon        *string
	Date        pgtype.Timestamptz
}

type ImportBracketsParams struct {
	ID          int64
	Name        string
	Description *string
	AppliesTo   string
}

type ImportChallengesParams struct {
	ID              int64
	Name            string
	Category        string
	Description     string
	Attribution     *string
	ConnectionInfo  *string
	Type            string
	State           string
	Value           int32
	Function        string
	Initial         *int32
	Minimum         *int32
	Decay           *int32
	MaxAttempts     int32
	Logic           string
	Position        int32
	NextID          *int64
	Requirements    json.RawMessage
	FlagMode        string
	FirstBlood      string
	FirstBloodBonus *int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ImportConfigParams struct {
	Key   string
	Value *string
}

type ImportFilesParams struct {
	ID          int64
	Location    string
	Sha256sum   []byte
	SizeBytes   int64
	ChallengeID *int64
	CreatedAt   pgtype.Timestamptz
}

type ImportFlagsParams struct {
	ID              int64
	ChallengeID     int64
	Type            string
	Content         string
	CaseInsensitive bool
}

type ImportHintsParams struct {
	ID           int64
	ChallengeID  int64
	Title        *string
	Content      string
	Cost         int32
	Requirements json.RawMessage
	Position     int32
}

type ImportSolvesParams struct {
	ID           int64
	SubmissionID *int64
	ChallengeID  int64
	UserID       int64
	TeamID       *int64
	Value        int32
	Date         pgtype.Timestamptz
}

type ImportSubmissionsParams struct {
	ID                  int64
	ChallengeID         int64
	UserID              int64
	TeamID              *int64
	Type                string
	Provided            string
	Ip                  *netip.Addr
	Date                pgtype.Timestamptz
	AttributedAccountID *int64
}

type ImportTagsParams struct {
	ID          int64
	ChallengeID int64
	Value       string
}

type ImportTeamsParams struct {
	ID           int64
	Name         string
	Email        *string
	PasswordHash string
	Secret       *string
	Website      *string
	Affiliation  *string
	Country      *string
	BracketID    *int64
	CaptainID    *int64
	Hidden       bool
	Banned       bool
	CreatedAt    pgtype.Timestamptz
}

type ImportUsersParams struct {
	ID                 int64
	Name               string
	Email              string
	PasswordHash       *string
	Role               string
	Secret             *string
	Website            *string
	Affiliation        *string
	Country            *string
	Language           *string
	BracketID          *int64
	TeamID             *int64
	Hidden             bool
	Banned             bool
	Verified           bool
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
}
