// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID          int64
	UserID      int64
	TokenHash   []byte
	Description *string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	ActorID     *int64
	Action      string
	TargetTable string
	TargetID    *int64
	Before      json.RawMessage
	After       json.RawMessage
	At          pgtype.Timestamptz
	Ip          *netip.Addr
}

type Award struct {
	ID          int64
	UserID      int64
	TeamID      *int64
	Type        string
	ChallengeID *int64
	Name        string
	Description *string
	Value       int32
	Category    *string
	Icon        *string
	Date        pgtype.Timestamptz
}

type Bracket struct {
	ID          int64
	Name        string
	Description *string
	AppliesTo   string
}

type Challenge struct {
	ID              int64
	Name            string
	Category        string
	Description     string
	Attribution     *string
	ConnectionInfo  *string
	Type            string
	State           string
	Value           int32
	Function        string
	Initial         *int32
	Minimum         *int32
	Decay           *int32
	MaxAttempts     int32
	Logic           string
	Position        int32
	NextID          *int64
	Requirements    json.RawMessage
	FlagMode        string
	FirstBlood      string
	FirstBloodBonus *int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ChallengeInstance struct {
	ID          int64
	ChallengeID int64
	ValueHash   []byte
	ArtifactID  *int64
	Vars        json.RawMessage
	Generation  int32
}

type Config struct {
	ID        int64
	Key       string
	Value     *string
	UpdatedAt pgtype.Timestamptz
}

type EmailToken struct {
	ID         int64
	TokenHash  []byte
	Purpose    string
	UserID     int64
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
}

type Field struct {
	ID          int64
	Name        string
	AppliesTo   string
	FieldType   string
	Description *string
	Required    bool
	Public      bool
	Editable    bool
	Position    int32
}

type FieldEntry struct {
	ID      int64
	FieldID int64
	UserID  *int64
	TeamID  *int64
	Value   json.RawMessage
}

type File struct {
	ID          int64
	Location    string
	Sha256sum   []byte
	SizeBytes   int64
	ChallengeID *int64
	CreatedAt   pgtype.Timestamptz
	Name        string
}

type Flag struct {
	ID              int64
	ChallengeID     int64
	Type            string
	Content         string
	CaseInsensitive bool
}

type FlagIssue struct {
	ChallengeID int64
	AccountID   int64
	InstanceID  int64
	AssignedAt  pgtype.Timestamptz
}

type Hint struct {
	ID           int64
	ChallengeID  int64
	Title        *string
	Content      string
	Cost         int32
	Requirements json.RawMessage
	Position     int32
}

type HintUnlock struct {
	ID      int64
	HintID  int64
	UserID  int64
	TeamID  *int64
	AwardID int64
	Date    pgtype.Timestamptz
}

type Instance struct {
	ID       bool
	UserMode string
	SetupAt  pgtype.Timestamptz
	Version  string
}

type Notification struct {
	ID      int64
	Title   string
	Content string
	Date    pgtype.Timestamptz
}

type Page struct {
	ID           int64
	Route        string
	Title        string
	Content      string
	Format       string
	Draft        bool
	AuthRequired bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RateLimit struct {
	Bucket      string
	WindowStart pgtype.Timestamptz
	N           int32
}

type Session struct {
	IDHash        []byte
	UserID        int64
	PwFingerprint []byte
	CsrfToken     string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	LastSeen      pgtype.Timestamptz
}

type Solf struct {
	ID           int64
	SubmissionID *int64
	ChallengeID  int64
	UserID       int64
	TeamID       *int64
	Value        int32
	Date         pgtype.Timestamptz
}

type Submission struct {
	ID                  int64
	ChallengeID         int64
	UserID              int64
	TeamID              *int64
	Type                string
	Provided            string
	Ip                  *netip.Addr
	Date                pgtype.Timestamptz
	AttributedAccountID *int64
}

type Tag struct {
	ID          int64
	ChallengeID int64
	Value       string
}

type Task struct {
	ID        int64
	Kind      string
	State     string
	Progress  int32
	Detail    *string
	Error     *string
	CreatedBy *int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Team struct {
	ID           int64
	Name         string
	Email        *string
	PasswordHash string
	Secret       *string
	Website      *string
	Affiliation  *string
	Country      *string
	BracketID    *int64
	CaptainID    *int64
	Hidden       bool
	Banned       bool
	CreatedAt    pgtype.Timestamptz
}

type Tracking struct {
	ID     int64
	UserID int64
	Ip     netip.Addr
	Date   pgtype.Timestamptz
}

type User struct {
	ID                 int64
	Name               string
	Email              string
	PasswordHash       *string
	Role               string
	Secret             *string
	Website            *string
	Affiliation        *string
	Country            *string
	Language           *string
	BracketID          *int64
	TeamID             *int64
	Hidden             bool
	Banned             bool
	Verified           bool
	MustChangePassword bool
	CreatedAt          pgtype.Timestamptz
	PendingEmail       *string
}
