// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotification = `-- name: GetNotification :one
SELECT id, title, content, date
FROM notifications
WHERE id = $1
`

// The listen pump carries only an id in the 8 kB NOTIFY payload and reloads the row here, so the
// content it fans out is the committed row rather than a copy that could disagree with it.
func (q *Queries) GetNotification(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Date,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (title, content)
VALUES ($1, $2)
RETURNING id, title, content, date
`

type InsertNotificationParams struct {
	Title   string
	Content string
}

// Notifications are broadcast, not addressed: every row goes to every client, so there is no
// targeting column to filter on. The interesting property lives in the service, where the INSERT
// and the pg_notify that wakes the listeners share one transaction — a row that persists is a row
// that was announced, and a rolled-back write never wakes the fleet.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification, arg.Title, arg.Content)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Date,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, title, content, date, COUNT(*) OVER () AS total
FROM notifications
ORDER BY date DESC, id DESC
LIMIT $2::int OFFSET $1::int
`

type ListNotificationsParams struct {
	Off int32
	Lim int32
}

type ListNotificationsRow struct {
	ID      int64
	Title   string
	Content string
	Date    pgtype.Timestamptz
	Total   int64
}

// COUNT(*) OVER () returns the total in the same round trip rather than a second query. Ordered by
// a total key (date then id) so pages are stable when two rows share a timestamp.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Date,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentNotifications = `-- name: RecentNotifications :many
SELECT id, title, content, date
FROM notifications
ORDER BY date DESC, id DESC
LIMIT $1::int
`

// Replay on connect: newest first, capped, so a client that just opened the stream is caught up
// without paging. The caller emits them oldest-first.
func (q *Queries) RecentNotifications(ctx context.Context, lim int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, recentNotifications, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
