// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCreatePage = `-- name: AdminCreatePage :one
INSERT INTO pages (route, title, content, format, draft, auth_required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, route, title, content, format, draft, auth_required, created_at, updated_at
`

type AdminCreatePageParams struct {
	Route        string
	Title        string
	Content      string
	Format       string
	Draft        bool
	AuthRequired bool
}

func (q *Queries) AdminCreatePage(ctx context.Context, arg AdminCreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, adminCreatePage,
		arg.Route,
		arg.Title,
		arg.Content,
		arg.Format,
		arg.Draft,
		arg.AuthRequired,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.Draft,
		&i.AuthRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminDeletePage = `-- name: AdminDeletePage :execrows
DELETE FROM pages WHERE id = $1
`

func (q *Queries) AdminDeletePage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, adminDeletePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminGetPage = `-- name: AdminGetPage :one
SELECT id, route, title, content, format, draft, auth_required, created_at, updated_at FROM pages WHERE id = $1
`

func (q *Queries) AdminGetPage(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRow(ctx, adminGetPage, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.Draft,
		&i.AuthRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListPages = `-- name: AdminListPages :many
SELECT id, route, title, format, draft, auth_required, created_at, updated_at
  FROM pages
 ORDER BY title
`

type AdminListPagesRow struct {
	ID           int64
	Route        string
	Title        string
	Format       string
	Draft        bool
	AuthRequired bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// The admin index: every page, draft or not. Content is omitted — the list does not need the body,
// and a rules page is large.
func (q *Queries) AdminListPages(ctx context.Context) ([]AdminListPagesRow, error) {
	rows, err := q.db.Query(ctx, adminListPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPagesRow{}
	for rows.Next() {
		var i AdminListPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Route,
			&i.Title,
			&i.Format,
			&i.Draft,
			&i.AuthRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdatePage = `-- name: AdminUpdatePage :one
UPDATE pages SET
    route         = COALESCE($1, route),
    title         = COALESCE($2, title),
    content       = COALESCE($3, content),
    format        = COALESCE($4, format),
    draft         = COALESCE($5, draft),
    auth_required = COALESCE($6, auth_required),
    updated_at    = now()
WHERE id = $7
RETURNING id, route, title, content, format, draft, auth_required, created_at, updated_at
`

type AdminUpdatePageParams struct {
	Route        *string
	Title        *string
	Content      *string
	Format       *string
	Draft        *bool
	AuthRequired *bool
	ID           int64
}

// Partial update: an absent field keeps its value. Changing route to one already taken trips
// pages_route_key, which the service turns into a 409.
func (q *Queries) AdminUpdatePage(ctx context.Context, arg AdminUpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, adminUpdatePage,
		arg.Route,
		arg.Title,
		arg.Content,
		arg.Format,
		arg.Draft,
		arg.AuthRequired,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.Draft,
		&i.AuthRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByRoute = `-- name: GetPageByRoute :one

SELECT id, route, title, content, format, draft, auth_required, created_at, updated_at FROM pages WHERE route = $1
`

// CMS pages: the rules/FAQ/sponsors content. The public reads are keyed by the URL slug; the admin
// CRUD is keyed by id. Route uniqueness is the table's (pages_route_key), so a duplicate slug is a
// constraint violation the service maps to a 409, never a check-then-insert.
// The public read. Returns the row whatever its draft/auth_required flags — the policy gate decides
// visibility against them, so the query must not pre-filter drafts or the gate could never be tested.
func (q *Queries) GetPageByRoute(ctx context.Context, route string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByRoute, route)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Route,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.Draft,
		&i.AuthRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedPages = `-- name: ListPublishedPages :many
SELECT id, route, title, auth_required
  FROM pages
 WHERE draft = false
 ORDER BY title
`

type ListPublishedPagesRow struct {
	ID           int64
	Route        string
	Title        string
	AuthRequired bool
}

// The public list behind the nav: published pages only, drafts never appear. auth_required rides
// along so the client can mark a link that will ask an anonymous visitor to log in.
func (q *Queries) ListPublishedPages(ctx context.Context) ([]ListPublishedPagesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPagesRow{}
	for rows.Next() {
		var i ListPublishedPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Route,
			&i.Title,
			&i.AuthRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
