// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFileOnce = `-- name: InsertFileOnce :one

INSERT INTO files (location, sha256sum, size_bytes, challenge_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (location) DO UPDATE
   SET sha256sum = EXCLUDED.sha256sum
RETURNING id, location, sha256sum, size_bytes, challenge_id, created_at
`

type InsertFileOnceParams struct {
	Location    string
	Sha256sum   []byte
	SizeBytes   int64
	ChallengeID *int64
}

type InsertFileOnceRow struct {
	ID          int64
	Location    string
	Sha256sum   []byte
	SizeBytes   int64
	ChallengeID *int64
	CreatedAt   pgtype.Timestamptz
}

// Platform-level writes whose only interesting property is that they are race-free:
// a unique constraint plus ON CONFLICT, never a check-then-insert.
// ON CONFLICT DO UPDATE, not DO NOTHING: a re-upload of a byte-identical object must hand
// back the existing id, not ErrNoRows. `location` is content-addressed upstream, so the
// SET is a no-op write that exists only to make RETURNING fire on the conflict path.
func (q *Queries) InsertFileOnce(ctx context.Context, arg InsertFileOnceParams) (InsertFileOnceRow, error) {
	row := q.db.QueryRow(ctx, insertFileOnce,
		arg.Location,
		arg.Sha256sum,
		arg.SizeBytes,
		arg.ChallengeID,
	)
	var i InsertFileOnceRow
	err := row.Scan(
		&i.ID,
		&i.Location,
		&i.Sha256sum,
		&i.SizeBytes,
		&i.ChallengeID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTracking = `-- name: UpsertTracking :one
INSERT INTO tracking (user_id, ip)
VALUES ($1, $2)
ON CONFLICT (user_id, ip) DO UPDATE
   SET date = now()
RETURNING id, user_id, ip, date
`

type UpsertTrackingParams struct {
	UserID int64
	Ip     netip.Addr
}

// Runs on every authenticated request. One idempotent statement that cannot raise:
// there is no error path left to mishandle.
func (q *Queries) UpsertTracking(ctx context.Context, arg UpsertTrackingParams) (Tracking, error) {
	row := q.db.QueryRow(ctx, upsertTracking, arg.UserID, arg.Ip)
	var i Tracking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ip,
		&i.Date,
	)
	return i, err
}
