// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPublicProfile = `-- name: GetUserPublicProfile :one

SELECT u.id, u.name, u.website, u.affiliation, u.country, u.created_at,
       u.bracket_id, b.name AS bracket_name,
       (COALESCE((SELECT sum(s.value) FROM solves s
                   WHERE s.user_id = u.id
                     AND ($1::timestamptz IS NULL
                          OR s.date < $1::timestamptz)), 0)
      + COALESCE((SELECT sum(a.value) FROM awards a
                   WHERE a.user_id = u.id
                     AND ($1::timestamptz IS NULL
                          OR a.date < $1::timestamptz)), 0))::bigint AS score
  FROM users u
  LEFT JOIN brackets b ON b.id = u.bracket_id
 WHERE u.id = $2
   AND ($3::boolean OR (u.hidden = false AND u.banned = false))
`

type GetUserPublicProfileParams struct {
	Cutoff pgtype.Timestamptz
	UserID int64
	Admin  bool
}

type GetUserPublicProfileRow struct {
	ID          int64
	Name        string
	Website     *string
	Affiliation *string
	Country     *string
	CreatedAt   pgtype.Timestamptz
	BracketID   *int64
	BracketName *string
	Score       int64
}

// Public account profiles: a user's page, gated exactly like the scoreboard and the team page.
// A hidden or banned user 404s to the public and is visible to an admin — the `admin` flag is the
// only thing that widens the row, mirroring the scoreboard. The score sums the stamped solves.user_id
// and awards.user_id ledgers under the caller's freeze horizon (cutoff strict `<`, NULL = live), so a
// public page served during a freeze hands over the frozen standing, one account at a time.
func (q *Queries) GetUserPublicProfile(ctx context.Context, arg GetUserPublicProfileParams) (GetUserPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicProfile, arg.Cutoff, arg.UserID, arg.Admin)
	var i GetUserPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.CreatedAt,
		&i.BracketID,
		&i.BracketName,
		&i.Score,
	)
	return i, err
}

const listUserSolves = `-- name: ListUserSolves :many
SELECT c.id AS challenge_id, c.name AS challenge_name, c.category,
       s.value::int AS value, s.date
  FROM solves s
  JOIN challenges c ON c.id = s.challenge_id
 WHERE s.user_id = $1
   AND c.state = 'visible'
   AND ($2::timestamptz IS NULL OR s.date < $2::timestamptz)
 ORDER BY s.date DESC, s.id DESC
`

type ListUserSolvesParams struct {
	UserID int64
	Cutoff pgtype.Timestamptz
}

type ListUserSolvesRow struct {
	ChallengeID   int64
	ChallengeName string
	Category      string
	Value         int32
	Date          pgtype.Timestamptz
}

// The account's solved challenges, newest first, under the same freeze horizon as the score above.
// Only visible challenges are listed: the total score sums the whole ledger (matching the board), but
// naming a hidden challenge here would leak its existence, so the itemised history hides it just as
// the per-challenge solve list does.
func (q *Queries) ListUserSolves(ctx context.Context, arg ListUserSolvesParams) ([]ListUserSolvesRow, error) {
	rows, err := q.db.Query(ctx, listUserSolves, arg.UserID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSolvesRow{}
	for rows.Next() {
		var i ListUserSolvesRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.ChallengeName,
			&i.Category,
			&i.Value,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
