// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ── tags ──────────────────────────────────────────────────────────────────────────
	//
	// A tag is a (challenge_id, value) row; the same value on many challenges is one tag with several
	// uses. These statements treat a tag by its value, which is the unit an operator manages.
	// No pre-checks: UNIQUE(challenge_id, value) refuses the duplicate and the FK refuses a missing
	// challenge, each mapped by the caller. A pre-read would just be the same check with a race in it.
	AdminAddTag(ctx context.Context, arg AdminAddTagParams) (Tag, error)
	AdminAssignTeamBracket(ctx context.Context, arg AdminAssignTeamBracketParams) (AdminAssignTeamBracketRow, error)
	// bracket_id NULL clears the assignment. Touching bracket_id does not trip the registration-cap
	// trigger, which fires only on team_id.
	AdminAssignUserBracket(ctx context.Context, arg AdminAssignUserBracketParams) (AdminAssignUserBracketRow, error)
	// Flag counts for the flag_mode switch guards: total decides whether a switch to static would leave
	// every submission erroring on an empty flag set, and the regex count decides whether a switch to
	// unique would strand a pattern that cannot be pool-issued.
	AdminChallengeFlagStats(ctx context.Context, challengeID int64) (AdminChallengeFlagStatsRow, error)
	// Whether the challenge has any recorded solve. A flag_mode switch is refused while this is nonzero:
	// the anti-cheat unissued-solve detector is a date-blind anti-join, so flipping static→unique
	// mid-event would report every legitimate prior solver as an unissued solve.
	AdminCountChallengeSolves(ctx context.Context, challengeID int64) (int64, error)
	AdminCountOtherAdmins(ctx context.Context, userID int64) (int64, error)
	AdminCountTagUses(ctx context.Context, value string) (int64, error)
	AdminCreateBracket(ctx context.Context, arg AdminCreateBracketParams) (Bracket, error)
	// Admin mutations. Every statement here runs inside a transaction that has stamped the acting
	// admin into app.actor_id, so the capture triggers write the audit row in the same transaction
	// as the change itself.
	// ── challenges ──────────────────────────────────────────────────────────────────
	AdminCreateChallenge(ctx context.Context, arg AdminCreateChallengeParams) (Challenge, error)
	// Custom registration fields: admin-defined profile questions (affiliation, eligibility, a consent
	// checkbox) collected at sign-up. `fields` holds the definitions; `field_entries` holds one answer
	// per (field, account), enforced by the one-owner CHECK and the per-field UNIQUE. A `required` field
	// with no entry is what the login `profile_complete` gate reads as an incomplete profile, so the
	// answer writes below are what keep that gate satisfiable.
	// ── admin CRUD over the definitions ──────────────────────────────────────────────
	AdminCreateField(ctx context.Context, arg AdminCreateFieldParams) (Field, error)
	AdminCreatePage(ctx context.Context, arg AdminCreatePageParams) (Page, error)
	// Same arbiters as the self-serve create: teams_name_uniq and the num_teams caps trigger decide
	// on the INSERT itself, never in a prior check. captain_id stays NULL — an admin-provisioned team
	// is captainless until its first member joins and adopts it.
	AdminCreateTeam(ctx context.Context, arg AdminCreateTeamParams) (AdminCreateTeamRow, error)
	// Members are not blocked: bracket_id is ON DELETE SET NULL, so a delete simply unassigns them.
	AdminDeleteBracket(ctx context.Context, bracketID int64) (int64, error)
	// Flags, hints, tags and file links cascade. Ledger rows (solves, submissions, awards, hint
	// unlocks, issued flags) RESTRICT: a challenge with recorded history cannot be deleted, and the
	// caller maps that violation to a conflict.
	AdminDeleteChallenge(ctx context.Context, challengeID int64) (int64, error)
	// Answers are cascaded, not blocked: field_entries.field_id is ON DELETE CASCADE. An answer is user
	// data, not a gameplay ledger row — removing a retired question takes its answers with it, and the
	// audit trigger on field_entries records each removed answer. execrows so the caller can tell "no
	// such field" from a real delete.
	AdminDeleteField(ctx context.Context, fieldID int64) (int64, error)
	AdminDeleteFile(ctx context.Context, id int64) ([]byte, error)
	AdminDeleteFlag(ctx context.Context, arg AdminDeleteFlagParams) (int64, error)
	AdminDeleteHint(ctx context.Context, arg AdminDeleteHintParams) (int64, error)
	AdminDeletePage(ctx context.Context, id int64) (int64, error)
	AdminDeleteTag(ctx context.Context, value string) (int64, error)
	// Membership is the WHERE, not a prior read: zero rows means the user was not on that team by the
	// time this ran, and the caller turns that into a named refusal instead of a silent success.
	//
	// Unlike the captain's kick this carries no "team has never scored" guard, and that is deliberate.
	// Every ledger row stamps team_id when it is written, so points already earned stay credited to the
	// team that earned them no matter who leaves afterwards. Fixing a roster mid-event is the entire
	// reason this statement exists; the audit trigger records who did it.
	AdminDetachMember(ctx context.Context, arg AdminDetachMemberParams) (int64, error)
	// Existence probe for artifact validation, scoped to the challenge: an artifact_id that is not a
	// file of this challenge filters out here, and the caller names it as invalid.
	AdminFilterChallengeFileIDs(ctx context.Context, arg AdminFilterChallengeFileIDsParams) ([]int64, error)
	// Existence probe for prerequisite validation: the caller diffs the echo against its input to name
	// the ids that do not exist.
	AdminFilterChallengeIDs(ctx context.Context, ids []int64) ([]int64, error)
	// Existence probe for hint-prerequisite validation, scoped to the challenge: a cross-challenge id
	// filters out here and is reported by the caller the same as one that does not exist at all.
	AdminFilterHintIDs(ctx context.Context, arg AdminFilterHintIDsParams) ([]int64, error)
	// Set-only: the clear belongs to the password change itself, in the same statement as the new
	// hash, so the order can never discharge without the password that satisfies it.
	AdminForcePasswordChange(ctx context.Context, userID int64) (AdminForcePasswordChangeRow, error)
	AdminGetChallenge(ctx context.Context, challengeID int64) (Challenge, error)
	AdminGetField(ctx context.Context, fieldID int64) (Field, error)
	AdminGetFlag(ctx context.Context, arg AdminGetFlagParams) (Flag, error)
	AdminGetPage(ctx context.Context, id int64) (Page, error)
	AdminGetTeam(ctx context.Context, teamID int64) (AdminGetTeamRow, error)
	AdminGetUser(ctx context.Context, userID int64) (AdminGetUserRow, error)
	// Challenge file attachments. The blob lives in object storage, content-addressed by sha256; these
	// rows are the link from a challenge to a stored object plus its human-facing name.
	// location is derived from the content address and is UNIQUE, so a concurrent upload of the same
	// content under the same name collapses to one row instead of double-inserting. DO NOTHING (not a
	// no-op UPDATE) so a deduped upload emits no spurious audit row; the caller reads the existing row.
	AdminInsertFile(ctx context.Context, arg AdminInsertFileParams) (File, error)
	// ── flags ───────────────────────────────────────────────────────────────────────
	AdminInsertFlag(ctx context.Context, arg AdminInsertFlagParams) (Flag, error)
	// ── hints ───────────────────────────────────────────────────────────────────────
	AdminInsertHint(ctx context.Context, arg AdminInsertHintParams) (Hint, error)
	// One statement, one transaction: the whole batch lands or none of it does. An in-batch duplicate,
	// or a collision with an existing generation's hash, trips UNIQUE(challenge_id, value_hash,
	// generation) and rolls the entire upload back — the friendly duplicate pre-check in Go only buys a
	// nicer message; this is the guarantee. A zero artifact_id means "no artifact": file ids are
	// bigserial and never 0, so it is a safe stand-in for the SQL NULL a bigint[] element cannot carry.
	AdminInsertInstances(ctx context.Context, arg AdminInsertInstancesParams) (int64, error)
	// ── audit trail ───────────────────────────────────────────────────────────────────
	// Read-only feed over the capture triggers' output, newest first. Each filter is optional and
	// narrows independently; an unset one drops out of the WHERE rather than matching a sentinel. The
	// (at, id) tiebreak keeps the order total when many rows share a timestamp, so pages never overlap.
	// COUNT(*) OVER () rides along so the page and its total agree in one round trip.
	AdminListAudit(ctx context.Context, arg AdminListAuditParams) ([]AdminListAuditRow, error)
	// The whole prerequisite graph, for the cycle warning on requirement writes. Boards are small; one
	// read beats a traversal query nothing else needs.
	AdminListChallengeRequirements(ctx context.Context) ([]AdminListChallengeRequirementsRow, error)
	// Every field, in the order a form would render them: user fields then team fields, each by their
	// authored position, id as the stable tie-break.
	AdminListFields(ctx context.Context) ([]Field, error)
	// The pool of one challenge, newest generation first, each row carrying who it was issued to (a NULL
	// issued_to is a still-free instance). COUNT(*) OVER () rides along so the page and its total agree.
	AdminListInstances(ctx context.Context, arg AdminListInstancesParams) ([]AdminListInstancesRow, error)
	// The admin index: every page, draft or not. Content is omitted — the list does not need the body,
	// and a rules page is large.
	AdminListPages(ctx context.Context) ([]AdminListPagesRow, error)
	AdminListTags(ctx context.Context) ([]AdminListTagsRow, error)
	// Admin-side roster repair: an organizer acting on someone else's team. The captain's own
	// kick/leave path lives in teams.sql; these are the organizer's equivalents, and they differ in
	// exactly one way — see AdminDetachMember.
	// The admin roster view. email is admin-only data, which is why it is selected here and never on
	// the public team page.
	AdminListTeamMembers(ctx context.Context, teamID *int64) ([]AdminListTeamMembersRow, error)
	// ── teams ───────────────────────────────────────────────────────────────────────
	// COUNT(*) OVER () carries the total in the same round trip, like AdminListUsers. The search is
	// one optional (q, field) pair; an unset q drops the filter entirely, and an unknown field falls
	// back to the name so the CASE can never silently match nothing.
	AdminListTeams(ctx context.Context, arg AdminListTeamsParams) ([]AdminListTeamsRow, error)
	// ── users ───────────────────────────────────────────────────────────────────────
	// COUNT(*) OVER () carries the total in the same round trip, so the pagination header never
	// disagrees with the page it describes. The (q, field) search mirrors the team list; email is
	// searchable here and nowhere public.
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	// Drop the source rows on challenges that already carry the destination, so the rename that follows
	// cannot trip UNIQUE(challenge_id, value). These deletions are real merges and are audited as such.
	AdminMergeTagCollisions(ctx context.Context, arg AdminMergeTagCollisionsParams) (int64, error)
	// The value_hash set of the newest generation, for the idempotent-push check: an upload whose hash
	// set equals this one is a no-op and returns the existing generation unchanged.
	AdminNewestPoolHashes(ctx context.Context, challengeID int64) ([][]byte, error)
	// ── challenge instances (the unique-flag pool) ────────────────────────────────────
	//
	// The pool write path. The client uploads value_hash = sha256(flag) — never the plaintext, which
	// the platform is designed never to hold — plus an optional per-account artifact and vars. A
	// re-upload lands in a new generation so new issues come from the new set while existing flag_issues
	// stay attributable to the instances they were assigned from.
	// The generation a fresh upload lands in: one past the highest present, or 1 for an empty pool.
	AdminNextPoolGeneration(ctx context.Context, challengeID int64) (int32, error)
	AdminRemoveTag(ctx context.Context, arg AdminRemoveTagParams) (int64, error)
	AdminRenameTag(ctx context.Context, arg AdminRenameTagParams) (int64, error)
	// Bulk position assignment in one statement: the two arrays are zipped by ordinality, so every
	// challenge moves or none does. A row count below the input length means an id did not exist.
	AdminReorderChallenges(ctx context.Context, arg AdminReorderChallengesParams) (int64, error)
	// The one write path for challenges.flag_mode outside the importer. The switch guards live in the
	// service, in the same transaction as this update: a mid-event switch would misfire the
	// unissued-solve detector, so the service refuses it while any solve exists.
	AdminSetChallengeFlagMode(ctx context.Context, arg AdminSetChallengeFlagModeParams) (Challenge, error)
	// Whole-value replace: the column is one document, so a partial patch has no meaning here.
	AdminSetChallengeRequirements(ctx context.Context, arg AdminSetChallengeRequirementsParams) (Challenge, error)
	AdminSetChallengeState(ctx context.Context, arg AdminSetChallengeStateParams) (Challenge, error)
	AdminSetTeamBanned(ctx context.Context, arg AdminSetTeamBannedParams) (AdminSetTeamBannedRow, error)
	AdminSetTeamHidden(ctx context.Context, arg AdminSetTeamHiddenParams) (AdminSetTeamHiddenRow, error)
	AdminSetUserBanned(ctx context.Context, arg AdminSetUserBannedParams) (AdminSetUserBannedRow, error)
	AdminSetUserHidden(ctx context.Context, arg AdminSetUserHiddenParams) (AdminSetUserHiddenRow, error)
	AdminSetUserRole(ctx context.Context, arg AdminSetUserRoleParams) (AdminSetUserRoleRow, error)
	// Admin-side verification repair: the escape hatch for an event whose mail never arrives.
	// Every statement here runs inside a transaction that has stamped the acting admin into
	// app.actor_id, so the capture triggers write the audit row in the same transaction as the
	// change itself. Flipping who counts as a verified player is exactly the kind of act that
	// has to be attributable afterwards.
	AdminSetUserVerified(ctx context.Context, arg AdminSetUserVerifiedParams) (AdminSetUserVerifiedRow, error)
	// Read-side disambiguation only: it shapes "no such team" versus "user is not on that team" after a
	// zero-row write. The foreign key, not this, is what actually refuses a bad target.
	AdminTeamExists(ctx context.Context, teamID int64) (bool, error)
	// Partial update: an absent field keeps its value. applies_to is immutable — flipping it would
	// silently strand every current member, whose account kind no longer matches.
	AdminUpdateBracket(ctx context.Context, arg AdminUpdateBracketParams) (Bracket, error)
	// Partial update with a third state for the nullable columns: an absent field keeps its value, a
	// clear flag nulls it, and a supplied value sets it. The three are exclusive per column — the
	// transport turns an omitted key into neither, an explicit null into the clear, and a value into
	// the narg. The dynamic-params CHECK still arbitrates the result, so clearing initial on a decayed
	// challenge is refused, not silently stored.
	AdminUpdateChallenge(ctx context.Context, arg AdminUpdateChallengeParams) (Challenge, error)
	// Partial update: an absent argument keeps its value. field_type and applies_to are immutable —
	// flipping either would reinterpret every stored answer (a text answer read as a bool, a user
	// answer counted against a team gate), so they are create-only, exactly as a bracket's applies_to is.
	AdminUpdateField(ctx context.Context, arg AdminUpdateFieldParams) (Field, error)
	// Scoped by challenge_id in the WHERE, not checked in Go: a flag id from another challenge's URL
	// affects zero rows, so there is no window and no forgotten guard.
	AdminUpdateFlag(ctx context.Context, arg AdminUpdateFlagParams) (Flag, error)
	AdminUpdateHint(ctx context.Context, arg AdminUpdateHintParams) (Hint, error)
	// Partial update: an absent field keeps its value. Changing route to one already taken trips
	// pages_route_key, which the service turns into a 409.
	AdminUpdatePage(ctx context.Context, arg AdminUpdatePageParams) (Page, error)
	// Deliberately narrow SET: banned, hidden, captain_id, password_hash and membership are not
	// reachable from this statement — they move through their own routes or not at all.
	AdminUpdateTeam(ctx context.Context, arg AdminUpdateTeamParams) (AdminUpdateTeamRow, error)
	// Deliberately narrow SET: email, role, banned, hidden, team_id and must_change_password are not
	// reachable from this statement — each moves through its own route or not at all.
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (AdminUpdateUserRow, error)
	// The whole-event repair, for a mailer that accepted everything and delivered nothing.
	// Narrowed to the rows that actually change: the audit trail then names exactly the accounts
	// this unblocked, and running it twice is a no-op rather than a second sweep of noise.
	AdminVerifyAllUsers(ctx context.Context) (int64, error)
	// A sole member adopts a captainless team (the captain's user row was deleted, FK SET NULL).
	AdoptCaptainlessTeam(ctx context.Context, arg AdoptCaptainlessTeamParams) error
	// Hands the account an unissued instance from the pool.
	//
	// Two constraints back this up: PRIMARY KEY (challenge_id, account_id) makes it idempotent under
	// concurrent first-views, and UNIQUE (instance_id) makes double-issue impossible — which is the
	// constraint the entire anti-cheat property rests on.
	//
	// Callers must hold LockChallengePool. `FOR UPDATE ... SKIP LOCKED` alone does not make this
	// safe, which is not obvious and was found the hard way: it locks the challenge_instances row, but
	// the "is it issued?" test reads flag_issues — a different table. A transaction whose snapshot
	// predates a concurrent commit still sees the instance as free, and by the time it takes the row
	// lock the other transaction has already released it, so nothing is skipped. The loser then trips
	// UNIQUE(instance_id), which ON CONFLICT does not catch (its target is the PK), and the player gets
	// a 500 — at CTF start, when everyone opens the challenge at once.
	//
	// Newest generation first: re-uploading a pool bumps `generation`, and new issues should come from
	// the new pool while old flag_issues rows keep pointing at their original instance, so submissions
	// attributed under a previous generation stay attributable.
	//
	// Zero rows is ambiguous, and the caller must disambiguate by re-reading GetIssuedInstance:
	//   (a) a row comes back  ⇒ a concurrent first-view won the race; use it (idempotent, correct).
	//   (b) no row comes back ⇒ the pool is exhausted. Hard-fail the challenge — never fall back to a
	//       shared flag, which would silently destroy uniqueness for exactly the late registrants you
	//       are most suspicious of.
	AssignInstance(ctx context.Context, arg AssignInstanceParams) (int64, error)
	// ── rate limits ─────────────────────────────────────────────────────────────────
	// Atomic on Postgres alone. The row is the counter, so there is no increment to lose: two
	// concurrent bumps serialize on the primary key and both see a correct value.
	BumpRateLimit(ctx context.Context, arg BumpRateLimitParams) (int32, error)
	// Drop a queued change without confirming it (the player cancelled, or is re-queuing a different
	// address). Idempotent: no pending change is a no-op.
	ClearPendingEmail(ctx context.Context, userID int64) error
	// Promote the pending address to live, atomically, and only if there is one to promote. verified is
	// set true because the token that reached this statement was delivered to the new address and proves
	// control of it. users_email_uniq rejects a race where the address was taken since it was queued —
	// a loud 23505 the caller turns into a conflict, never a silent overwrite. Zero rows means the
	// pending address was already cleared (a spent or duplicate confirm).
	ConfirmEmailChange(ctx context.Context, userID int64) (int64, error)
	// Single-use is enforced by this one statement: two concurrent consumers race on the row
	// lock, and the loser sees consumed_at already set and gets zero rows. A SELECT-then-UPDATE
	// would let both pass the check. Expiry lives in the WHERE clause so an expired token is
	// indistinguishable from a bad one, on the database's clock, not the app server's.
	ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (int64, error)
	CountAwardsWithoutParent(ctx context.Context) (int64, error)
	// How many answers a field carries, for the admin delete confirmation ("this removes N answers").
	CountFieldEntries(ctx context.Context, fieldID int64) (int64, error)
	// Whether any other row still points at the same stored object, so a delete knows if the object is
	// now unreferenced and safe to remove.
	CountFilesBySha(ctx context.Context, sha256sum []byte) (int64, error)
	CountFilesWithoutChallenge(ctx context.Context) (int64, error)
	// The distinct (issued-to, submitted-by) pair count behind FindFlagSharingPairs, for pagination.
	CountFlagSharingPairs(ctx context.Context) (int64, error)
	// Referential-integrity probes. session_replication_role=replica ignores foreign keys during the
	// COPY rather than deferring them, so re-enabling it validates nothing — a dangling reference has to
	// be counted explicitly, still inside the transaction, so the whole restore rolls back on the first
	// one found.
	CountFlagsWithoutChallenge(ctx context.Context) (int64, error)
	CountHintsWithoutChallenge(ctx context.Context) (int64, error)
	// The count of IP clusters meeting the threshold, for pagination.
	CountIPOverlaps(ctx context.Context, minAccounts int32) (int64, error)
	// The max_attempts gate: wrong answers only, all-time, scoped to the account. A COUNT(*) over the
	// append-only log rather than a counter row — there is no increment to lose.
	CountIncorrectSubmissions(ctx context.Context, arg CountIncorrectSubmissionsParams) (int64, error)
	// The prerequisite gate for the submit path. Counts how many of the given challenge ids this
	// account has solved; the caller compares that against the number required. It is a plain indexed
	// read with no lock, so a prerequisite-locked challenge is rejected before the challenge lock is
	// ever taken — the wrong-answer fast path is untouched. The account model comes from `instance`.
	CountSolvedPrerequisites(ctx context.Context, arg CountSolvedPrerequisitesParams) (int64, error)
	// First-blood detection, run under the challenge lock so it is exact, not a guess.
	//
	// Two columns, and first blood requires both: `prior_solves = 0 AND actor_eligible`.
	// "Hidden and banned accounts cannot take first blood" is two rules, not one:
	//
	//   prior_solves   — hidden/banned solvers are excluded from the count, so a hidden admin
	//                    test-solving a challenge does not burn its first blood for the real solvers.
	//   actor_eligible — the submitter is itself visible. The count alone silently gets this wrong:
	//                    for a hidden solver the count is 0 *by construction* (it excluded itself),
	//                    so `prior == 0` would hand the bonus to the hidden account.
	//
	// The account model comes from `instance`, not from a caller-supplied flag: user_mode is
	// immutable and singleton, so reading it here costs one cached-page lookup and makes it impossible
	// for a caller to count the wrong column.
	CountSolvesExcluding(ctx context.Context, arg CountSolvesExcludingParams) (CountSolvesExcludingRow, error)
	CountSolvesWithoutParent(ctx context.Context) (int64, error)
	CountSubmissionsWithoutParent(ctx context.Context) (int64, error)
	CountTagsWithoutChallenge(ctx context.Context) (int64, error)
	CountTeamsWithoutCaptain(ctx context.Context) (int64, error)
	// The unissued-solve count behind FindUnissuedSolves, for pagination.
	CountUnissuedSolves(ctx context.Context) (int64, error)
	// The prerequisite gate for hint unlocks. A hint can require other hints to be unlocked first;
	// this counts how many of them this account already owns, and the caller compares that against the
	// number required. Hint prerequisites carry no anonymize flag — a locked hint is simply not
	// purchasable until its prerequisites are unlocked.
	CountUnlockedHintPrerequisites(ctx context.Context, arg CountUnlockedHintPrerequisitesParams) (int64, error)
	CountUsersWithoutTeam(ctx context.Context) (int64, error)
	// ── api tokens ──────────────────────────────────────────────────────────────────
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error)
	// The first-admin bootstrap. role='admin' cannot be granted through the admin API without an admin
	// already existing, so the very first one is made here instead. verified is stamped true because the
	// account has no inbox flow behind a console command. The caller runs this with the caps trigger
	// disabled for the transaction, so a full instance cannot lock its own first admin out.
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (int64, error)
	// Email verification and password reset tokens.
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (int64, error)
	// ── sessions ────────────────────────────────────────────────────────────────────
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	// Team enrollment and the team profile read models.
	// The unique name index and the num_teams caps trigger arbitrate: a duplicate raises 23505 and an
	// over-cap insert raises a check_violation on the INSERT itself, never in a prior SELECT.
	CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error)
	// Registration. The unique email and the num_users/team_size caps are enforced by the index and the
	// caps trigger, so a duplicate raises 23505 and an over-cap insert raises a check_violation — both
	// surface as errors here rather than as a lost check-then-insert race.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Scoped by user_id as well as id: ownership is enforced in the WHERE clause rather than by a
	// SELECT-then-check in Go, so there is no window and no forgotten guard. Zero rows affected means
	// "not yours, or not there", and the caller cannot tell the difference — which is correct.
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error)
	DeleteExpiredAPITokens(ctx context.Context) error
	DeleteExpiredEmailTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldRateLimits(ctx context.Context, before pgtype.Timestamptz) error
	DeleteSession(ctx context.Context, idHash []byte) error
	// A team ban's session sweep. The ban wall stops every member on their next request even
	// without this — the wall reads team_banned per request — but a live cookie on a banned
	// team is still a door left unlocked.
	DeleteTeamSessions(ctx context.Context, teamID *int64) error
	// Clearing an optional, editable answer. A DELETE, not a value=null write: "no answer" has one
	// representation (no row), which the gate and the reads all agree on.
	DeleteUserFieldEntry(ctx context.Context, arg DeleteUserFieldEntryParams) error
	// "Log out everywhere". Also what a ban should call — a banned user's live cookie is still a live
	// cookie, and the ban wall stops them on the next request, but there is no reason to leave the door
	// shut and unlocked.
	DeleteUserSessions(ctx context.Context, userID int64) error
	// Disband is a plain delete guarded only by captaincy. The RESTRICT foreign keys from the ledger
	// (submissions, solves, awards, hint_unlocks) refuse the delete the instant the team has any
	// history, surfacing as a foreign_key_violation the API turns into a conflict — a scored team is
	// retired by hide/ban, never erased. Any remaining members fall to team_id NULL via the ON DELETE
	// SET NULL on users, so a zero-history team created by mistake vanishes cleanly.
	DisbandTeam(ctx context.Context, captainID int64) (int64, error)
	// Async admin operations (backup, restore, import) tracked in the tasks table. River owns the
	// execution; this table owns the state a poller reads. The progress writes below run on a
	// connection SEPARATE from the restore transaction on purpose: a restore is one transaction so its
	// own progress UPDATEs would be invisible until it commits.
	// Inserts a queued task. The tasks_one_in_flight partial unique index raises 23505 when a task of
	// the same kind is already queued or running — that unique violation IS the single-in-flight
	// refusal, surfaced to the caller as 409, never a second job queued to collide.
	EnqueueTask(ctx context.Context, arg EnqueueTaskParams) (Task, error)
	// "Already on a team" is the WHERE clause, not a prior read: zero rows means the user was enrolled
	// elsewhere by the time this ran. The caps trigger enforces team_size on the same statement.
	EnrollUser(ctx context.Context, arg EnrollUserParams) (int64, error)
	// The console bootstrap: the one path from an empty database to a playable instance.
	//
	// Two rows make an instance live — the instance singleton (which the scoring SQL keys on) and
	// config.setup (which the route policy gates every request on, including /login). They are written
	// in the same transaction as the first admin, so a live instance always has an admin and an
	// instance with an admin is always live.
	// The singleton, created once and never rewritten: user_mode is fixed at setup, and the immutability
	// trigger says so. ON CONFLICT makes a re-run idempotent and hands back the mode actually in force —
	// the no-op SET exists only so RETURNING fires on the conflict path, and it re-asserts the same
	// user_mode so the trigger stays satisfied.
	EnsureInstance(ctx context.Context, arg EnsureInstanceParams) (string, error)
	// A failure is loud and terminal: the error text is stamped for the operator and the row leaves the
	// in-flight set, freeing the kind for another attempt.
	FailTask(ctx context.Context, arg FailTaskParams) error
	// The anti-cheat detectors. Reads only. These never mutate, never penalise, and never tell the
	// player anything: auto-penalisation was considered and rejected (no appeal path, and a false
	// positive becomes an instant ban during a live event). They feed an admin review queue; a human
	// decides, out of band.
	// A predicate on `submissions` alone — no join to flag_issues, no join to
	// challenge_instances. That is the entire payoff of stamping `attributed_account_id` inside the
	// submit transaction: the evidence survives the instance being rotated, regenerated or
	// deleted, and it survives swapping FlagIssuer to the HMAC implementation later. A join-based audit
	// trail is only as durable as the rows it joins to; a stamped one is a fact.
	//
	// Served by submissions_sharing_idx, which is partial — only correct, attributed submissions are
	// ever scanned, a tiny fraction of the table.
	//
	// The account model comes from `instance`. In teams mode the unit is the team, so
	// intra-team sharing is invisible by design: teammates legitimately share artifacts and flags — that
	// is what a team is. The detector fires only across accounts, which is the thing worth catching.
	FindFlagSharing(ctx context.Context, lim int32) ([]FindFlagSharingRow, error)
	// One account's sharing evidence, both directions: flags issued to it that another account submitted
	// (direction='issued_to') and flags it submitted that were issued to another (direction='submitted'),
	// grouped by counterparty. Bounded to one account, so it is not paginated.
	FindFlagSharingForAccount(ctx context.Context, accountID int64) ([]FindFlagSharingForAccountRow, error)
	// Flag sharing, folded to one row per offender pair: account `submitter` submitted correct flags that
	// were issued to account `issued_to`. Same predicate as FindFlagSharing — submissions alone, so it
	// survives instance rotation — but grouped, counted, and with the challenge span, so a pair that
	// shared twenty flags is one row of evidence, not twenty. Served by submissions_sharing_idx.
	FindFlagSharingPairs(ctx context.Context, arg FindFlagSharingPairsParams) ([]FindFlagSharingPairsRow, error)
	// The other accounts that shared an address with @account_id, one row per (address, other account).
	// Same signal caveat as FindIPOverlaps: shared egress is common and this only points a human at a
	// coincidence worth checking.
	FindIPOverlapForAccount(ctx context.Context, arg FindIPOverlapForAccountParams) ([]FindIPOverlapForAccountRow, error)
	// Addresses used by several distinct accounts. This is a SIGNAL, not a verdict: shared NAT, a campus,
	// a corporate egress or a carrier-grade NAT pool all put unrelated players behind one address, so a
	// cluster is evidence for a human to weigh, never grounds to act on alone. @min_accounts tunes how
	// many distinct accounts on one address is worth surfacing. In teams mode the account is the team, so
	// teammates behind one router do not trip it. Served by submissions_ip_idx.
	FindIPOverlaps(ctx context.Context, arg FindIPOverlapsParams) ([]FindIPOverlapsRow, error)
	// The provable detector, not a statistical signal.
	//
	// A solve on a flag_mode='unique' challenge by an account that was never issued an instance. There is
	// no honest way to hold a valid flag for a challenge whose artifact you never fetched: assignment is
	// lazy, so a flag_issues row exists for every account that so much as opened the challenge. No such
	// row means the flag came from somewhere else. Full stop.
	//
	// Anti-join over solves_challenge_firstblood_idx × the flag_issues PK. No new index.
	FindUnissuedSolves(ctx context.Context, arg FindUnissuedSolvesParams) ([]FindUnissuedSolvesRow, error)
	FinishTask(ctx context.Context, arg FinishTaskParams) error
	// Looked up by sha256(token); the plaintext is shown once, at creation, and never stored —
	// a table of plaintext secrets turns every dump or export into a bearer-credential leak.
	// Expiry is enforced here, in the WHERE clause, for the same reason as sessions.
	GetAPIToken(ctx context.Context, tokenHash []byte) (GetAPITokenRow, error)
	// The affordability read: an exact SUM over the ledger — a cached balance is an opinion
	// about the past — taken under the spend lock so no concurrent spend can land between
	// this read and the insert that follows. awards.value may be negative (that is what a
	// hint spend is). The account model comes from `instance`, never a caller-supplied flag.
	GetAccountScore(ctx context.Context, arg GetAccountScoreParams) (int64, error)
	GetBracket(ctx context.Context, bracketID int64) (Bracket, error)
	// The submit hot path.
	//
	// The ordering that matters: the challenge lock is taken lazily, on the correct-flag path only.
	// ~99% of submissions are wrong answers; a lock at the top of the transaction would serialize every
	// wrong guess on the hottest challenge through one row — a queue where you meant to build a guard.
	// Step 1 of submit: read the challenge with no lock. The flag compare happens against this.
	// A hidden challenge is not playable; the guard lives in this read so no caller can forget it.
	GetChallenge(ctx context.Context, challengeID int64) (Challenge, error)
	// The metadata a download needs, joined to its challenge so the handler can enforce that a hidden
	// challenge's file is invisible to non-admins. A file with no owning challenge returns no row.
	//
	// prereqs_met is the projection the board and the detail view already compute: a challenge whose
	// prerequisites this account has not solved lists no files at all, so a download by id answers to
	// the same gate. Without it the id — a bigserial, and therefore guessable — is a side door onto the
	// artifacts of every challenge the board is withholding.
	GetChallengeFileForDownload(ctx context.Context, arg GetChallengeFileForDownloadParams) (GetChallengeFileForDownloadRow, error)
	// calling this on a static challenge is a no-op, not a corruption
	// The flag_mode='static' compare path. Loaded on every submit of a static challenge — the
	// hottest read in the product — and served entirely by flags_challenge_idx.
	//
	// Every flag is returned and the caller (domain/flags.MatchAny) evaluates ALL of them without
	// short-circuiting: stopping at the first match would leak, through response latency, which flag
	// matched. The whole point of crypto/subtle is lost if the loop above it branches on the result.
	GetChallengeFlags(ctx context.Context, challengeID int64) ([]Flag, error)
	// A single visible challenge with the same solve_count / solved projection as the board, clamped to
	// the same freeze horizon — including `value`, which is invertible to the solve count on a dynamic
	// challenge and so is quoted at the frozen count for a frozen viewer. See ListChallenges.
	GetChallengeForView(ctx context.Context, arg GetChallengeForViewParams) (GetChallengeForViewRow, error)
	GetFileByLocation(ctx context.Context, location string) (File, error)
	// The challenge id from the URL is part of the key: a hint reached through the wrong challenge —
	// or through a hidden one — is simply not found.
	//
	// The challenge's requirements ride along because a hint is not purchasable independently of the
	// challenge that owns it: the unlock is gated on the challenge's prerequisites as well as the
	// hint's own, and reading them here keeps that gate on the row we already had to fetch.
	GetHint(ctx context.Context, arg GetHintParams) (GetHintRow, error)
	// Read under the account spend lock, which is what makes it safe to branch on. It runs
	// Before affordability: an account that owns a hint and has since spent down to zero
	// must be told it owns the hint — not that it cannot afford it.
	GetHintUnlock(ctx context.Context, arg GetHintUnlockParams) (int64, error)
	// Unique flags / challenge instances.
	//
	// An instance is a bundle: a flag (stored only as sha256), an optional artifact, and per-account
	// template vars. Assignment is lazy — at the account's first access to the challenge. This is the
	// only place in the product where reading a challenge mutates state.
	// The account's own instance. This is the entire template context source: `vars` and the
	// artifact, and nothing else. Note what is absent — there is no path from here to the plaintext flag,
	// because the plaintext is never stored. Cross-account leakage is not prevented, it is
	// unrepresentable.
	// Challenge detail for flag_mode='unique' therefore varies by account: any cache must be keyed by
	// (challenge_id, account_id). Design this in; do not discover it.
	GetIssuedInstance(ctx context.Context, arg GetIssuedInstanceParams) (GetIssuedInstanceRow, error)
	// The listen pump carries only an id in the 8 kB NOTIFY payload and reloads the row here, so the
	// content it fans out is the committed row rather than a copy that could disagree with it.
	GetNotification(ctx context.Context, id int64) (Notification, error)
	// No cutoff: an account always sees its own live score, freeze or not. Withholding it would tell
	// the team nothing an attacker wants and everything they already know.
	// t.email rides along because this is the team's own view — the public profile never selects it.
	GetOwnTeam(ctx context.Context, userID int64) (GetOwnTeamRow, error)
	// CMS pages: the rules/FAQ/sponsors content. The public reads are keyed by the URL slug; the admin
	// CRUD is keyed by id. Route uniqueness is the table's (pages_route_key), so a duplicate slug is a
	// constraint violation the service maps to a 409, never a check-then-insert.
	// The public read. Returns the row whatever its draft/auth_required flags — the policy gate decides
	// visibility against them, so the query must not pre-filter drafts or the gate could never be tested.
	GetPageByRoute(ctx context.Context, route string) (Page, error)
	// One account's cumulative score over time, replayed from the same append-only ledger the
	// scoreboard sums. Powers the graph on a public profile, so it is freeze-safe by the same mechanism:
	// the caller passes the freeze horizon as `cutoff` and every event at or after it is excluded. The
	// query takes no is_admin freeze flag — `cutoff` IS the horizon, so the clamp cannot be forgotten by
	// handing in the wrong boolean.
	// `admin` here only widens visibility to a hidden or banned subject; it never lifts the freeze. A
	// non-admin viewing a hidden account gets an empty timeline, exactly as that account is absent from
	// the board — and a non-existent account reads the same empty, leaking nothing about which is which.
	//
	// The account column is resolved from `instance`, immutable since setup, so the timeline can never be
	// keyed on the wrong account model. `value <> 0` mirrors the scoreboard: a zero-point event does not
	// move the line. The running total is a window SUM over (date, value); microsecond ties settle on
	// value, and the final cumulative is order-independent regardless.
	GetScoreHistory(ctx context.Context, arg GetScoreHistoryParams) ([]GetScoreHistoryRow, error)
	// Expiry is a WHERE clause, not a Go comparison: an expired session must be indistinguishable from
	// a missing one, and it must be so at the only place that can be tricked into disagreeing — the
	// database. `now()` is the transaction's clock, not the app server's, so a skewed pod cannot extend
	// a session.
	//
	// pw_fingerprint comes back so the caller can compare it against the user's current password hash.
	// A mismatch means the password changed after this session was minted, and the session is dead.
	GetSession(ctx context.Context, idHash []byte) (GetSessionRow, error)
	// Scoreboard time-travel: "what did the board look like at 14:00?". Possible only because
	// stamped solve values make the scoreboard append-only.
	//
	// The caller must clamp `as_of` to the freeze horizon for non-admins — otherwise
	// `?as_of=<now>` during a freeze hands the live board to anyone who asks. This query
	// deliberately takes no admin freeze flag, so the clamp cannot be forgotten by passing
	// the wrong boolean: `as_of` is the horizon.
	//
	// The account column is resolved from `instance`, a singleton and immutable, so the
	// time-travel board can never be computed against the wrong account model.
	GetStandingsAsOf(ctx context.Context, arg GetStandingsAsOfParams) ([]GetStandingsAsOfRow, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTeamForJoin(ctx context.Context, name string) (GetTeamForJoinRow, error)
	// Hidden and banned teams 404 publicly, matching the board and the solve lists. The score sums
	// the stamped solves.team_id ledger — the same legs the scoreboard reads, and it takes the same
	// freeze horizon: cutoff is strict `<`, NULL = live. Both legs carry it, because a public team
	// page that sums live is the frozen board read one team at a time.
	GetTeamPublicProfile(ctx context.Context, arg GetTeamPublicProfileParams) (GetTeamPublicProfileRow, error)
	GetTeamStandings(ctx context.Context, arg GetTeamStandingsParams) ([]GetTeamStandingsRow, error)
	// ── credentials ─────────────────────────────────────────────────────────────────
	// Case-insensitive, matching users_email_uniq: lookup and the uniqueness constraint must
	// agree on the fold, or an address can be registered twice and reset neither time.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error)
	// The account model. Singleton and immutable (enforced by instance_user_mode_immutable), so this
	// is one cached-page lookup. `instance` is created at setup; NO ROWS means the instance was never
	// set up, which is a hard error and not a defaultable condition. Loud beats silent.
	GetUserMode(ctx context.Context) (string, error)
	// Public account profiles: a user's page, gated exactly like the scoreboard and the team page.
	// A hidden or banned user 404s to the public and is visible to an admin — the `admin` flag is the
	// only thing that widens the row, mirroring the scoreboard. The score sums the stamped solves.user_id
	// and awards.user_id ledgers under the caller's freeze horizon (cutoff strict `<`, NULL = live), so a
	// public page served during a freeze hands over the frozen standing, one account at a time.
	GetUserPublicProfile(ctx context.Context, arg GetUserPublicProfileParams) (GetUserPublicProfileRow, error)
	// Standings and scoreboard time-travel. The heaviest read in the product.
	// Four things here are load-bearing:
	//
	//   1. `SUM(solves.value)`, not `SUM(challenges.value)`: the score is what each solve was
	//      worth at the time. Summing the live value lets decay retroactively rewrite history.
	//   2. `value <> 0` on both legs: a zero-point solve or award must not move the tiebreak's
	//      timestamp.
	//   3. INNER JOIN to the account table: an account with no non-zero scoring event is absent
	//      from the board, not shown at rank N with 0 points.
	//   4. The tiebreak is `score DESC, last_event ASC, account_id ASC` — the last clause is
	//      determinism insurance for an exact-microsecond tie at an identical score.
	//
	// `cutoff` is the freeze horizon, strict `<`: a solve exactly at the freeze timestamp is
	// hidden. NULL = no freeze / admin view. `admin` includes hidden and banned accounts.
	// `lim` = 0 means no limit.
	GetUserStandings(ctx context.Context, arg GetUserStandingsParams) ([]GetUserStandingsRow, error)
	// Teams mode: the scoring account is the team. awards.user_id is NOT NULL, so the adjustment is
	// recorded against the team's captain — its representative member, kept current by the enrolment
	// trigger. A team with no members (captain_id IS NULL) has no way to score and is refused as zero
	// rows rather than silently violating the NOT NULL.
	GrantTeamAward(ctx context.Context, arg GrantTeamAwardParams) (GrantTeamAwardRow, error)
	// Manual awards: the admin write surface for out-of-band point adjustments — a cheating penalty,
	// a live-dispute correction, a make-good. A manual award is always type='standard'; the ledger's
	// other award types (hint_unlock, first_blood) are gameplay facts stamped under the challenge lock,
	// never an admin decision. The scoreboard already sums awards.value alongside solves.value, so a
	// single INSERT here moves standings and nothing on the read side changes.
	// Users mode: the scoring account is the user. team_id rides along from the user's own row (NULL in
	// users mode), exactly as the submit path writes both. Zero rows ⇒ no such user.
	GrantUserAward(ctx context.Context, arg GrantUserAwardParams) (GrantUserAwardRow, error)
	ImportAwards(ctx context.Context, arg []ImportAwardsParams) (int64, error)
	// Bulk restore path for the archive importer (internal/platform/importer).
	//
	// Every insert here is a :copyfrom: the loader streams whole translated tables through the binary
	// COPY protocol inside one transaction, with explicit ids so the archive's identity is preserved.
	// The transaction runs under `session_replication_role = replica`, so foreign keys and audit
	// triggers are suppressed during the COPY and the tables can be loaded in any order; unique and
	// check constraints stay live, which is what turns a conflicting archive into an atomic failure
	// rather than a silently partial import. Dangling references are caught explicitly afterwards by
	// the Count*WithoutParent probes below.
	ImportBrackets(ctx context.Context, arg []ImportBracketsParams) (int64, error)
	ImportChallenges(ctx context.Context, arg []ImportChallengesParams) (int64, error)
	ImportConfig(ctx context.Context, arg []ImportConfigParams) (int64, error)
	ImportFiles(ctx context.Context, arg []ImportFilesParams) (int64, error)
	ImportFlags(ctx context.Context, arg []ImportFlagsParams) (int64, error)
	ImportHints(ctx context.Context, arg []ImportHintsParams) (int64, error)
	ImportSolves(ctx context.Context, arg []ImportSolvesParams) (int64, error)
	ImportSubmissions(ctx context.Context, arg []ImportSubmissionsParams) (int64, error)
	ImportTags(ctx context.Context, arg []ImportTagsParams) (int64, error)
	ImportTeams(ctx context.Context, arg []ImportTeamsParams) (int64, error)
	ImportUsers(ctx context.Context, arg []ImportUsersParams) (int64, error)
	// The first-blood bonus and the hint-unlock charge are both awards (`value` may be negative).
	// `awards_one_first_blood_per_challenge` (partial unique) prevents a double bonus even if the
	// challenge lock is ever bypassed — by an admin grant, an import, or a psql session.
	InsertAward(ctx context.Context, arg InsertAwardParams) (InsertAwardRow, error)
	// Platform-level writes whose only interesting property is that they are race-free:
	// a unique constraint plus ON CONFLICT, never a check-then-insert.
	// ON CONFLICT DO UPDATE, not DO NOTHING: a re-upload of a byte-identical object must hand
	// back the existing id, not ErrNoRows. `location` is content-addressed upstream, so the
	// SET is a no-op write that exists only to make RETURNING fire on the conflict path.
	InsertFileOnce(ctx context.Context, arg InsertFileOnceParams) (InsertFileOnceRow, error)
	// The duplicate check IS the constraint, never a SELECT. Zero rows (pgx.ErrNoRows) means
	// already unlocked, and the caller must roll back: the award inserted a moment earlier is
	// a charge, and committing it without the unlock row it paid for is a double-charge.
	// `award_id` is NOT NULL UNIQUE REFERENCES awards(id) — exactly one charge per unlock.
	InsertHintUnlock(ctx context.Context, arg InsertHintUnlockParams) (InsertHintUnlockRow, error)
	// Notifications are broadcast, not addressed: every row goes to every client, so there is no
	// targeting column to filter on. The interesting property lives in the service, where the INSERT
	// and the pg_notify that wakes the listeners share one transaction — a row that persists is a row
	// that was announced, and a rolled-back write never wakes the fleet.
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	// The duplicate check is the constraint, never a SELECT. Zero rows returned (pgx.ErrNoRows) is
	// the `already_solved` signal; UNIQUE(challenge_id, user_id) / UNIQUE(challenge_id, team_id) is the
	// arbiter.
	//
	// Not a data-modifying CTE. A CTE would insert the `submissions` row even when this insert
	// conflicts, orphaning a type='correct' submission with no solve. Two statements, one transaction.
	//
	// @value is the per-solve snapshot: the asking price at the moment of the solve, read under the
	// challenge lock and never recomputed. It is what makes the scoreboard append-only.
	InsertSolve(ctx context.Context, arg InsertSolveParams) (InsertSolveRow, error)
	// The append-only attempt log. `attributed_account_id` is the account the matched flag was
	// issued to — NULL unless flag_mode='unique'. It is stamped here, never joined at query time, so
	// sharing detection survives the instance being rotated, regenerated or deleted.
	InsertSubmission(ctx context.Context, arg InsertSubmissionParams) (InsertSubmissionRow, error)
	// Removal is the captain's alone, over a current teammate who is not the captain, and only while
	// the team has never scored. All three live in the WHERE, so a demoted captain, a stale target, or
	// a team already on the board changes zero rows — there is no check to race past. The scored guard
	// mirrors leave: solves stamp team_id, so a roster that can shrink after scoring would leave the
	// board attributing points to a lineup nobody can reconstruct.
	KickMember(ctx context.Context, arg KickMemberParams) (int64, error)
	// Departure is forbidden once the team has scored: solves stamp team_id, so a roster that can
	// shrink after scoring would misattribute the board. The condition lives in the statement so two
	// racing writes (a leave and a solve) serialize in the database, not in Go.
	LeaveTeam(ctx context.Context, arg LeaveTeamParams) (int64, error)
	ListAPITokens(ctx context.Context, userID int64) ([]ListAPITokensRow, error)
	// Brackets: named divisions that partition the scoreboard. A bracket is a filter over the one
	// global ranking, never a separate scoring pool, so the standings query joins it as a WHERE
	// predicate (scoreboard.sql). Membership is a single nullable FK on the account, so an account
	// belongs to at most one bracket by construction, and deleting a bracket only nulls its members.
	// All brackets, optionally scoped to one account kind. The public list passes the instance mode so
	// a client only offers filters that can match; the admin list passes nothing and sees every row.
	ListBrackets(ctx context.Context, appliesTo *string) ([]Bracket, error)
	// The board shows the name and size; the download link is built from the id. location is the storage
	// key and never leaves the server.
	ListChallengeFiles(ctx context.Context, challengeID *int64) ([]ListChallengeFilesRow, error)
	// Hint content is a purchase, never listed: the row carries the price and whether this account already
	// paid it, and the content itself is delivered only by UnlockHint.
	ListChallengeHints(ctx context.Context, arg ListChallengeHintsParams) ([]ListChallengeHintsRow, error)
	// Who solved a challenge, oldest first, with cutoff (strict <, NULL = live) as the freeze horizon.
	// The challenge is the driving table and EVERY solve/account predicate lives in an ON clause, so the
	// two empty cases stay distinguishable in one round trip: zero rows means no visible challenge (the
	// caller 404s), while `shown = false` marks a row the challenge kept but the projection must hide —
	// no visible solve at all, or a hidden/banned solver filtered out. The caller drops the unshown rows.
	ListChallengeSolves(ctx context.Context, arg ListChallengeSolvesParams) ([]ListChallengeSolvesRow, error)
	ListChallengeTags(ctx context.Context, challengeID int64) ([]string, error)
	// Read models for the challenge board and challenge detail. All account-scoped predicates resolve the
	// mode from the instance singleton, the same way the hot path and scoreboard do, so "solved by me" and
	// the solve count can never be computed against the wrong column.
	// The visible board. solve_count and solved are scoped to visible accounts, matching the decay and
	// first-blood exclusion, so a hidden admin test-solve does not inflate a challenge's count.
	// cutoff is the freeze horizon (strict <, NULL = live): a frozen viewer's solve_count must not
	// tick up on a post-freeze solve, or the count leaks what the frozen board hides.
	//
	// `value` is clamped to the same horizon, and that is not cosmetic. challenges.value is the current
	// asking price: RecalcChallengeValue rewrites it on every solve with no time predicate, and it has
	// to — the price a player is quoted must be the price they will pay. But the decay curve is public,
	// deterministic and integer-exact, so the solve count is directly invertible from the value: a
	// frozen viewer who snapshots the price and watches it drop has counted the solves the freeze exists
	// to hide. Clamping the count and serving the live value hides the reading and publishes its
	// derivative.
	//
	// So a frozen viewer is quoted the price at the FROZEN count. The curve is evaluated here, in SQL,
	// from the same integer arithmetic RecalcChallengeValue writes — a second evaluation in Go is
	// exactly how the two silently drift apart by a point. This costs the player nothing real: what a
	// solve is actually worth is stamped on solves.value when it lands, not read off this column.
	// One count per challenge, over visible accounts, clamped to the freeze horizon. solve_count and a
	// frozen viewer's value are the same fact, so they are read from the same place and cannot disagree.
	ListChallenges(ctx context.Context, arg ListChallengesParams) ([]ListChallengesRow, error)
	// COUNT(*) OVER () returns the total in the same round trip rather than a second query. Ordered by
	// a total key (date then id) so pages are stable when two rows share a timestamp.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// The public projection of a user's answers: only fields flagged public, only those actually
	// answered. This is what a public profile view is allowed to show — a non-public answer never
	// leaves this query.
	ListPublicUserFieldAnswers(ctx context.Context, userID int64) ([]ListPublicUserFieldAnswersRow, error)
	// The public list behind the nav: published pages only, drafts never appear. auth_required rides
	// along so the client can mark a link that will ask an anonymous visitor to log in.
	ListPublishedPages(ctx context.Context) ([]ListPublishedPagesRow, error)
	// The live submissions feed an organiser watches during an event and mines for cheat review.
	// Read-only over the append-only attempt log; it never joins its way to a scoring decision.
	// Keyset pagination, newest first, on the (date, id) cursor — never OFFSET, which re-counts the
	// skipped rows on every page and drifts as new attempts land mid-scroll during a live event. A NULL
	// cursor is the first page; otherwise the strict (date, id) < (before_date, before_id) tuple resumes
	// exactly after the last row already seen. The display joins are LEFT so a challenge or account whose
	// name cannot be resolved never drops the attempt from a cheat-review feed.
	//
	// attributed_account_id is passed through verbatim — it is a fact stamped inside the submit
	// transaction, never re-derived by joining the (mutable, rotatable) flag issue here.
	//
	// Ordering matches submissions_admin_list_idx and submissions_admin_type_idx (both DESC on date),
	// so the unfiltered feed and the `type` facet each walk an index backwards rather than sort.
	ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error)
	ListTeamManualAwards(ctx context.Context, teamID *int64) ([]ListTeamManualAwardsRow, error)
	// Per-member attribution reads the stamped solves.team_id, so points stay with the team that
	// scored them regardless of later roster churn. include_masked lifts the hidden/banned member
	// filter for the team's own view; cutoff is the freeze horizon (strict `<`, NULL = live) for the
	// public one, where an unclamped per-member breakdown says who scored what during the freeze.
	ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error)
	// ── user answers: registration + /me ─────────────────────────────────────────────
	// The user-applicable field definitions, for the register-time validation and the /me editor. Read
	// inside the registration transaction so required-field enforcement sees the fields as of the write.
	ListUserFieldDefs(ctx context.Context) ([]ListUserFieldDefsRow, error)
	// The /me view: every user field with this caller's current answer (NULL where unanswered), so the
	// settings form can render both the fields still owed and the ones already filled in.
	ListUserFieldsWithAnswers(ctx context.Context, userID int64) ([]ListUserFieldsWithAnswersRow, error)
	// Only type='standard' rows: hint spends and first-blood bonuses are gameplay facts, not admin
	// adjustments, and must never appear in a revoke list.
	ListUserManualAwards(ctx context.Context, userID int64) ([]ListUserManualAwardsRow, error)
	// The account's solved challenges, newest first, under the same freeze horizon as the score above.
	// Only visible challenges are listed: the total score sums the whole ledger (matching the board), but
	// naming a hidden challenge here would leak its existence, so the itemised history hides it just as
	// the per-challenge solve list does.
	ListUserSolves(ctx context.Context, arg ListUserSolvesParams) ([]ListUserSolvesRow, error)
	// Authentication: sessions, API tokens, and the one query that resolves a caller to a Principal.
	// THE authentication query. Sessions and API tokens both converge here before any
	// authorization runs, so a token cannot route around a wall a cookie hits.
	//
	// Deliberately absent: `hidden`. A hidden account authenticates and plays normally —
	// hiddenness is a scoreboard predicate, never an auth decision.
	//
	// `profile_complete` is the required-fields gate. NOT EXISTS over the missing entries,
	// so the answer is a boolean and not a count the caller has to interpret.
	LoadPrincipal(ctx context.Context, userID int64) (LoadPrincipalRow, error)
	// The max_attempts gate is a check-then-act: count wrong answers, then insert one. Without a lock
	// an account's own concurrent submissions all read the same stale count and every one slips past
	// the cap, so a scripted client brute-forces past max_attempts. This advisory lock serializes THIS
	// account's submissions to THIS challenge, making the count that follows exact. It is keyed per
	// (challenge, account): different players never contend, so the challenge is not globally serialized
	// and the wrong-answer hot path across players is untouched — this is not the challenge-row lock.
	// Taken only when the challenge has a cap. A hash collision would merely make two unrelated pairs
	// occasionally serialize, which is harmless. The xact lock auto-releases at commit or rollback.
	LockAttemptCounter(ctx context.Context, arg LockAttemptCounterParams) error
	// Taken only after the flag compared correct. Under this lock the prior-solve count is exact, so
	// first blood is decided inside the submitting transaction, and the decay recalc is exact for free.
	// Re-read `value` from this row, not from GetChallenge: another solver may have decayed the
	// challenge in between. Snapshot what the lock says, not what the optimistic read said.
	//
	// FOR NO KEY UPDATE: every INSERT into `submissions` and `solves` takes FOR KEY SHARE on this row
	// through the FK, and plain FOR UPDATE conflicts with that — it would serialize every wrong guess
	// behind the lock, one layer down. FOR NO KEY UPDATE lets the wrong-answer inserts sail through yet
	// still conflicts with itself, so two correct paths serialize. We never UPDATE challenges.id, so
	// the weaker lock costs nothing. Verified empirically.
	LockChallengeForSubmit(ctx context.Context, challengeID int64) (Challenge, error)
	// Serializes issuance for one challenge. Must be called in the same transaction as AssignInstance,
	// and as a separate statement — that is the whole point of it.
	//
	// Under READ COMMITTED a statement's snapshot is taken when the statement starts. If the lock were
	// acquired inside AssignInstance itself, the NOT EXISTS there would still be reading the snapshot
	// from before the wait, so it would not see the flag_issues row the previous holder just committed,
	// and it would hand out an instance that is already taken. Taking the lock here, first, means
	// AssignInstance's snapshot is created after the wait and sees everything.
	//
	// The lock is released on commit or rollback. Issuance is a first-view operation, not the submit
	// path, so serializing it per challenge costs nothing that matters.
	// hashtext over a namespaced string, so a bigserial challenge id is never truncated to int4.
	LockChallengePool(ctx context.Context, challengeID int64) error
	// The teams-mode counterpart. Same lock strength, same reasoning.
	LockTeamForSpend(ctx context.Context, teamID int64) (int64, error)
	// Hint unlocks. The transaction contract, in order:
	//   BEGIN
	//     LockUserForSpend / LockTeamForSpend     -- serialize this account's spends
	//     GetAccountScore                          -- exact, read under the lock
	//     if score < hint.cost: ROLLBACK -> 400
	//     InsertAward(type='hint_unlock', value=-cost)
	//     InsertHintUnlock ... ON CONFLICT DO NOTHING  -- no row => already unlocked
	//     if no row: ROLLBACK -> 400                   -- the award dies with the tx; no orphan charge
	//   COMMIT
	// Serializes this account's spends so the balance can never go negative; the lock is on
	// the account because the balance is a property of the account. Two queries, not one
	// parameterised one: the account model is a table choice, and a table cannot be a bind
	// parameter.
	//
	// FOR NO KEY UPDATE: the FK inserts on submissions/solves/awards take FOR KEY SHARE on
	// this row, which FOR UPDATE would block — a wrong answer must never wait on a lock.
	// It still conflicts with itself, so two concurrent spends by one account serialize.
	LockUserForSpend(ctx context.Context, userID int64) (int64, error)
	// The flag_mode='unique' compare path: sha256(provided) -> one indexed probe on
	// challenge_instances(challenge_id, value_hash). O(1), not O(N_accounts) — and it never does a
	// byte-wise comparison at all, so there is no per-byte timing channel to leak. Stronger than a
	// constant-time compare, not a compromise.
	//
	// The LEFT JOIN is deliberate. A hit with `attributed_account_id IS NULL` is a valid pool flag that
	// was never issued to anyone — the submission is still correct, and the NULL is itself an anti-cheat
	// signal ("solved without ever fetching the artifact"). Correctness does not depend on who the flag
	// was issued to; attribution does.
	//
	// If the returned account differs from the submitter's: accept the solve, silently. The player
	// sees an ordinary `Correct!`. A detector that announces itself is not a detector — reject the flag
	// and the cheater learns the platform tracks provenance, and adapts. The row surfaces in the admin
	// review queue instead, and a human decides.
	//
	// Prefer an issued row over an unissued one when a hash exists across generations, so attribution
	// survives a pool re-upload.
	LookupInstanceByHash(ctx context.Context, arg LookupInstanceByHashParams) (LookupInstanceByHashRow, error)
	// Flips the instance live. Until this row says "true" the policy gate denies every route with
	// setup-incomplete, so a fresh install has no front door. Idempotent: re-running the bootstrap on a
	// live instance rewrites the same value.
	MarkSetupComplete(ctx context.Context) error
	MarkUserVerified(ctx context.Context, userID int64) error
	// The one number that must be right before the event starts. Pool exhaustion mid-CTF is a hard
	// failure by design, and this gauge is what makes it preventable rather than merely loud.
	PoolStats(ctx context.Context) ([]PoolStatsRow, error)
	// Elevate an existing user to a verified admin, by email (case-insensitive, matching
	// users_email_uniq). role is not one of the columns the caps trigger watches, so this needs no
	// exemption. execrows so the caller can distinguish "no such user" from a real promotion.
	PromoteToAdmin(ctx context.Context, email string) (int64, error)
	// min(id) is deterministic and NULL empties the seat when the last member walks out.
	ReassignCaptainAfterLeave(ctx context.Context, arg ReassignCaptainAfterLeaveParams) error
	// One statement, never a read-modify-write — a read-modify-write is a last-writer-wins race, and
	// this is only safe because the caller already holds the challenge lock.
	//
	// GREATEST(n - 1, 0): the first solver pays the max value. NULLIF(c.decay, 0): decay = 0 is already
	// rejected by challenges_dynamic_params, but if it ever leaked in, the value collapses to `minimum`
	// rather than dividing by zero. This updates only the current asking price shown on the board; it
	// does not touch a single past solve — that is the whole point.
	//
	// Integer arithmetic, deliberately — do not "restore" the float8/CEIL version. The same curve runs
	// in Go (scoring.Curve.ValueAt), and float8 does not round identically: for (initial=3901,
	// minimum=205, decay=142) the true value at n = decay is 205, but float64 lands a hair high and
	// CEIL lifts it to 206, so displayed and stored price would diverge for the rest of the event.
	// Over the integers both engines do the same floor: init - floor(D*n^2/decay^2), D = initial - minimum.
	//
	// The two branches clamp n differently, and the difference is not cosmetic:
	//   linear      — n is not clamped; its floor is the outer GREATEST. Clamping at decay would stop
	//                 the decrement early and strand the challenge above `minimum`. The product is
	//                 bigint because decay * n overflows int4 at real-world sizes.
	//   logarithmic — n is clamped at decay: past the knee the curve is flat, so the clamp changes no
	//                 result, and it is what bounds the squared product.
	RecalcChallengeValue(ctx context.Context, challengeID int64) error
	// Replay on connect: newest first, capped, so a client that just opened the stream is caught up
	// without paging. The caller emits them oldest-first.
	RecentNotifications(ctx context.Context, lim int32) ([]Notification, error)
	// Gives one bump back, atomically. The credential budgets are taken before the handler runs and
	// returned when the attempt turns out to have been legitimate, so they count failures without ever
	// reading-then-writing. GREATEST floors it: a refund whose bump landed in the previous window
	// (the request straddled the boundary) must not drive a live counter negative.
	RefundRateLimit(ctx context.Context, arg RefundRateLimitParams) error
	// A revoke is a real DELETE, never a mutation of a ledger row: scoreboard time-travel replays the
	// ledger, so a revoked adjustment must read as never-having-happened, not as a rewritten fact. The
	// WHERE type='standard' inside the delete is the guard — a hint_unlock or first_blood award is a
	// gameplay fact and cannot be deleted through this path whatever id is passed. The surrounding CTE
	// reads the row's type once so the caller can tell "no such award" from "refused: not manual",
	// without a check-then-delete window: the delete's own predicate, not the read, is what protects the
	// gameplay awards.
	// COALESCE to non-null sentinels so the single result row scans cleanly whatever happened: an empty
	// found_type means "no such award" (type is never empty), a zero deleted_id means "not deleted"
	// (ids start at 1). The caller reads the two together to pick the outcome.
	RevokeManualAward(ctx context.Context, id int64) (RevokeManualAwardRow, error)
	// Queue a new address for verification. It becomes live only when a token delivered to it is
	// confirmed (ConfirmEmailChange). users_pending_email_uniq rejects a duplicate queued address —
	// surfaced as a conflict, not a lost check-then-insert race.
	SetPendingEmail(ctx context.Context, arg SetPendingEmailParams) (int64, error)
	// Advances a running task. Written on its own pooled connection, so a caller polling GetTask sees
	// movement while a single-transaction restore is still open and uncommitted.
	SetTaskProgress(ctx context.Context, arg SetTaskProgressParams) error
	// Claims a queued task for a worker. Kept narrow to state='queued' so a redelivered job cannot
	// reset a task that already advanced.
	StartTask(ctx context.Context, arg StartTaskParams) error
	// One row per challenge with its solve count, most-solved first. LEFT JOIN so a challenge nobody has
	// solved appears with zero rather than vanishing — the least-solved tail is the half an organiser
	// actually acts on. The count is the per-challenge distribution the dashboard renders.
	StatsChallengeSolves(ctx context.Context) ([]StatsChallengeSolvesRow, error)
	// Solves bucketed onto a time grid for the dashboard's timeline. The bucket width is a caller-chosen
	// date_trunc field ('hour', 'day', …), passed as a bound parameter — the handler restricts it to a
	// known set, so it is never interpolated SQL. Empty buckets do not appear; a sparse grid is the
	// caller's to fill.
	StatsSolvesOverTime(ctx context.Context, bucket string) ([]StatsSolvesOverTimeRow, error)
	// The attempt log split by status. Every type present is one row; a type nobody hit is simply
	// absent, and the caller fills the zero.
	StatsSubmissionsByType(ctx context.Context) ([]StatsSubmissionsByTypeRow, error)
	// Aggregations for the admin dashboard. Admin-gated: solve distributions are exactly what the
	// scoreboard freeze exists to hide, so this surface never leaks onto a public route. Reads only.
	// The headline counters, one round trip. Scalar sub-selects rather than joins so an empty table
	// reads as zero, not as a missing row.
	StatsTotals(ctx context.Context) (StatsTotalsRow, error)
	// Read-side disambiguation for the roster mutations above: which of captaincy, membership, or the
	// scored guard turned a zero-row write away. Off the hot path — it runs only to shape an error.
	TeamCaptainScored(ctx context.Context, teamID int64) (TeamCaptainScoredRow, error)
	TouchSession(ctx context.Context, idHash []byte) error
	// The seat moves only from the current captain to a current teammate; both facts are the WHERE, so
	// a demoted captain or a non-member target moves zero rows. Transfer carries no scored guard — it
	// changes who holds the seat, never the roster, so it cannot misattribute a solve.
	TransferCaptaincy(ctx context.Context, arg TransferCaptaincyParams) (int64, error)
	// The self-serve profile write: the player-owned fields and nothing else. Identity and
	// moderation state are not in the SET list, so this statement cannot be talked into touching them.
	UpdateOwnProfile(ctx context.Context, arg UpdateOwnProfileParams) (UpdateOwnProfileRow, error)
	// A real password change: the user chose a new password, so a pending forced change is satisfied.
	// One statement, so the flag can never clear without the hash that justifies it.
	UpdatePasswordAndClearForcedChange(ctx context.Context, arg UpdatePasswordAndClearForcedChangeParams) error
	// The rehash-on-login path only: a bcrypt hash from an import, silently upgraded to Argon2id while
	// we hold the plaintext. The password itself has not changed, so must_change_password stays put —
	// a forced user logging in must not discharge the order by the act of logging in.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	// Captaincy is the WHERE clause, not a prior read: zero rows means the caller is not the captain
	// (or has no team) by the time this runs, so there is no window and no forgotten guard.
	UpdateTeamByCaptain(ctx context.Context, arg UpdateTeamByCaptainParams) (int64, error)
	// Rehash-on-join: an imported bcrypt join password is upgraded while the plaintext is in hand.
	UpdateTeamPasswordHash(ctx context.Context, arg UpdateTeamPasswordHashParams) error
	// The self-serve display-name write. name is deliberately not unique (a display name is not an
	// identity), so this is a plain update with no collision to catch. email and moderation state are
	// not in the SET list, so this statement cannot be talked into touching the account's identity.
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error)
	// Runs on every authenticated request. One idempotent statement that cannot raise:
	// there is no error path left to mishandle.
	UpsertTracking(ctx context.Context, arg UpsertTrackingParams) (Tracking, error)
	// One answer per (field, user), so a re-answer is an UPSERT on the UNIQUE(field_id, user_id), never
	// a second row the profile-complete gate would have to pick a winner from.
	UpsertUserFieldEntry(ctx context.Context, arg UpsertUserFieldEntryParams) error
}

var _ Querier = (*Queries)(nil)
