// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const statsChallengeSolves = `-- name: StatsChallengeSolves :many
SELECT c.id AS challenge_id, c.name, c.category, c.value,
       count(s.id)::bigint AS solve_count
  FROM challenges c
  LEFT JOIN solves s ON s.challenge_id = c.id
 GROUP BY c.id, c.name, c.category, c.value
 ORDER BY solve_count DESC, c.id ASC
`

type StatsChallengeSolvesRow struct {
	ChallengeID int64
	Name        string
	Category    string
	Value       int32
	SolveCount  int64
}

// One row per challenge with its solve count, most-solved first. LEFT JOIN so a challenge nobody has
// solved appears with zero rather than vanishing — the least-solved tail is the half an organiser
// actually acts on. The count is the per-challenge distribution the dashboard renders.
func (q *Queries) StatsChallengeSolves(ctx context.Context) ([]StatsChallengeSolvesRow, error) {
	rows, err := q.db.Query(ctx, statsChallengeSolves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsChallengeSolvesRow{}
	for rows.Next() {
		var i StatsChallengeSolvesRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.Name,
			&i.Category,
			&i.Value,
			&i.SolveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSolvesOverTime = `-- name: StatsSolvesOverTime :many
SELECT date_trunc($1::text, date)::timestamptz AS bucket,
       count(*)::bigint AS count
  FROM solves
 GROUP BY bucket
 ORDER BY bucket ASC
`

type StatsSolvesOverTimeRow struct {
	Bucket pgtype.Timestamptz
	Count  int64
}

// Solves bucketed onto a time grid for the dashboard's timeline. The bucket width is a caller-chosen
// date_trunc field ('hour', 'day', …), passed as a bound parameter — the handler restricts it to a
// known set, so it is never interpolated SQL. Empty buckets do not appear; a sparse grid is the
// caller's to fill.
func (q *Queries) StatsSolvesOverTime(ctx context.Context, bucket string) ([]StatsSolvesOverTimeRow, error) {
	rows, err := q.db.Query(ctx, statsSolvesOverTime, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsSolvesOverTimeRow{}
	for rows.Next() {
		var i StatsSolvesOverTimeRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSubmissionsByType = `-- name: StatsSubmissionsByType :many
SELECT type, count(*)::bigint AS count
  FROM submissions
 GROUP BY type
 ORDER BY count DESC, type ASC
`

type StatsSubmissionsByTypeRow struct {
	Type  string
	Count int64
}

// The attempt log split by status. Every type present is one row; a type nobody hit is simply
// absent, and the caller fills the zero.
func (q *Queries) StatsSubmissionsByType(ctx context.Context) ([]StatsSubmissionsByTypeRow, error) {
	rows, err := q.db.Query(ctx, statsSubmissionsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsSubmissionsByTypeRow{}
	for rows.Next() {
		var i StatsSubmissionsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTotals = `-- name: StatsTotals :one

SELECT
    (SELECT count(*) FROM solves)::bigint      AS total_solves,
    (SELECT count(*) FROM submissions)::bigint AS total_submissions,
    (SELECT count(*) FROM awards)::bigint       AS total_awards,
    (SELECT count(DISTINCT challenge_id) FROM solves)::bigint AS solved_challenges
`

type StatsTotalsRow struct {
	TotalSolves      int64
	TotalSubmissions int64
	TotalAwards      int64
	SolvedChallenges int64
}

// Aggregations for the admin dashboard. Admin-gated: solve distributions are exactly what the
// scoreboard freeze exists to hide, so this surface never leaks onto a public route. Reads only.
// The headline counters, one round trip. Scalar sub-selects rather than joins so an empty table
// reads as zero, not as a missing row.
func (q *Queries) StatsTotals(ctx context.Context) (StatsTotalsRow, error) {
	row := q.db.QueryRow(ctx, statsTotals)
	var i StatsTotalsRow
	err := row.Scan(
		&i.TotalSolves,
		&i.TotalSubmissions,
		&i.TotalAwards,
		&i.SolvedChallenges,
	)
	return i, err
}
