// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submissions_log.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSubmissions = `-- name: ListSubmissions :many

SELECT sub.id, sub.date, sub.type, sub.provided, sub.ip,
       sub.challenge_id, c.name AS challenge_name,
       sub.user_id, u.name AS user_name,
       sub.team_id, t.name AS team_name,
       sub.attributed_account_id
  FROM submissions sub
  JOIN      challenges c ON c.id = sub.challenge_id
  LEFT JOIN users      u ON u.id = sub.user_id
  LEFT JOIN teams      t ON t.id = sub.team_id
 WHERE ($1::timestamptz IS NULL
        OR sub.date < $1::timestamptz
        OR (sub.date = $1::timestamptz AND sub.id < $2::bigint))
   AND ($3::text          IS NULL OR sub.type         = $3::text)
   AND ($4::bigint IS NULL OR sub.challenge_id = $4::bigint)
   AND ($5::bigint      IS NULL OR sub.user_id      = $5::bigint)
   AND ($6::bigint      IS NULL OR sub.team_id      = $6::bigint)
 ORDER BY sub.date DESC, sub.id DESC
 LIMIT $7::int
`

type ListSubmissionsParams struct {
	BeforeDate  pgtype.Timestamptz
	BeforeID    *int64
	Type        *string
	ChallengeID *int64
	UserID      *int64
	TeamID      *int64
	Lim         int32
}

type ListSubmissionsRow struct {
	ID                  int64
	Date                pgtype.Timestamptz
	Type                string
	Provided            string
	Ip                  *netip.Addr
	ChallengeID         int64
	ChallengeName       string
	UserID              int64
	UserName            *string
	TeamID              *int64
	TeamName            *string
	AttributedAccountID *int64
}

// The live submissions feed an organiser watches during an event and mines for cheat review.
// Read-only over the append-only attempt log; it never joins its way to a scoring decision.
// Keyset pagination, newest first, on the (date, id) cursor — never OFFSET, which re-counts the
// skipped rows on every page and drifts as new attempts land mid-scroll during a live event. A NULL
// cursor is the first page; otherwise the strict (date, id) < (before_date, before_id) tuple resumes
// exactly after the last row already seen. The display joins are LEFT so a challenge or account whose
// name cannot be resolved never drops the attempt from a cheat-review feed.
//
// attributed_account_id is passed through verbatim — it is a fact stamped inside the submit
// transaction, never re-derived by joining the (mutable, rotatable) flag issue here.
//
// Ordering matches submissions_admin_list_idx and submissions_admin_type_idx (both DESC on date),
// so the unfiltered feed and the `type` facet each walk an index backwards rather than sort.
func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.BeforeDate,
		arg.BeforeID,
		arg.Type,
		arg.ChallengeID,
		arg.UserID,
		arg.TeamID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsRow{}
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Type,
			&i.Provided,
			&i.Ip,
			&i.ChallengeID,
			&i.ChallengeName,
			&i.UserID,
			&i.UserName,
			&i.TeamID,
			&i.TeamName,
			&i.AttributedAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
