// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
)

const enqueueTask = `-- name: EnqueueTask :one

INSERT INTO tasks (kind, state, created_by)
VALUES ($1, 'queued', $2)
RETURNING id, kind, state, progress, detail, error, created_by, created_at, updated_at
`

type EnqueueTaskParams struct {
	Kind      string
	CreatedBy *int64
}

// Async admin operations (backup, restore, import) tracked in the tasks table. River owns the
// execution; this table owns the state a poller reads. The progress writes below run on a
// connection SEPARATE from the restore transaction on purpose: a restore is one transaction so its
// own progress UPDATEs would be invisible until it commits.
// Inserts a queued task. The tasks_one_in_flight partial unique index raises 23505 when a task of
// the same kind is already queued or running — that unique violation IS the single-in-flight
// refusal, surfaced to the caller as 409, never a second job queued to collide.
func (q *Queries) EnqueueTask(ctx context.Context, arg EnqueueTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, enqueueTask, arg.Kind, arg.CreatedBy)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.Progress,
		&i.Detail,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks
   SET state = 'failed', error = $1, updated_at = now()
 WHERE id = $2
`

type FailTaskParams struct {
	Error *string
	ID    int64
}

// A failure is loud and terminal: the error text is stamped for the operator and the row leaves the
// in-flight set, freeing the kind for another attempt.
func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.Exec(ctx, failTask, arg.Error, arg.ID)
	return err
}

const finishTask = `-- name: FinishTask :exec
UPDATE tasks
   SET state = 'succeeded', progress = 100, detail = $1, updated_at = now()
 WHERE id = $2
`

type FinishTaskParams struct {
	Detail *string
	ID     int64
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) error {
	_, err := q.db.Exec(ctx, finishTask, arg.Detail, arg.ID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, kind, state, progress, detail, error, created_by, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.State,
		&i.Progress,
		&i.Detail,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskProgress = `-- name: SetTaskProgress :exec
UPDATE tasks
   SET progress = $1, detail = $2, updated_at = now()
 WHERE id = $3 AND state = 'running'
`

type SetTaskProgressParams struct {
	Progress int32
	Detail   *string
	ID       int64
}

// Advances a running task. Written on its own pooled connection, so a caller polling GetTask sees
// movement while a single-transaction restore is still open and uncommitted.
func (q *Queries) SetTaskProgress(ctx context.Context, arg SetTaskProgressParams) error {
	_, err := q.db.Exec(ctx, setTaskProgress, arg.Progress, arg.Detail, arg.ID)
	return err
}

const startTask = `-- name: StartTask :exec
UPDATE tasks
   SET state = 'running', progress = $1, detail = $2, updated_at = now()
 WHERE id = $3 AND state = 'queued'
`

type StartTaskParams struct {
	Progress int32
	Detail   *string
	ID       int64
}

// Claims a queued task for a worker. Kept narrow to state='queued' so a redelivered job cannot
// reset a task that already advanced.
func (q *Queries) StartTask(ctx context.Context, arg StartTaskParams) error {
	_, err := q.db.Exec(ctx, startTask, arg.Progress, arg.Detail, arg.ID)
	return err
}
