// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptCaptainlessTeam = `-- name: AdoptCaptainlessTeam :exec
UPDATE teams t SET captain_id = $1
 WHERE t.id = $2 AND t.captain_id IS NULL
   AND (SELECT count(*) FROM users u WHERE u.team_id = t.id) = 1
`

type AdoptCaptainlessTeamParams struct {
	UserID *int64
	TeamID int64
}

// A sole member adopts a captainless team (the captain's user row was deleted, FK SET NULL).
func (q *Queries) AdoptCaptainlessTeam(ctx context.Context, arg AdoptCaptainlessTeamParams) error {
	_, err := q.db.Exec(ctx, adoptCaptainlessTeam, arg.UserID, arg.TeamID)
	return err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name, password_hash, captain_id)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateTeamParams struct {
	Name         string
	PasswordHash *string
	CaptainID    *int64
}

type CreateTeamRow struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

// Team enrollment and the team profile read models.
// The unique name index and the num_teams caps trigger arbitrate: a duplicate raises 23505 and an
// over-cap insert raises a check_violation on the INSERT itself, never in a prior SELECT.
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.PasswordHash, arg.CaptainID)
	var i CreateTeamRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const enrollUser = `-- name: EnrollUser :execrows
UPDATE users SET team_id = $1
 WHERE id = $2 AND team_id IS NULL
`

type EnrollUserParams struct {
	TeamID *int64
	UserID int64
}

// "Already on a team" is the WHERE clause, not a prior read: zero rows means the user was enrolled
// elsewhere by the time this ran. The caps trigger enforces team_size on the same statement.
func (q *Queries) EnrollUser(ctx context.Context, arg EnrollUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, enrollUser, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnTeam = `-- name: GetOwnTeam :one
SELECT t.id, t.name, t.website, t.affiliation, t.country, t.created_at, t.captain_id,
       (COALESCE((SELECT sum(s.value) FROM solves s WHERE s.team_id = t.id), 0)
      + COALESCE((SELECT sum(a.value) FROM awards a WHERE a.team_id = t.id), 0))::bigint AS score
  FROM teams t
  JOIN users u ON u.team_id = t.id
 WHERE u.id = $1
`

type GetOwnTeamRow struct {
	ID          int64
	Name        string
	Website     *string
	Affiliation *string
	Country     *string
	CreatedAt   pgtype.Timestamptz
	CaptainID   *int64
	Score       int64
}

func (q *Queries) GetOwnTeam(ctx context.Context, userID int64) (GetOwnTeamRow, error) {
	row := q.db.QueryRow(ctx, getOwnTeam, userID)
	var i GetOwnTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.CreatedAt,
		&i.CaptainID,
		&i.Score,
	)
	return i, err
}

const getTeamForJoin = `-- name: GetTeamForJoin :one
SELECT id, password_hash, banned FROM teams WHERE name = $1
`

type GetTeamForJoinRow struct {
	ID           int64
	PasswordHash *string
	Banned       bool
}

func (q *Queries) GetTeamForJoin(ctx context.Context, name string) (GetTeamForJoinRow, error) {
	row := q.db.QueryRow(ctx, getTeamForJoin, name)
	var i GetTeamForJoinRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Banned)
	return i, err
}

const getTeamPublicProfile = `-- name: GetTeamPublicProfile :one
SELECT t.id, t.name, t.website, t.affiliation, t.country, t.created_at,
       (COALESCE((SELECT sum(s.value) FROM solves s WHERE s.team_id = t.id), 0)
      + COALESCE((SELECT sum(a.value) FROM awards a WHERE a.team_id = t.id), 0))::bigint AS score
  FROM teams t
 WHERE t.id = $1 AND t.hidden = false AND t.banned = false
`

type GetTeamPublicProfileRow struct {
	ID          int64
	Name        string
	Website     *string
	Affiliation *string
	Country     *string
	CreatedAt   pgtype.Timestamptz
	Score       int64
}

// Hidden and banned teams 404 publicly, matching the board and the solve lists. The score sums
// the stamped solves.team_id ledger — the same legs the scoreboard reads.
func (q *Queries) GetTeamPublicProfile(ctx context.Context, teamID int64) (GetTeamPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getTeamPublicProfile, teamID)
	var i GetTeamPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.CreatedAt,
		&i.Score,
	)
	return i, err
}

const leaveTeam = `-- name: LeaveTeam :execrows
UPDATE users u SET team_id = NULL
 WHERE u.id = $1 AND u.team_id = $2
   AND NOT EXISTS (SELECT 1 FROM solves s WHERE s.team_id = u.team_id)
`

type LeaveTeamParams struct {
	UserID int64
	TeamID *int64
}

// Departure is forbidden once the team has scored: solves stamp team_id, so a roster that can
// shrink after scoring would misattribute the board. The condition lives in the statement so two
// racing writes (a leave and a solve) serialize in the database, not in Go.
func (q *Queries) LeaveTeam(ctx context.Context, arg LeaveTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveTeam, arg.UserID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.name,
       COALESCE(u.id = t.captain_id, false)::boolean AS captain,
       (SELECT count(*) FROM solves s WHERE s.team_id = t.id AND s.user_id = u.id)::bigint AS solve_count,
       COALESCE((SELECT sum(s.value) FROM solves s WHERE s.team_id = t.id AND s.user_id = u.id), 0)::bigint AS points
  FROM users u
  JOIN teams t ON t.id = u.team_id
 WHERE u.team_id = $1
   AND ($2::boolean OR (u.hidden = false AND u.banned = false))
 ORDER BY u.id
`

type ListTeamMembersParams struct {
	TeamID        *int64
	IncludeMasked bool
}

type ListTeamMembersRow struct {
	ID         int64
	Name       string
	Captain    bool
	SolveCount int64
	Points     int64
}

// Per-member attribution reads the stamped solves.team_id, so points stay with the team that
// scored them regardless of later roster churn. include_masked lifts the hidden/banned member
// filter for the team's own view.
func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.TeamID, arg.IncludeMasked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Captain,
			&i.SolveCount,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCaptainAfterLeave = `-- name: ReassignCaptainAfterLeave :exec
UPDATE teams t
   SET captain_id = (SELECT min(u.id) FROM users u WHERE u.team_id = t.id)
 WHERE t.id = $1 AND t.captain_id = $2
`

type ReassignCaptainAfterLeaveParams struct {
	TeamID int64
	UserID *int64
}

// min(id) is deterministic and NULL empties the seat when the last member walks out.
func (q *Queries) ReassignCaptainAfterLeave(ctx context.Context, arg ReassignCaptainAfterLeaveParams) error {
	_, err := q.db.Exec(ctx, reassignCaptainAfterLeave, arg.TeamID, arg.UserID)
	return err
}

const updateTeamPasswordHash = `-- name: UpdateTeamPasswordHash :exec
UPDATE teams SET password_hash = $1 WHERE id = $2
`

type UpdateTeamPasswordHashParams struct {
	PasswordHash *string
	TeamID       int64
}

// Rehash-on-join: an imported bcrypt join password is upgraded while the plaintext is in hand.
func (q *Queries) UpdateTeamPasswordHash(ctx context.Context, arg UpdateTeamPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateTeamPasswordHash, arg.PasswordHash, arg.TeamID)
	return err
}
