// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptCaptainlessTeam = `-- name: AdoptCaptainlessTeam :exec
UPDATE teams t SET captain_id = $1
 WHERE t.id = $2 AND t.captain_id IS NULL
   AND (SELECT count(*) FROM users u WHERE u.team_id = t.id) = 1
`

type AdoptCaptainlessTeamParams struct {
	UserID *int64
	TeamID int64
}

// A sole member adopts a captainless team (the captain's user row was deleted, FK SET NULL).
func (q *Queries) AdoptCaptainlessTeam(ctx context.Context, arg AdoptCaptainlessTeamParams) error {
	_, err := q.db.Exec(ctx, adoptCaptainlessTeam, arg.UserID, arg.TeamID)
	return err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name, password_hash, captain_id)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateTeamParams struct {
	Name         string
	PasswordHash string
	CaptainID    *int64
}

type CreateTeamRow struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

// Team enrollment and the team profile read models.
// The unique name index and the num_teams caps trigger arbitrate: a duplicate raises 23505 and an
// over-cap insert raises a check_violation on the INSERT itself, never in a prior SELECT.
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.PasswordHash, arg.CaptainID)
	var i CreateTeamRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const disbandTeam = `-- name: DisbandTeam :execrows
DELETE FROM teams t
 WHERE t.id = (SELECT u.team_id FROM users u WHERE u.id = $1)
   AND t.captain_id = $1
`

// Disband is a plain delete guarded only by captaincy. The RESTRICT foreign keys from the ledger
// (submissions, solves, awards, hint_unlocks) refuse the delete the instant the team has any
// history, surfacing as a foreign_key_violation the API turns into a conflict — a scored team is
// retired by hide/ban, never erased. Any remaining members fall to team_id NULL via the ON DELETE
// SET NULL on users, so a zero-history team created by mistake vanishes cleanly.
func (q *Queries) DisbandTeam(ctx context.Context, captainID int64) (int64, error) {
	result, err := q.db.Exec(ctx, disbandTeam, captainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enrollUser = `-- name: EnrollUser :execrows
UPDATE users SET team_id = $1
 WHERE id = $2 AND team_id IS NULL
`

type EnrollUserParams struct {
	TeamID *int64
	UserID int64
}

// "Already on a team" is the WHERE clause, not a prior read: zero rows means the user was enrolled
// elsewhere by the time this ran. The caps trigger enforces team_size on the same statement.
func (q *Queries) EnrollUser(ctx context.Context, arg EnrollUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, enrollUser, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnTeam = `-- name: GetOwnTeam :one
SELECT t.id, t.name, t.email, t.website, t.affiliation, t.country, t.created_at, t.captain_id,
       (COALESCE((SELECT sum(s.value) FROM solves s WHERE s.team_id = t.id), 0)
      + COALESCE((SELECT sum(a.value) FROM awards a WHERE a.team_id = t.id), 0))::bigint AS score
  FROM teams t
  JOIN users u ON u.team_id = t.id
 WHERE u.id = $1
`

type GetOwnTeamRow struct {
	ID          int64
	Name        string
	Email       *string
	Website     *string
	Affiliation *string
	Country     *string
	CreatedAt   pgtype.Timestamptz
	CaptainID   *int64
	Score       int64
}

// No cutoff: an account always sees its own live score, freeze or not. Withholding it would tell
// the team nothing an attacker wants and everything they already know.
// t.email rides along because this is the team's own view — the public profile never selects it.
func (q *Queries) GetOwnTeam(ctx context.Context, userID int64) (GetOwnTeamRow, error) {
	row := q.db.QueryRow(ctx, getOwnTeam, userID)
	var i GetOwnTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.CreatedAt,
		&i.CaptainID,
		&i.Score,
	)
	return i, err
}

const getTeamForJoin = `-- name: GetTeamForJoin :one
SELECT id, password_hash, banned FROM teams WHERE name = $1
`

type GetTeamForJoinRow struct {
	ID           int64
	PasswordHash string
	Banned       bool
}

func (q *Queries) GetTeamForJoin(ctx context.Context, name string) (GetTeamForJoinRow, error) {
	row := q.db.QueryRow(ctx, getTeamForJoin, name)
	var i GetTeamForJoinRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Banned)
	return i, err
}

const getTeamPublicProfile = `-- name: GetTeamPublicProfile :one
SELECT t.id, t.name, t.website, t.affiliation, t.country, t.created_at,
       (COALESCE((SELECT sum(s.value) FROM solves s
                   WHERE s.team_id = t.id
                     AND ($1::timestamptz IS NULL
                          OR s.date < $1::timestamptz)), 0)
      + COALESCE((SELECT sum(a.value) FROM awards a
                   WHERE a.team_id = t.id
                     AND ($1::timestamptz IS NULL
                          OR a.date < $1::timestamptz)), 0))::bigint AS score
  FROM teams t
 WHERE t.id = $2 AND t.hidden = false AND t.banned = false
`

type GetTeamPublicProfileParams struct {
	Cutoff pgtype.Timestamptz
	TeamID int64
}

type GetTeamPublicProfileRow struct {
	ID          int64
	Name        string
	Website     *string
	Affiliation *string
	Country     *string
	CreatedAt   pgtype.Timestamptz
	Score       int64
}

// Hidden and banned teams 404 publicly, matching the board and the solve lists. The score sums
// the stamped solves.team_id ledger — the same legs the scoreboard reads, and it takes the same
// freeze horizon: cutoff is strict `<`, NULL = live. Both legs carry it, because a public team
// page that sums live is the frozen board read one team at a time.
func (q *Queries) GetTeamPublicProfile(ctx context.Context, arg GetTeamPublicProfileParams) (GetTeamPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getTeamPublicProfile, arg.Cutoff, arg.TeamID)
	var i GetTeamPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Affiliation,
		&i.Country,
		&i.CreatedAt,
		&i.Score,
	)
	return i, err
}

const kickMember = `-- name: KickMember :execrows
UPDATE users m SET team_id = NULL
 WHERE m.id = $1
   AND m.id <> $2
   AND EXISTS (SELECT 1 FROM teams t
                WHERE t.id = m.team_id AND t.captain_id = $2)
   AND NOT EXISTS (SELECT 1 FROM solves s WHERE s.team_id = m.team_id)
`

type KickMemberParams struct {
	MemberID  int64
	CaptainID int64
}

// Removal is the captain's alone, over a current teammate who is not the captain, and only while
// the team has never scored. All three live in the WHERE, so a demoted captain, a stale target, or
// a team already on the board changes zero rows — there is no check to race past. The scored guard
// mirrors leave: solves stamp team_id, so a roster that can shrink after scoring would leave the
// board attributing points to a lineup nobody can reconstruct.
func (q *Queries) KickMember(ctx context.Context, arg KickMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, kickMember, arg.MemberID, arg.CaptainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaveTeam = `-- name: LeaveTeam :execrows
UPDATE users u SET team_id = NULL
 WHERE u.id = $1 AND u.team_id = $2
   AND NOT EXISTS (SELECT 1 FROM solves s WHERE s.team_id = u.team_id)
`

type LeaveTeamParams struct {
	UserID int64
	TeamID *int64
}

// Departure is forbidden once the team has scored: solves stamp team_id, so a roster that can
// shrink after scoring would misattribute the board. The condition lives in the statement so two
// racing writes (a leave and a solve) serialize in the database, not in Go.
func (q *Queries) LeaveTeam(ctx context.Context, arg LeaveTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveTeam, arg.UserID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.name,
       COALESCE(u.id = t.captain_id, false)::boolean AS captain,
       (SELECT count(*) FROM solves s
         WHERE s.team_id = t.id AND s.user_id = u.id
           AND ($1::timestamptz IS NULL
                OR s.date < $1::timestamptz))::bigint AS solve_count,
       COALESCE((SELECT sum(s.value) FROM solves s
                  WHERE s.team_id = t.id AND s.user_id = u.id
                    AND ($1::timestamptz IS NULL
                         OR s.date < $1::timestamptz)), 0)::bigint AS points
  FROM users u
  JOIN teams t ON t.id = u.team_id
 WHERE u.team_id = $2
   AND ($3::boolean OR (u.hidden = false AND u.banned = false))
 ORDER BY u.id
 -- Defence in depth: a roster is already bounded by the team_size cap at enrollment, so this trims
 -- nothing a real team can reach. It exists so the query is bounded by its own text, not by trust in
 -- a config value, on a route any player can hit.
 LIMIT 1000
`

type ListTeamMembersParams struct {
	Cutoff        pgtype.Timestamptz
	TeamID        *int64
	IncludeMasked bool
}

type ListTeamMembersRow struct {
	ID         int64
	Name       string
	Captain    bool
	SolveCount int64
	Points     int64
}

// Per-member attribution reads the stamped solves.team_id, so points stay with the team that
// scored them regardless of later roster churn. include_masked lifts the hidden/banned member
// filter for the team's own view; cutoff is the freeze horizon (strict `<`, NULL = live) for the
// public one, where an unclamped per-member breakdown says who scored what during the freeze.
func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.Cutoff, arg.TeamID, arg.IncludeMasked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Captain,
			&i.SolveCount,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamSolves = `-- name: ListTeamSolves :many
SELECT c.id AS challenge_id, c.name AS challenge_name, c.category,
       s.value::int AS value, s.date
  FROM solves s
  JOIN challenges c ON c.id = s.challenge_id
 WHERE s.team_id = $1
   AND c.state = 'visible'
   AND ($2::timestamptz IS NULL OR s.date < $2::timestamptz)
 ORDER BY s.date DESC, s.id DESC
 LIMIT 100
`

type ListTeamSolvesParams struct {
	TeamID *int64
	Cutoff pgtype.Timestamptz
}

type ListTeamSolvesRow struct {
	ChallengeID   int64
	ChallengeName string
	Category      string
	Value         int32
	Date          pgtype.Timestamptz
}

// The team's solved challenges, newest first, under the same freeze horizon as the score above
// (cutoff strict `<`, NULL = live). Only visible challenges are listed: the headline score sums the
// whole ledger, but naming a hidden challenge here would leak its existence, so the itemised history
// hides it exactly as the per-challenge solve list and the user profile's history do.
//
// Bounded to the most recent page, matching ListUserSolves: this rides inside a public profile
// document, not a paged feed, and the total is summed separately over the whole ledger — so the cap
// trims only the tail of the view, never the score. Without it a heavy team's page is a slow query
// and a one-request scrape at a large event.
func (q *Queries) ListTeamSolves(ctx context.Context, arg ListTeamSolvesParams) ([]ListTeamSolvesRow, error) {
	rows, err := q.db.Query(ctx, listTeamSolves, arg.TeamID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamSolvesRow{}
	for rows.Next() {
		var i ListTeamSolvesRow
		if err := rows.Scan(
			&i.ChallengeID,
			&i.ChallengeName,
			&i.Category,
			&i.Value,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCaptainAfterLeave = `-- name: ReassignCaptainAfterLeave :exec
UPDATE teams t
   SET captain_id = (SELECT min(u.id) FROM users u WHERE u.team_id = t.id)
 WHERE t.id = $1 AND t.captain_id = $2
`

type ReassignCaptainAfterLeaveParams struct {
	TeamID int64
	UserID *int64
}

// min(id) is deterministic and NULL empties the seat when the last member walks out.
func (q *Queries) ReassignCaptainAfterLeave(ctx context.Context, arg ReassignCaptainAfterLeaveParams) error {
	_, err := q.db.Exec(ctx, reassignCaptainAfterLeave, arg.TeamID, arg.UserID)
	return err
}

const setJoinSecretByCaptain = `-- name: SetJoinSecretByCaptain :execrows
UPDATE teams SET password_hash = $1 WHERE captain_id = $2
`

type SetJoinSecretByCaptainParams struct {
	PasswordHash string
	CaptainID    *int64
}

// Captaincy is the WHERE clause, so a demoted captain's in-flight rotate affects zero rows rather
// than racing past a check. Zero rows also covers a caller who is on no team at all.
func (q *Queries) SetJoinSecretByCaptain(ctx context.Context, arg SetJoinSecretByCaptainParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJoinSecretByCaptain, arg.PasswordHash, arg.CaptainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const teamCaptainScored = `-- name: TeamCaptainScored :one
SELECT t.captain_id,
       EXISTS (SELECT 1 FROM solves s WHERE s.team_id = t.id)::boolean AS scored
  FROM teams t WHERE t.id = $1
`

type TeamCaptainScoredRow struct {
	CaptainID *int64
	Scored    bool
}

// Read-side disambiguation for the roster mutations above: which of captaincy, membership, or the
// scored guard turned a zero-row write away. Off the hot path — it runs only to shape an error.
func (q *Queries) TeamCaptainScored(ctx context.Context, teamID int64) (TeamCaptainScoredRow, error) {
	row := q.db.QueryRow(ctx, teamCaptainScored, teamID)
	var i TeamCaptainScoredRow
	err := row.Scan(&i.CaptainID, &i.Scored)
	return i, err
}

const transferCaptaincy = `-- name: TransferCaptaincy :execrows
UPDATE teams t SET captain_id = $1
 WHERE t.captain_id = $2
   AND EXISTS (SELECT 1 FROM users m WHERE m.id = $1 AND m.team_id = t.id)
`

type TransferCaptaincyParams struct {
	NewCaptainID *int64
	CaptainID    *int64
}

// The seat moves only from the current captain to a current teammate; both facts are the WHERE, so
// a demoted captain or a non-member target moves zero rows. Transfer carries no scored guard — it
// changes who holds the seat, never the roster, so it cannot misattribute a solve.
func (q *Queries) TransferCaptaincy(ctx context.Context, arg TransferCaptaincyParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferCaptaincy, arg.NewCaptainID, arg.CaptainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTeamByCaptain = `-- name: UpdateTeamByCaptain :one
UPDATE teams t SET
    email       = CASE WHEN $1::bool THEN NULL
                       ELSE COALESCE($2, t.email) END,
    website     = CASE WHEN $3::bool THEN NULL
                       ELSE COALESCE($4, t.website) END,
    affiliation = CASE WHEN $5::bool THEN NULL
                       ELSE COALESCE($6, t.affiliation) END,
    country     = CASE WHEN $7::bool THEN NULL
                       ELSE COALESCE($8, t.country) END
WHERE t.id = (SELECT u.team_id FROM users u WHERE u.id = $9)
  AND t.captain_id = $9
RETURNING t.id
`

type UpdateTeamByCaptainParams struct {
	ClearEmail       bool
	Email            *string
	ClearWebsite     bool
	Website          *string
	ClearAffiliation bool
	Affiliation      *string
	ClearCountry     bool
	Country          *string
	UserID           int64
}

// Captaincy is the WHERE clause, not a prior read: zero rows means the caller is not the captain
// (or has no team) by the time this runs, so there is no window and no forgotten guard.
func (q *Queries) UpdateTeamByCaptain(ctx context.Context, arg UpdateTeamByCaptainParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateTeamByCaptain,
		arg.ClearEmail,
		arg.Email,
		arg.ClearWebsite,
		arg.Website,
		arg.ClearAffiliation,
		arg.Affiliation,
		arg.ClearCountry,
		arg.Country,
		arg.UserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateTeamPasswordHash = `-- name: UpdateTeamPasswordHash :exec
UPDATE teams SET password_hash = $1 WHERE id = $2
`

type UpdateTeamPasswordHashParams struct {
	PasswordHash string
	TeamID       int64
}

// Rehash-on-join: an imported bcrypt join password is upgraded while the plaintext is in hand.
func (q *Queries) UpdateTeamPasswordHash(ctx context.Context, arg UpdateTeamPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateTeamPasswordHash, arg.PasswordHash, arg.TeamID)
	return err
}
