// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_roster.sql

package db

import (
	"context"
)

const adminDetachMember = `-- name: AdminDetachMember :execrows
UPDATE users u SET team_id = NULL
 WHERE u.id = $1 AND u.team_id = $2
`

type AdminDetachMemberParams struct {
	UserID int64
	TeamID *int64
}

// Membership is the WHERE, not a prior read: zero rows means the user was not on that team by the
// time this ran, and the caller turns that into a named refusal instead of a silent success.
//
// Unlike the captain's kick this carries no "team has never scored" guard, and that is deliberate.
// Every ledger row stamps team_id when it is written, so points already earned stay credited to the
// team that earned them no matter who leaves afterwards. Fixing a roster mid-event is the entire
// reason this statement exists; the audit trigger records who did it.
func (q *Queries) AdminDetachMember(ctx context.Context, arg AdminDetachMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminDetachMember, arg.UserID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminListTeamMembers = `-- name: AdminListTeamMembers :many

SELECT u.id, u.name, u.email, u.banned, u.hidden,
       COALESCE(u.id = t.captain_id, false)::boolean AS captain
  FROM users u
  JOIN teams t ON t.id = u.team_id
 WHERE u.team_id = $1
 ORDER BY u.id
`

type AdminListTeamMembersRow struct {
	ID      int64
	Name    string
	Email   string
	Banned  bool
	Hidden  bool
	Captain bool
}

// Admin-side roster repair: an organizer acting on someone else's team. The captain's own
// kick/leave path lives in teams.sql; these are the organizer's equivalents, and they differ in
// exactly one way — see AdminDetachMember.
// The admin roster view. email is admin-only data, which is why it is selected here and never on
// the public team page.
func (q *Queries) AdminListTeamMembers(ctx context.Context, teamID *int64) ([]AdminListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, adminListTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTeamMembersRow{}
	for rows.Next() {
		var i AdminListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Banned,
			&i.Hidden,
			&i.Captain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTeamExists = `-- name: AdminTeamExists :one
SELECT EXISTS (SELECT 1 FROM teams t WHERE t.id = $1)::boolean AS present
`

// Read-side disambiguation only: it shapes "no such team" versus "user is not on that team" after a
// zero-row write. The foreign key, not this, is what actually refuses a bad target.
func (q *Queries) AdminTeamExists(ctx context.Context, teamID int64) (bool, error) {
	row := q.db.QueryRow(ctx, adminTeamExists, teamID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const adminTeamIsBanned = `-- name: AdminTeamIsBanned :one
SELECT t.banned FROM teams t WHERE t.id = $1
`

// Whether a move's destination would wall its arrival out of the API.
func (q *Queries) AdminTeamIsBanned(ctx context.Context, teamID int64) (bool, error) {
	row := q.db.QueryRow(ctx, adminTeamIsBanned, teamID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}
