// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unlocks.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnlockedHintPrerequisites = `-- name: CountUnlockedHintPrerequisites :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT count(DISTINCT hu.hint_id)::bigint
  FROM hint_unlocks hu
  CROSS JOIN mode m
 WHERE hu.hint_id = ANY($1::bigint[])
   AND CASE WHEN m.user_mode = 'teams'
            THEN hu.team_id = $2::bigint
            ELSE hu.user_id = $3::bigint
       END
`

type CountUnlockedHintPrerequisitesParams struct {
	Prerequisites []int64
	TeamID        *int64
	UserID        int64
}

// The prerequisite gate for hint unlocks. A hint can require other hints to be unlocked first;
// this counts how many of them this account already owns, and the caller compares that against the
// number required. Hint prerequisites carry no anonymize flag — a locked hint is simply not
// purchasable until its prerequisites are unlocked.
func (q *Queries) CountUnlockedHintPrerequisites(ctx context.Context, arg CountUnlockedHintPrerequisitesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnlockedHintPrerequisites, arg.Prerequisites, arg.TeamID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAccountScore = `-- name: GetAccountScore :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT (
    COALESCE((SELECT sum(s.value)
                FROM solves s
                CROSS JOIN mode m
               WHERE CASE WHEN m.user_mode = 'teams'
                          THEN s.team_id = $1::bigint
                          ELSE s.user_id = $2::bigint
                     END), 0)
  + COALESCE((SELECT sum(a.value)
                FROM awards a
                CROSS JOIN mode m
               WHERE CASE WHEN m.user_mode = 'teams'
                          THEN a.team_id = $1::bigint
                          ELSE a.user_id = $2::bigint
                     END), 0)
)::bigint AS score
`

type GetAccountScoreParams struct {
	TeamID *int64
	UserID int64
}

// The affordability read: an exact SUM over the ledger — a cached balance is an opinion
// about the past — taken under the spend lock so no concurrent spend can land between
// this read and the insert that follows. awards.value may be negative (that is what a
// hint spend is). The account model comes from `instance`, never a caller-supplied flag.
func (q *Queries) GetAccountScore(ctx context.Context, arg GetAccountScoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountScore, arg.TeamID, arg.UserID)
	var score int64
	err := row.Scan(&score)
	return score, err
}

const getHint = `-- name: GetHint :one
SELECT h.id, h.challenge_id, h.title, h.content, h.cost, h.requirements, h.position,
       c.requirements AS challenge_requirements
  FROM hints h
  JOIN challenges c ON c.id = h.challenge_id
 WHERE h.id = $1
   AND h.challenge_id = $2
   AND c.state = 'visible'
`

type GetHintParams struct {
	HintID      int64
	ChallengeID int64
}

type GetHintRow struct {
	ID                    int64
	ChallengeID           int64
	Title                 *string
	Content               string
	Cost                  int32
	Requirements          json.RawMessage
	Position              int32
	ChallengeRequirements json.RawMessage
}

// The challenge id from the URL is part of the key: a hint reached through the wrong challenge —
// or through a hidden one — is simply not found.
//
// The challenge's requirements ride along because a hint is not purchasable independently of the
// challenge that owns it: the unlock is gated on the challenge's prerequisites as well as the
// hint's own, and reading them here keeps that gate on the row we already had to fetch.
func (q *Queries) GetHint(ctx context.Context, arg GetHintParams) (GetHintRow, error) {
	row := q.db.QueryRow(ctx, getHint, arg.HintID, arg.ChallengeID)
	var i GetHintRow
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Content,
		&i.Cost,
		&i.Requirements,
		&i.Position,
		&i.ChallengeRequirements,
	)
	return i, err
}

const getHintUnlock = `-- name: GetHintUnlock :one
WITH mode AS (
    SELECT user_mode FROM instance
)
SELECT hu.id
  FROM hint_unlocks hu
  CROSS JOIN mode m
 WHERE hu.hint_id = $1
   AND CASE WHEN m.user_mode = 'teams'
            THEN hu.team_id = $2::bigint
            ELSE hu.user_id = $3::bigint
       END
`

type GetHintUnlockParams struct {
	HintID int64
	TeamID *int64
	UserID int64
}

// Read under the account spend lock, which is what makes it safe to branch on. It runs
// Before affordability: an account that owns a hint and has since spent down to zero
// must be told it owns the hint — not that it cannot afford it.
func (q *Queries) GetHintUnlock(ctx context.Context, arg GetHintUnlockParams) (int64, error) {
	row := q.db.QueryRow(ctx, getHintUnlock, arg.HintID, arg.TeamID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertHintUnlock = `-- name: InsertHintUnlock :one
INSERT INTO hint_unlocks (hint_id, user_id, team_id, award_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, date
`

type InsertHintUnlockParams struct {
	HintID  int64
	UserID  int64
	TeamID  *int64
	AwardID int64
}

type InsertHintUnlockRow struct {
	ID   int64
	Date pgtype.Timestamptz
}

// The duplicate check IS the constraint, never a SELECT. Zero rows (pgx.ErrNoRows) means
// already unlocked, and the caller must roll back: the award inserted a moment earlier is
// a charge, and committing it without the unlock row it paid for is a double-charge.
// `award_id` is NOT NULL UNIQUE REFERENCES awards(id) — exactly one charge per unlock.
func (q *Queries) InsertHintUnlock(ctx context.Context, arg InsertHintUnlockParams) (InsertHintUnlockRow, error) {
	row := q.db.QueryRow(ctx, insertHintUnlock,
		arg.HintID,
		arg.UserID,
		arg.TeamID,
		arg.AwardID,
	)
	var i InsertHintUnlockRow
	err := row.Scan(&i.ID, &i.Date)
	return i, err
}

const lockTeamForSpend = `-- name: LockTeamForSpend :one
SELECT id FROM teams WHERE id = $1 FOR NO KEY UPDATE
`

// The teams-mode counterpart. Same lock strength, same reasoning.
func (q *Queries) LockTeamForSpend(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockTeamForSpend, teamID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockUserForSpend = `-- name: LockUserForSpend :one

SELECT id FROM users WHERE id = $1 FOR NO KEY UPDATE
`

// Hint unlocks. The transaction contract, in order:
//
//	BEGIN
//	  LockUserForSpend / LockTeamForSpend     -- serialize this account's spends
//	  GetAccountScore                          -- exact, read under the lock
//	  if score < hint.cost: ROLLBACK -> 400
//	  InsertAward(type='hint_unlock', value=-cost)
//	  InsertHintUnlock ... ON CONFLICT DO NOTHING  -- no row => already unlocked
//	  if no row: ROLLBACK -> 400                   -- the award dies with the tx; no orphan charge
//	COMMIT
//
// Serializes this account's spends so the balance can never go negative; the lock is on
// the account because the balance is a property of the account. Two queries, not one
// parameterised one: the account model is a table choice, and a table cannot be a bind
// parameter.
//
// FOR NO KEY UPDATE: the FK inserts on submissions/solves/awards take FOR KEY SHARE on
// this row, which FOR UPDATE would block — a wrong answer must never wait on a lock.
// It still conflicts with itself, so two concurrent spends by one account serialize.
func (q *Queries) LockUserForSpend(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForSpend, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
